// =============================================================================
// auto_build_prep.js — Campistry Auto Build Prep v1.0.0
// =============================================================================
//
// PURPOSE:
//   Owns everything that happens BEFORE the solver runs in auto-build mode.
//   This is the replacement for the scattered pre-generation setup code that
//   currently lives inside auto_schedule_planner.js and daily_adjustments.js.
//
// RESPONSIBILITIES:
//   1. Aggressive full wipe of schedule state (auto mode is always authoritative)
//   2. Build divisionTimes directly from engine skeleton output (never from storage)
//   3. Store engine bunk overrides in the correct auto-specific location
//   4. Set all auto-mode flags so downstream systems behave correctly
//   5. Lock divisionTimes during generation to prevent stale storage restores
//
// WHAT THIS INTENTIONALLY DOES NOT DO:
//   - Write to campManualSkeleton_{dateKey}      ← manual builder's territory
//   - Write to app1.dailySkeletons               ← manual builder's territory
//   - Set window.manualSkeleton                  ← causes contamination
//   - Read from storage for skeleton data        ← auto skeleton comes from engine only
//
// LOAD ORDER:
//   auto_build_engine.js → auto_build_prep.js → auto_build_solver_adapter.js
//                        → auto_build_post_process.js → auto_build_pipeline.js
//
// PUBLIC API:
//   window.AutoBuildPrep.prepare(engineResult, options) → { ok, error }
//   window.AutoBuildPrep.wipe(dateKey)
//   window.AutoBuildPrep.buildDivisionTimes(skeleton)
//   window.AutoBuildPrep.storeEngineOutput(engineResult, dateKey)
//   window.AutoBuildPrep.lockDivisionTimes()
//   window.AutoBuildPrep.unlockDivisionTimes()
//
// =============================================================================

(function () {
    'use strict';

    var VERSION = '1.0.0';

    function log()  { console.log.apply(console,  ['[AutoBuildPrep]'].concat(Array.prototype.slice.call(arguments))); }
    function warn() { console.warn.apply(console, ['[AutoBuildPrep]'].concat(Array.prototype.slice.call(arguments))); }
    function err()  { console.error.apply(console,['[AutoBuildPrep]'].concat(Array.prototype.slice.call(arguments))); }

    // =========================================================================
    // INTERNAL STATE
    // =========================================================================

    var _divisionTimesLocked = false;   // prevents stale storage restore mid-generation
    var _originalLoadCurrentDailyData = null;  // saved ref for unlock

    // =========================================================================
    // 1. FULL WIPE
    // =========================================================================
    //
    // In auto mode the engine output is always the single source of truth.
    // We must nuke all stale schedule state before the solver runs so nothing
    // from a previous generation (or a manual session) bleeds in.
    //
    // This is more aggressive than the manual-mode wipe in scheduler_core_main.js
    // because auto mode never needs to preserve anything — the engine rebuilds
    // from scratch every time.

    function wipe(dateKey) {
        log('★ FULL WIPE for', dateKey);

        // 1. Clear in-memory schedule globals
        window.scheduleAssignments  = {};
        window.leagueAssignments    = {};
        window.fieldUsageBySlot     = {};
        window._autoBunkOverrides   = [];
        window._autoGeneratedSchedule = false;
        window._autoBuildTimelines  = null;

        // 2. Clear divisionTimes (will be rebuilt from engine output)
        window.divisionTimes = {};

        // 3. Nuke the primary daily data store for this date
        //    (campDailyData_v1 is what saveCurrentDailyData/loadCurrentDailyData uses)
        try {
            var DAILY_KEY = 'campDailyData_v1';
            var allData = JSON.parse(localStorage.getItem(DAILY_KEY) || '{}');
            if (allData[dateKey]) {
                delete allData[dateKey];
                localStorage.setItem(DAILY_KEY, JSON.stringify(allData));
                log('Cleared campDailyData_v1 for', dateKey);
            }
        } catch (e) {
            warn('Failed to clear campDailyData_v1:', e);
        }

        // 4. Nuke the orchestrator's key too
        try {
            var ORCH_KEY = 'campistry_schedule_data';
            var orchData = JSON.parse(localStorage.getItem(ORCH_KEY) || '{}');
            if (orchData[dateKey]) {
                delete orchData[dateKey];
                localStorage.setItem(ORCH_KEY, JSON.stringify(orchData));
                log('Cleared campistry_schedule_data for', dateKey);
            }
        } catch (e) {
            warn('Failed to clear campistry_schedule_data:', e);
        }

        // 5. Clear auto-specific keys
        try {
            localStorage.removeItem('campAutoSchedule_' + dateKey);
            localStorage.removeItem('campAutoDivisionTimes_' + dateKey);
        } catch (e) {
            warn('Failed to clear auto-specific localStorage keys:', e);
        }

        // 6. Optionally delete from cloud to prevent rehydration of stale data
        //    We do this async and don't block on it
        _deleteFromCloud(dateKey);

        log('Wipe complete for', dateKey);
    }

    function _deleteFromCloud(dateKey) {
        try {
            var client = window.CampistryDB?.getClient?.() || window.supabase;
            var campId = window.CampistryDB?.getCampId?.() || (typeof window.getCampId === 'function' ? window.getCampId() : null);
            if (!client || !campId) return;

            client
                .from('daily_schedules')
                .delete()
                .eq('camp_id', campId)
                .eq('date_key', dateKey)
                .then(function(res) {
                    if (res.error) warn('Cloud delete failed (non-critical):', res.error.message);
                    else log('Cloud records cleared for', dateKey);
                });
        } catch (e) {
            warn('Cloud delete skipped:', e);
        }
    }

    // =========================================================================
    // 2. BUILD DIVISION TIMES FROM ENGINE SKELETON
    // =========================================================================
    //
    // Auto mode NEVER restores divisionTimes from localStorage — the engine
    // skeleton is always the authoritative time structure.  The
    // division_times_integration.js patch tries to restore from storage; we
    // lock divisionTimes BEFORE calling the optimizer to prevent that.

    function buildDivisionTimes(skeleton) {
        if (!skeleton || skeleton.length === 0) {
            warn('buildDivisionTimes: skeleton is empty');
            return false;
        }

        if (!window.DivisionTimesSystem?.buildFromSkeleton) {
            warn('DivisionTimesSystem not loaded — cannot build division times');
            return false;
        }

        var divisions = window.divisions
            || window.loadGlobalSettings?.()?.app1?.divisions
            || {};

        var divisionTimes = window.DivisionTimesSystem.buildFromSkeleton(skeleton, divisions);
        window.divisionTimes = divisionTimes;

        log('Built divisionTimes for', Object.keys(divisionTimes).length, 'divisions from engine skeleton');
        return true;
    }

    // =========================================================================
    // 3. LOCK / UNLOCK DIVISION TIMES
    // =========================================================================
    //
    // division_times_integration.js wraps loadCurrentDailyData to restore
    // divisionTimes from localStorage.  During auto generation that restore
    // would overwrite the freshly-built auto divisionTimes with stale manual
    // data — exactly the bug we're preventing here.
    //
    // We patch loadCurrentDailyData to strip the divisionTimes field while the
    // lock is active.  The original is restored after generation completes.

    function lockDivisionTimes() {
        if (_divisionTimesLocked) return;

        var original = window.loadCurrentDailyData;
        if (typeof original !== 'function') return;

        _originalLoadCurrentDailyData = original;
        _divisionTimesLocked = true;

        window.loadCurrentDailyData = function () {
            var data = original.apply(this, arguments) || {};
            // Strip divisionTimes so the integration layer never overwrites ours
            var cleaned = Object.assign({}, data);
            delete cleaned.divisionTimes;
            return cleaned;
        };

        log('divisionTimes locked — storage restores will be ignored during generation');
    }

    function unlockDivisionTimes() {
        if (!_divisionTimesLocked) return;

        if (_originalLoadCurrentDailyData) {
            window.loadCurrentDailyData = _originalLoadCurrentDailyData;
            _originalLoadCurrentDailyData = null;
        }
        _divisionTimesLocked = false;
        log('divisionTimes unlocked');
    }

    // =========================================================================
    // 4. STORE ENGINE OUTPUT
    // =========================================================================
    //
    // Writes engine results to AUTO-SPECIFIC storage paths only.
    // NEVER touches:
    //   - campManualSkeleton_{dateKey}    ← manual builder
    //   - app1.dailySkeletons             ← manual builder
    //   - window.manualSkeleton           ← manual builder
    //
    // The auto pipeline owns:
    //   - campDailyData_v1[dateKey].autoSkeleton
    //   - campDailyData_v1[dateKey].bunkActivityOverrides   (← what Step 2 reads)
    //   - window._autoBunkOverrides                          (← what Step 2 also reads)
    //   - window._autoGeneratedSchedule
    //   - window._autoBuildTimelines

    function storeEngineOutput(engineResult, dateKey) {
        if (!engineResult) { err('storeEngineOutput: no engine result'); return; }

        var skeleton      = engineResult.skeleton      || [];
        var bunkOverrides = engineResult.bunkOverrides || [];
        var bunkTimelines = engineResult.bunkTimelines || {};

        // ── In-memory globals ──────────────────────────────────────────────
        window._autoGeneratedSchedule = true;
        window._autoBuildTimelines    = bunkTimelines;
        window._autoBunkOverrides     = bunkOverrides;

        // ── Expose skeleton on the globals the solver reads ────────────────
        // NOTE: We set window.skeleton (the generic ref) but NOT window.manualSkeleton.
        //       runSkeletonOptimizer receives the skeleton as its first argument,
        //       so these window globals are only fallback references.
        window.skeleton = skeleton;

        // ── Persist to auto-specific daily data keys ───────────────────────
        if (typeof window.saveCurrentDailyData === 'function') {
            window.saveCurrentDailyData('autoSkeleton', skeleton);
            window.saveCurrentDailyData('_autoGenerated', true);
            window.saveCurrentDailyData('_autoBuildTimelines', bunkTimelines);

            if (bunkOverrides.length > 0) {
                // 'bunkActivityOverrides' is what scheduler_core_main STEP 2 reads
                window.saveCurrentDailyData('bunkActivityOverrides', bunkOverrides);
            }

            // Persist the freshly-built divisionTimes
            if (window.divisionTimes && Object.keys(window.divisionTimes).length > 0) {
                var serialized = window.DivisionTimesSystem?.serialize?.(window.divisionTimes)
                              || window.divisionTimes;
                window.saveCurrentDailyData('divisionTimes', serialized);
            }
        }

        log('Engine output stored:', {
            skeletonBlocks: skeleton.length,
            bunkOverrides:  bunkOverrides.length,
            dateKey
        });
    }

    // =========================================================================
    // 5. MAIN PREPARE FUNCTION
    // =========================================================================
    //
    // Called by AutoBuildPipeline before the solver runs.
    // Returns { ok: true } or { ok: false, error: string }.

    function prepare(engineResult, options) {
        options = options || {};

        var dateKey = options.dateKey
            || window.currentScheduleDate
            || new Date().toISOString().split('T')[0];

        // Validate engine result
        if (!engineResult || !engineResult.skeleton || engineResult.skeleton.length === 0) {
            return { ok: false, error: 'Engine result has no skeleton blocks' };
        }

        log('='.repeat(60));
        log('AUTO BUILD PREP — ' + dateKey);
        log('='.repeat(60));

        try {
            // Step A: Full wipe
            wipe(dateKey);

            // Step B: Build divisionTimes from engine skeleton
            var dtOk = buildDivisionTimes(engineResult.skeleton);
            if (!dtOk) {
                warn('divisionTimes build failed — solver may use fallback time structure');
            }

            // Step C: Store engine output to auto-specific paths
            storeEngineOutput(engineResult, dateKey);

            // Step D: Lock divisionTimes against storage restores
            lockDivisionTimes();

            log('Prep complete — ready for solver');
            return { ok: true, dateKey };

        } catch (e) {
            err('Prep failed:', e);
            unlockDivisionTimes(); // safety: always unlock on error
            return { ok: false, error: String(e) };
        }
    }

    // =========================================================================
    // PUBLIC API
    // =========================================================================

    window.AutoBuildPrep = {
        VERSION,
        prepare,
        wipe,
        buildDivisionTimes,
        storeEngineOutput,
        lockDivisionTimes,
        unlockDivisionTimes
    };

    log('Auto Build Prep v' + VERSION + ' loaded');

})();
