// =============================================================================
// auto_build_post_process.js — Campistry Auto Build Post Process v1.0.0
// =============================================================================
//
// PURPOSE:
//   Owns everything that happens AFTER the solver completes in auto-build mode.
//   This is the replacement for the scattered post-generation code in
//   auto_schedule_planner.js and daily_adjustments.js.
//
// RESPONSIBILITIES:
//   1. Save completed schedule to auto-specific storage paths (NOT manual paths)
//   2. Persist the final divisionTimes (post-solver, with any fixes applied)
//   3. Fire campistry-generation-complete event so other systems can react
//   4. Set Gantt/timeline rendering flags for the auto-generated view
//   5. Update the UI table
//   6. Release the divisionTimes lock (set by AutoBuildPrep)
//
// WHAT THIS INTENTIONALLY DOES NOT DO:
//   - Call window.saveSchedule() on the manual path
//   - Trigger saveDailySkeleton() (manual builder's save path)
//   - Write window.manualSkeleton
//
// PUBLIC API:
//   window.AutoBuildPostProcess.finalize(engineResult, options) → Promise<{ok}>
//
// =============================================================================

(function () {
    'use strict';

    var VERSION = '1.0.0';

    function log()  { console.log.apply(console,  ['[AutoBuildPostProcess]'].concat(Array.prototype.slice.call(arguments))); }
    function warn() { console.warn.apply(console, ['[AutoBuildPostProcess]'].concat(Array.prototype.slice.call(arguments))); }
    function err()  { console.error.apply(console,['[AutoBuildPostProcess]'].concat(Array.prototype.slice.call(arguments))); }

    // =========================================================================
    // 1. SAVE COMPLETED SCHEDULE
    // =========================================================================
    //
    // After the solver runs, window.scheduleAssignments and window.leagueAssignments
    // contain the completed schedule.  We save these to the unified schedule system
    // (cloud + localStorage) using the auto-specific save path.
    //
    // The UnifiedScheduleSystem / ScheduleSync handle the actual cloud writes —
    // we just need to trigger them correctly.

    async function _saveCompletedSchedule(dateKey, engineResult) {
        log('Saving completed schedule for', dateKey);

        var scheduleData = {
            scheduleAssignments:  window.scheduleAssignments  || {},
            leagueAssignments:    window.leagueAssignments    || {},
            unifiedTimes:         window.unifiedTimes         || [],
            divisionTimes:        _serializeDivisionTimes(),
            isRainyDay:           window.isRainyDay           || false,
            rainyDayStartTime:    window.rainyDayStartTime    ?? null,
            // Auto-mode markers
            _autoGenerated:       true,
            _autoSkeleton:        engineResult.skeleton       || [],
            _autoBuildTimelines:  engineResult.bunkTimelines  || {},
        };

        // Path A: saveCurrentDailyData (writes to campDailyData_v1)
        if (typeof window.saveCurrentDailyData === 'function') {
            window.saveCurrentDailyData('scheduleAssignments',  scheduleData.scheduleAssignments);
            window.saveCurrentDailyData('leagueAssignments',    scheduleData.leagueAssignments);
            window.saveCurrentDailyData('unifiedTimes',         scheduleData.unifiedTimes);
            window.saveCurrentDailyData('divisionTimes',        scheduleData.divisionTimes);
            window.saveCurrentDailyData('_autoGenerated',       true);
            window.saveCurrentDailyData('_autoBuildTimelines',  scheduleData._autoBuildTimelines);
            log('Saved via saveCurrentDailyData');
        }

        // Path B: ScheduleSync queue (cloud push)
        if (window.ScheduleSync?.queueSave) {
            window.ScheduleSync.queueSave(dateKey, scheduleData);
            log('Queued cloud save via ScheduleSync');
        }

        // Path C: Direct cloud save via the unified save helper (if available)
        // This handles cross-scheduler RBAC-aware writes.
        if (window.saveSchedule) {
            try {
                await window.saveSchedule();
                log('saveSchedule() completed');
            } catch (e) {
                warn('saveSchedule() threw (non-critical):', e);
            }
        }
    }

    function _serializeDivisionTimes() {
        if (!window.divisionTimes) return {};
        if (window.DivisionTimesSystem?.serialize) {
            return window.DivisionTimesSystem.serialize(window.divisionTimes);
        }
        return window.divisionTimes;
    }

    // =========================================================================
    // 2. APPLY POST-GENERATION FIXES
    // =========================================================================
    //
    // DivisionTimesSystem fires its own post-generation hook via the
    // campistry-generation-complete event.  We call any additional auto-specific
    // fixes here before firing that event.

    function _applyPostGenerationFixes() {
        // Fix mismatched bunk slot-count arrays (DivisionTimesSystem utility)
        if (typeof window.fixAllBunkSlotCounts === 'function') {
            var fixes = window.fixAllBunkSlotCounts();
            if (fixes && fixes.fixed > 0) {
                log('fixAllBunkSlotCounts applied', fixes.fixed, 'fixes');
            }
        }

        // Fill any missing pinned slots
        if (typeof window.fillMissingPinnedSlots === 'function') {
            var filled = window.fillMissingPinnedSlots();
            if (filled > 0) log('fillMissingPinnedSlots filled', filled, 'slots');
        }
    }

    // =========================================================================
    // 3. FIRE GENERATION-COMPLETE EVENT
    // =========================================================================
    //
    // Other systems (DivisionTimesSystem, GlobalFieldLocks, etc.) listen for
    // this event to run their own post-generation cleanup.

    function _fireGenerationCompleteEvent(dateKey) {
        var detail = {
            dateKey,
            autoGenerated: true,
            bunkCount: Object.keys(window.scheduleAssignments || {}).length
        };

        window.dispatchEvent(new CustomEvent('campistry-generation-complete', { detail }));
        log('Fired campistry-generation-complete for', dateKey, '—',
            detail.bunkCount, 'bunks');
    }

    // =========================================================================
    // 4. SET GANTT / TIMELINE RENDERING FLAGS
    // =========================================================================
    //
    // The Gantt renderer checks these flags to decide whether to show the
    // auto-generated timeline view vs the standard table.

    function _setRenderingFlags(engineResult) {
        window._autoGeneratedSchedule = true;
        window._autoBuildTimelines    = engineResult.bunkTimelines || {};
        log('Gantt rendering flags set');
    }

    // =========================================================================
    // 5. UPDATE UI
    // =========================================================================

    function _updateUI() {
        // Standard table refresh
        if (typeof window.updateTable === 'function') {
            try { window.updateTable(); } catch (e) { warn('updateTable threw:', e); }
        }

        // Debug field locks (if enabled)
        if (window.GlobalFieldLocks?.debugPrintLocks) {
            window.GlobalFieldLocks.debugPrintLocks();
        }
    }

    // =========================================================================
    // 6. RELEASE DIVISION TIMES LOCK
    // =========================================================================

    function _releaseLocks() {
        if (window.AutoBuildPrep?.unlockDivisionTimes) {
            window.AutoBuildPrep.unlockDivisionTimes();
        }
    }

    // =========================================================================
    // MAIN FINALIZE FUNCTION
    // =========================================================================

    async function finalize(engineResult, options) {
        options = options || {};

        var dateKey = options.dateKey
            || window.currentScheduleDate
            || new Date().toISOString().split('T')[0];

        log('='.repeat(60));
        log('AUTO BUILD POST PROCESS — ' + dateKey);
        log('='.repeat(60));

        try {
            // 1. Apply post-generation fixes (before saving so fixes are persisted)
            _applyPostGenerationFixes();

            // 2. Set rendering flags
            _setRenderingFlags(engineResult);

            // 3. Save the completed schedule (cloud + localStorage)
            await _saveCompletedSchedule(dateKey, engineResult);

            // 4. Fire the generation-complete event
            //    (DivisionTimesSystem, etc. run their own hooks here)
            _fireGenerationCompleteEvent(dateKey);

            // 5. Update UI
            _updateUI();

            log('Post-process complete ✅');
            return { ok: true };

        } catch (e) {
            err('Post-process failed:', e);
            return { ok: false, error: String(e) };

        } finally {
            // Always release the lock even if something above threw
            _releaseLocks();
        }
    }

    // =========================================================================
    // PUBLIC API
    // =========================================================================

    window.AutoBuildPostProcess = {
        VERSION,
        finalize
    };

    log('Auto Build Post Process v' + VERSION + ' loaded');

})();
