// =============================================================================
// auto_build_pipeline.js — Campistry Auto Build Pipeline v1.0.0
// =============================================================================
//
// PURPOSE:
//   Single entry point for all auto-build schedule generation.
//   Replaces the duplicated, scattered pipeline code in:
//     - auto_schedule_planner.js  (genBtn onclick)
//     - daily_adjustments.js      (auto mode generate handler)
//
// ARCHITECTURE:
//
//   Caller (auto_schedule_planner / daily_adjustments / any future UI)
//       │
//       ▼
//   AutoBuildPipeline.run(layers, options)
//       │
//       ├── Phase 1: ENGINE
//       │     AutoBuildEngine.build()
//       │     → { skeleton, bunkOverrides, bunkTimelines, warnings }
//       │
//       ├── Phase 2: PREP          (auto_build_prep.js)
//       │     AutoBuildPrep.prepare()
//       │     → full wipe, build divisionTimes, store engine output, lock DT
//       │
//       ├── Phase 3: SOLVE         (auto_build_solver_adapter.js)
//       │     AutoBuildSolverAdapter.run()
//       │     → calls runSkeletonOptimizer with auto-mode flags
//       │
//       └── Phase 4: POST-PROCESS  (auto_build_post_process.js)
//             AutoBuildPostProcess.finalize()
//             → save, fire events, update UI, release locks
//
// CALLERS SHOULD REPLACE THEIR INLINE PIPELINE WITH:
//
//   // Old (scattered, problematic):
//   var result = window.AutoBuildEngine.build({ layers, dateStr });
//   window._autoGeneratedSchedule = true;
//   window._autoBuildTimelines = result.bunkTimelines;
//   window.manualSkeleton = result.skeleton;   ← contamination
//   ... (dozens of lines) ...
//   window.runSkeletonOptimizer(result.skeleton);
//
//   // New (clean):
//   var pipelineResult = await window.AutoBuildPipeline.run(layers, { dateStr });
//   if (pipelineResult.ok) { notify('Generated!', 'success'); }
//   else                   { notify(pipelineResult.error, 'error'); }
//
// PUBLIC API:
//   window.AutoBuildPipeline.run(layers, options)   → Promise<PipelineResult>
//   window.AutoBuildPipeline.preview(layers, options) → EngineResult | null
//   window.AutoBuildPipeline.validate(layers, dateStr) → string[]
//   window.AutoBuildPipeline.isRunning()            → boolean
//
// PipelineResult:
//   { ok: boolean, phase: string, error?: string, engineResult?: object,
//     warnings?: string[], stats?: object }
//
// Options:
//   dateStr          — override date (default: window.currentScheduleDate)
//   allowedDivisions — RBAC division filter (default: AccessControl result)
//   externalOverrides — passed to runSkeletonOptimizer as arg 2
//   existingSnapshot  — passed to runSkeletonOptimizer as arg 4
//   existingUnified   — passed to runSkeletonOptimizer as arg 5
//   onPhaseChange     — callback(phase, detail) for progress tracking
//
// =============================================================================

(function () {
    'use strict';

    var VERSION = '1.0.0';

    function log()  { console.log.apply(console,  ['[AutoBuildPipeline]'].concat(Array.prototype.slice.call(arguments))); }
    function warn() { console.warn.apply(console, ['[AutoBuildPipeline]'].concat(Array.prototype.slice.call(arguments))); }
    function err()  { console.error.apply(console,['[AutoBuildPipeline]'].concat(Array.prototype.slice.call(arguments))); }

    // =========================================================================
    // STATE
    // =========================================================================

    var _isRunning = false;

    // =========================================================================
    // DEPENDENCY CHECK
    // =========================================================================

    function _checkDependencies() {
        var missing = [];
        if (!window.AutoBuildEngine)       missing.push('AutoBuildEngine (auto_build_engine.js)');
        if (!window.AutoBuildPrep)         missing.push('AutoBuildPrep (auto_build_prep.js)');
        if (!window.AutoBuildSolverAdapter)missing.push('AutoBuildSolverAdapter (auto_build_solver_adapter.js)');
        if (!window.AutoBuildPostProcess)  missing.push('AutoBuildPostProcess (auto_build_post_process.js)');

        if (missing.length > 0) {
            return { ok: false, error: 'Missing dependencies: ' + missing.join(', ') };
        }

        if (typeof window.runSkeletonOptimizer !== 'function') {
            return { ok: false, error: 'runSkeletonOptimizer not loaded (scheduler_core_main.js missing)' };
        }

        return { ok: true };
    }

    // =========================================================================
    // PROGRESS REPORTING
    // =========================================================================

    function _phase(name, detail, onPhaseChange) {
        log('[Phase: ' + name + ']', detail || '');
        if (typeof onPhaseChange === 'function') {
            try { onPhaseChange(name, detail); } catch (e) { /* ignore */ }
        }
    }

    // =========================================================================
    // NORMALIZE LAYERS
    // =========================================================================
    //
    // Callers may pass layers in different shapes:
    //   A) A flat array of layers (each with a .grade property)
    //   B) An object keyed by grade: { '1st Grade': [layer, ...], ... }
    //
    // AutoBuildEngine.build() expects a flat array with .grade on each layer.

    function _normalizeLayers(layers) {
        if (!layers) return [];

        // Shape B: keyed by grade
        if (!Array.isArray(layers) && typeof layers === 'object') {
            var flat = [];
            Object.keys(layers).forEach(function (grade) {
                var gradeLayers = layers[grade];
                if (!Array.isArray(gradeLayers)) return;
                gradeLayers.forEach(function (layer) {
                    flat.push(Object.assign({}, layer, { grade: layer.grade || grade }));
                });
            });
            return flat;
        }

        // Shape A: already a flat array
        return layers;
    }

    // =========================================================================
    // VALIDATE LAYERS (PRE-FLIGHT)
    // =========================================================================

    function validate(layers, dateStr) {
        if (!window.AutoBuildEngine) return ['AutoBuildEngine not loaded'];
        var flat = _normalizeLayers(layers);
        return window.AutoBuildEngine.validate(flat, dateStr) || [];
    }

    // =========================================================================
    // PREVIEW (ENGINE ONLY — NO SOLVER, NO SIDE EFFECTS)
    // =========================================================================
    //
    // Runs the engine and returns its output for inspection without touching any
    // schedule state.  Safe to call at any time.

    function preview(layers, options) {
        options = options || {};
        if (!window.AutoBuildEngine) {
            warn('preview: AutoBuildEngine not loaded');
            return null;
        }
        var flat    = _normalizeLayers(layers);
        var dateStr = options.dateStr
            || window.currentScheduleDate
            || new Date().toISOString().split('T')[0];

        try {
            return window.AutoBuildEngine.build({ layers: flat, dateStr });
        } catch (e) {
            err('preview failed:', e);
            return null;
        }
    }

    // =========================================================================
    // MAIN RUN
    // =========================================================================

    async function run(layers, options) {
        options = options || {};

        // Prevent concurrent runs
        if (_isRunning) {
            return { ok: false, phase: 'guard', error: 'Auto build already in progress' };
        }
        _isRunning = true;

        var onPhaseChange = options.onPhaseChange || null;
        var dateStr = options.dateStr
            || window.currentScheduleDate
            || new Date().toISOString().split('T')[0];

        log('═'.repeat(66));
        log('AUTO BUILD PIPELINE v' + VERSION + ' — ' + dateStr);
        log('═'.repeat(66));

        var engineResult = null;

        try {
            // ─────────────────────────────────────────────────────────────────
            // PRE-FLIGHT: dependency check
            // ─────────────────────────────────────────────────────────────────
            var depCheck = _checkDependencies();
            if (!depCheck.ok) {
                return { ok: false, phase: 'preflight', error: depCheck.error };
            }

            // ─────────────────────────────────────────────────────────────────
            // PRE-FLIGHT: layer normalization & validation
            // ─────────────────────────────────────────────────────────────────
            var flatLayers = _normalizeLayers(layers);
            if (flatLayers.length === 0) {
                return { ok: false, phase: 'preflight', error: 'No layers defined — add layers before generating' };
            }

            var validationErrors = validate(flatLayers, dateStr);
            if (validationErrors.length > 0) {
                warn('Validation errors:', validationErrors);
                // Non-fatal: log warnings but continue (engine handles them gracefully)
            }

            // ─────────────────────────────────────────────────────────────────
            // PHASE 1: ENGINE
            // Build the skeleton, bunk overrides, and per-bunk timelines.
            // This is pure computation — no side effects.
            // ─────────────────────────────────────────────────────────────────
            _phase('engine', 'Building skeleton from ' + flatLayers.length + ' layers…', onPhaseChange);

            try {
                engineResult = window.AutoBuildEngine.build({ layers: flatLayers, dateStr });
            } catch (e) {
                return { ok: false, phase: 'engine', error: 'AutoBuildEngine threw: ' + String(e) };
            }

            if (!engineResult || !engineResult.skeleton || engineResult.skeleton.length === 0) {
                return {
                    ok: false,
                    phase: 'engine',
                    error: 'Engine produced no skeleton blocks — check your layers for time/type conflicts',
                    warnings: engineResult?.warnings || []
                };
            }

            log('Engine output: ' + engineResult.skeleton.length + ' skeleton blocks, '
                + (engineResult.bunkOverrides?.length || 0) + ' bunk overrides, '
                + (engineResult.warnings?.length || 0) + ' warnings');

            if (engineResult.warnings?.length > 0) {
                engineResult.warnings.forEach(function (w) { warn('[Engine warning]', w); });
            }

            // ─────────────────────────────────────────────────────────────────
            // PHASE 2: PREP
            // Full wipe → build divisionTimes → store engine output → lock DT.
            // ─────────────────────────────────────────────────────────────────
            _phase('prep', 'Wiping state and building division times…', onPhaseChange);

            var prepResult = window.AutoBuildPrep.prepare(engineResult, {
                dateKey: dateStr
            });

            if (!prepResult.ok) {
                return { ok: false, phase: 'prep', error: prepResult.error };
            }

            // ─────────────────────────────────────────────────────────────────
            // PHASE 3: SOLVE
            // Adapter calls runSkeletonOptimizer with auto-mode flags set.
            // ─────────────────────────────────────────────────────────────────
            _phase('solve', 'Running solver…', onPhaseChange);

            var solveResult = await window.AutoBuildSolverAdapter.run(engineResult, {
                dateKey:          dateStr,
                allowedDivisions: options.allowedDivisions   || null,
                externalOverrides:options.externalOverrides  || null,
                existingSnapshot: options.existingSnapshot   || null,
                existingUnified:  options.existingUnified    || null
            });

            if (!solveResult.ok) {
                return { ok: false, phase: 'solve', error: solveResult.error };
            }

            // ─────────────────────────────────────────────────────────────────
            // PHASE 4: POST-PROCESS
            // Save, fire events, update UI, release locks.
            // ─────────────────────────────────────────────────────────────────
            _phase('postprocess', 'Saving and updating UI…', onPhaseChange);

            var postResult = await window.AutoBuildPostProcess.finalize(engineResult, {
                dateKey: dateStr
            });

            if (!postResult.ok) {
                // Post-process failure is logged but we still consider the generation
                // successful — the schedule is built; only persistence/UI failed.
                warn('Post-process had issues (schedule may still be correct):', postResult.error);
            }

            // ─────────────────────────────────────────────────────────────────
            // SUCCESS
            // ─────────────────────────────────────────────────────────────────
            var bunkCount = Object.keys(window.scheduleAssignments || {}).length;
            log('═'.repeat(66));
            log('★ AUTO BUILD PIPELINE COMPLETE ★');
            log('  Skeleton:   ' + engineResult.skeleton.length + ' blocks');
            log('  Overrides:  ' + (engineResult.bunkOverrides?.length || 0));
            log('  Bunks:      ' + bunkCount);
            log('  Warnings:   ' + (engineResult.warnings?.length || 0));
            log('═'.repeat(66));

            _phase('done', 'Complete', onPhaseChange);

            return {
                ok:           true,
                phase:        'done',
                engineResult,
                warnings:     engineResult.warnings || [],
                stats: {
                    skeletonBlocks: engineResult.skeleton.length,
                    bunkOverrides:  engineResult.bunkOverrides?.length || 0,
                    bunkCount,
                    date:           dateStr
                }
            };

        } catch (e) {
            err('Pipeline threw unexpected error:', e);
            // Safety: always release locks if something blew up
            window.AutoBuildPrep?.unlockDivisionTimes?.();
            window._generationInProgress = false;

            return {
                ok:    false,
                phase: 'unknown',
                error: String(e)
            };

        } finally {
            _isRunning = false;
        }
    }

    // =========================================================================
    // PUBLIC API
    // =========================================================================

    window.AutoBuildPipeline = {
        VERSION,
        run,
        preview,
        validate,
        isRunning: function () { return _isRunning; }
    };

    log('Auto Build Pipeline v' + VERSION + ' loaded');

})();
