// =============================================================================
// bunk_engine_integration.js — Wires BunkScheduleEngine into the existing
// daily_adjustments.js generate flow for AUTO mode.
// =============================================================================
//
// HOW IT PLUGS IN:
//   The existing runOptimizer() in daily_adjustments.js checks
//   window._daBuilderMode. When it's 'auto', it currently calls AutoBuildEngine.
//   This file replaces that call with BunkScheduleEngine when the camp has
//   opted into the new per-bunk pipeline.
//
//   The camp-level flag is:   globalSettings.app1.generationMode === 'bunk'
//   The old auto engine runs: globalSettings.app1.generationMode === 'grade' (or absent)
//
// OUTPUT FORMAT:
//   BunkScheduleEngine outputs bunkTimelines keyed by bunk name.
//   This integration layer:
//     1. Stores bunkTimelines as the canonical source of truth
//     2. Saves to campDailyData_v1 alongside scheduleAssignments
//     3. Triggers history update
//     4. Fires the existing 'campistry-generation-complete' event so
//        all downstream hooks (save, sync, Gantt) fire as normal
//
// =============================================================================

(function () {
    'use strict';

    // -------------------------------------------------------------------------
    // Check which generation mode this camp uses
    // -------------------------------------------------------------------------
    function getGenerationMode() {
        var g = window.loadGlobalSettings?.() || {};
        return g.app1?.generationMode || 'grade'; // 'grade' = existing, 'bunk' = new
    }

    function isBunkMode() {
        var g = window.loadGlobalSettings?.() || {};
        return g.app1?.generationMode === 'bunk';
    }

    // -------------------------------------------------------------------------
    // MAIN: Run the bunk-level generation pipeline
    // Called from the Generate button when mode='auto' AND generationMode='bunk'
    // -------------------------------------------------------------------------
    async function runBunkGeneration(dateStr, daAutoLayers, onComplete, onError) {
        if (!window.BunkScheduleEngine) {
            onError?.('BunkScheduleEngine not loaded');
            return;
        }

        console.log('[BunkIntegration] Starting bunk-level generation for', dateStr);

        try {
            // ── 1. Full pre-generation wipe (same as existing pipeline) ──────
            window.scheduleAssignments = {};
            window.leagueAssignments = {};

            try {
                var DAILY_KEY = 'campDailyData_v1';
                var allData = JSON.parse(localStorage.getItem(DAILY_KEY) || '{}');
                if (allData[dateStr]) {
                    delete allData[dateStr];
                    localStorage.setItem(DAILY_KEY, JSON.stringify(allData));
                }
            } catch (e) {
                console.warn('[BunkIntegration] localStorage wipe failed:', e);
            }

            // Cloud delete
            try {
                var client = window.CampistryDB?.getClient?.() || window.supabase;
                var campId = window.CampistryDB?.getCampId?.() || window.getCampId?.();
                if (client && campId) {
                    await client.from('daily_schedules').delete()
                        .eq('camp_id', campId).eq('date_key', dateStr);
                }
            } catch (e) {
                console.warn('[BunkIntegration] Cloud wipe failed:', e);
            }

            window.GlobalFieldLocks?.clearAllLocks?.();
            window._preGenClearActive = true;
            window._generationInProgress = true;

            // ── 2. Run the engine ─────────────────────────────────────────────
            var result = window.BunkScheduleEngine.build({
                dateStr: dateStr,
                layers: daAutoLayers
            });

            window._preGenClearActive = false;
            window._generationInProgress = false;

            if (!result || Object.keys(result.bunkTimelines || {}).length === 0) {
                onError?.('BunkScheduleEngine produced no timelines — check layers and division config');
                return;
            }

            // ── 3. Store bunkTimelines as primary data ────────────────────────
            window._autoBuildTimelines = result.bunkTimelines;
            window._autoGeneratedSchedule = true;
            window._bunkModeActive = true;

            // Also produce a scheduleAssignments-compatible structure for any
            // existing code that reads it. Each bunk gets a flat array of entries
            // indexed by a synthetic slot index (one per minute-block).
            // NOTE: This is approximate — the renderer should prefer bunkTimelines.
            var syntheticAssignments = buildSyntheticAssignments(result.bunkTimelines);
            window.scheduleAssignments = syntheticAssignments;

            // ── 4. Persist ────────────────────────────────────────────────────
            var dataToSave = {
                scheduleAssignments: syntheticAssignments,
                bunkTimelines: result.bunkTimelines,
                leagueAssignments: {},
                _autoGenerated: true,
                _generationMode: 'bunk',
                _buildVersion: result._buildVersion,
                savedAt: new Date().toISOString()
            };

            // Save to localStorage
            try {
                var DAILY_KEY2 = 'campDailyData_v1';
                var existing = JSON.parse(localStorage.getItem(DAILY_KEY2) || '{}');
                existing[dateStr] = dataToSave;
                localStorage.setItem(DAILY_KEY2, JSON.stringify(existing));
            } catch (e) {
                console.warn('[BunkIntegration] localStorage save failed:', e);
            }

            // Trigger existing save hooks
            window.saveCurrentDailyData?.('bunkTimelines', result.bunkTimelines);
            window.saveCurrentDailyData?.('_autoGenerated', true);
            window.saveCurrentDailyData?.('_generationMode', 'bunk');
            window.saveCurrentDailyData?.('_autoBuildTimelines', result.bunkTimelines);

            // Cloud save via existing ScheduleDB
            window.ScheduleDB?.saveSchedule?.(dateStr, dataToSave);

            // ── 5. Fire generation-complete event ────────────────────────────
            window.dispatchEvent(new CustomEvent('campistry-generation-complete', {
                detail: {
                    dateKey: dateStr,
                    mode: 'bunk',
                    bunkCount: Object.keys(result.bunkTimelines).length,
                    warnings: result.warnings
                }
            }));

            // ── 6. Update table / UI ──────────────────────────────────────────
            window.updateTable?.();

            var msg = '✅ Schedule Generated! (' +
                Object.keys(result.bunkTimelines).length + ' bunks';
            if (result.warnings.length > 0) {
                msg += ', ' + result.warnings.length + ' warnings';
            }
            msg += ')';

            console.log('[BunkIntegration] Generation complete:', msg);
            onComplete?.(msg, result);

        } catch (err) {
            window._preGenClearActive = false;
            window._generationInProgress = false;
            console.error('[BunkIntegration] Generation failed:', err);
            onError?.('Generation error: ' + err.message);
        }
    }

    // -------------------------------------------------------------------------
    // Build a synthetic scheduleAssignments structure from bunkTimelines
    // so existing code that reads scheduleAssignments doesn't crash.
    // Each bunk gets an array where each entry is indexed by a 5-minute slot
    // starting from the division's day start.
    // -------------------------------------------------------------------------
    function buildSyntheticAssignments(bunkTimelines) {
        var assignments = {};

        Object.values(bunkTimelines).forEach(function (tl) {
            var bunkName = tl.bunkName;
            assignments[bunkName] = [];

            tl.slots.forEach(function (slot) {
                // Convert to 5-minute slot indices
                var slotIdx = Math.floor((slot.startMin - tl.dayStart) / 5);
                var slotCount = Math.ceil((slot.endMin - slot.startMin) / 5);

                for (var i = 0; i < slotCount; i++) {
                    assignments[bunkName][slotIdx + i] = {
                        _activity: slot.activity || slot.activityType || 'Free',
                        field: slot.field,
                        _autoGenerated: true,
                        _bunkMode: true,
                        _startMin: slot.startMin,
                        _endMin: slot.endMin,
                        continuation: i > 0,
                        _locked: slot.locked || false,
                        _source: slot.source
                    };
                }
            });
        });

        return assignments;
    }

    // -------------------------------------------------------------------------
    // SETTINGS: get/set the generation mode for this camp
    // -------------------------------------------------------------------------
    function setGenerationMode(mode) {
        // mode: 'grade' | 'bunk'
        var g = window.loadGlobalSettings?.() || {};
        g.app1 = g.app1 || {};
        g.app1.generationMode = mode;
        window.saveGlobalSettings?.('app1', g.app1);
        console.log('[BunkIntegration] Generation mode set to:', mode);
    }

    // -------------------------------------------------------------------------
    // PUBLIC API
    // -------------------------------------------------------------------------
    window.BunkEngineIntegration = {
        isBunkMode: isBunkMode,
        getGenerationMode: getGenerationMode,
        setGenerationMode: setGenerationMode,
        runBunkGeneration: runBunkGeneration,
        buildSyntheticAssignments: buildSyntheticAssignments,

        // Called from daily_adjustments.js runOptimizer() — replaces
        // the AutoBuildEngine call when bunk mode is active
        handleAutoGenerate: async function (dateStr, daAutoLayers, showAlert) {
            if (!isBunkMode()) return false; // signal: use existing pipeline

            await runBunkGeneration(
                dateStr,
                daAutoLayers,
                function (msg) { showAlert?.(msg); },
                function (err) { showAlert?.('❌ ' + err); }
            );

            return true; // signal: handled by bunk engine, skip existing pipeline
        }
    };

    console.log('[BunkEngineIntegration] loaded. Mode:', getGenerationMode());

})();
