// =============================================================================
// bunk_engine_integration.js — Wires BunkScheduleEngine into the existing
// daily_adjustments.js generate flow for AUTO mode.
// =============================================================================
//
// HOW IT PLUGS IN:
//   The existing runOptimizer() in daily_adjustments.js checks
//   window._daBuilderMode. When it's 'auto', it currently calls AutoBuildEngine.
//   This file replaces that call with BunkScheduleEngine when the camp has
//   opted into the new per-bunk pipeline.
//
//   The camp-level flag is:   globalSettings.app1.generationMode === 'bunk'
//   The old auto engine runs: globalSettings.app1.generationMode === 'grade' (or absent)
//
// OUTPUT FORMAT:
//   BunkScheduleEngine outputs bunkTimelines keyed by bunk name.
//   This integration layer:
//     1. Stores bunkTimelines as the canonical source of truth
//     2. Saves to campDailyData_v1 alongside scheduleAssignments
//     3. Triggers history update
//     4. Fires the existing 'campistry-generation-complete' event so
//        all downstream hooks (save, sync, Gantt) fire as normal
//
// =============================================================================

(function () {
    'use strict';

    // -------------------------------------------------------------------------
    // Check which generation mode this camp uses
    // -------------------------------------------------------------------------
    function getGenerationMode() {
        var g = window.loadGlobalSettings?.() || {};
        return g.app1?.generationMode || 'grade'; // 'grade' = existing, 'bunk' = new
    }

    function isBunkMode() {
        var g = window.loadGlobalSettings?.() || {};
        return g.app1?.generationMode === 'bunk';
    }

    // -------------------------------------------------------------------------
    // MAIN: Run the bunk-level generation pipeline
    // Called from the Generate button when mode='auto' AND generationMode='bunk'
    // -------------------------------------------------------------------------
   async function runBunkGeneration(dateStr, daAutoLayers, onComplete, onError) {
    if (!window.BunkScheduleEngine) {
        onError?.('BunkScheduleEngine not loaded');
        return;
    }

    console.log('[BunkIntegration] Starting bunk-level generation for', dateStr);

    try {
        // ── 1. Full pre-generation wipe ──────────────────────────────────────
        window.scheduleAssignments = {};
        window.leagueAssignments = {};
        window.GlobalFieldLocks?.clearAllLocks?.();
        window._preGenClearActive = true;
        window._generationInProgress = true;

        // ── 2. Run BunkScheduleEngine (Phases 0-4 only — placement, no assignment) ─
        var result = window.BunkScheduleEngine.build({
            dateStr: dateStr,
            layers: daAutoLayers
        });

        window._preGenClearActive = false;
        window._generationInProgress = false;

        if (!result || Object.keys(result.bunkTimelines || {}).length === 0) {
            onError?.('BunkScheduleEngine produced no timelines — check layers');
            return;
        }

        // ── 3. Build per-bunk divisionTimes ──────────────────────────────────
        // Each bunk gets its own slot array derived from its own timeline.
        // This is _isPerBunk mode — slot indices are unique per bunk.
        var divisions = window.divisions || window.loadGlobalSettings?.()?.app1?.divisions || {};
        var perBunkDivisionTimes = buildPerBunkDivisionTimes(result.bunkTimelines, divisions);
        window.divisionTimes = perBunkDivisionTimes;
        window._autoDivisionTimesBuilt = true;

        // ── 4. Initialize scheduleAssignments with correct slot counts per bunk ─
        Object.values(result.bunkTimelines).forEach(function(tl) {
            var bunkSlots = perBunkDivisionTimes[tl.divisionName]?._perBunkSlots?.[tl.bunkName] || [];
            window.scheduleAssignments[tl.bunkName] = new Array(bunkSlots.length).fill(null);
        });

        // ── 5. Write locked slots (anchors) directly into scheduleAssignments ─
        // These are swim, lunch, snack, dismissal — already fully resolved,
        // solver should not touch them.
        Object.values(result.bunkTimelines).forEach(function(tl) {
            var bunkSlots = perBunkDivisionTimes[tl.divisionName]?._perBunkSlots?.[tl.bunkName] || [];
            tl.slots.forEach(function(slot) {
                if (!slot.locked) return;
                // Find which slot indices this covers
                var indices = findSlotIndices(bunkSlots, slot.startMin, slot.endMin);
                indices.forEach(function(idx) {
                    window.scheduleAssignments[tl.bunkName][idx] = {
                        _activity: slot.activity,
                        field: slot.field || null,
                        _fixed: true,
                        _autoGenerated: true,
                        _startMin: slot.startMin,
                        _endMin: slot.endMin,
                        continuation: false
                    };
                });
                // Mark continuations for multi-slot blocks
                for (var i = 1; i < indices.length; i++) {
                    window.scheduleAssignments[tl.bunkName][indices[i]].continuation = true;
                }
            });
        });

        // ── 6. Build activityBlocks for the solver ───────────────────────────
        // One block per UNLOCKED placeholder slot per bunk.
        // These are the slots the solver will fill in with specific activities.
        var activityBlocks = buildActivityBlocks(result.bunkTimelines, perBunkDivisionTimes);

        if (activityBlocks.length === 0) {
            onError?.('No solvable slots found — check layer types and windows');
            return;
        }

        console.log('[BunkIntegration] Built', activityBlocks.length, 'activity blocks for solver');

        // ── 7. Build solver config (same as existing pipeline) ───────────────
        var rotationHistory = window.loadRotationHistory?.() || {};
        var config = {
            activityProperties: window.activityProperties || {},
            rotationHistory: rotationHistory,
            divisions: divisions,
            dateStr: dateStr,
            _bunkMode: true
        };

        // ── 8. Run the solver ─────────────────────────────────────────────────
        window.Solver?.solveSchedule(activityBlocks, config);

        // ── 9. Update rotation history ────────────────────────────────────────
        window.RotationEngine?.clearHistoryCache?.();

        // ── 10. Persist ───────────────────────────────────────────────────────
        window.saveCurrentDailyData?.('scheduleAssignments', window.scheduleAssignments);
        window.saveCurrentDailyData?.('_autoGenerated', true);
        window.saveCurrentDailyData?.('_generationMode', 'bunk');
        window.saveCurrentDailyData?.('divisionTimes', perBunkDivisionTimes);
        window.ScheduleDB?.saveSchedule?.(dateStr, {
            scheduleAssignments: window.scheduleAssignments,
            divisionTimes: perBunkDivisionTimes,
            _autoGenerated: true,
            _generationMode: 'bunk',
            savedAt: new Date().toISOString()
        });

        // ── 11. Fire completion event and update UI ───────────────────────────
        window.dispatchEvent(new CustomEvent('campistry-generation-complete', {
            detail: { dateKey: dateStr, mode: 'bunk', bunkCount: Object.keys(result.bunkTimelines).length }
        }));

        window.updateTable?.();

        var msg = '✅ Schedule Generated! (' + Object.keys(result.bunkTimelines).length + ' bunks';
        if (result.warnings?.length > 0) msg += ', ' + result.warnings.length + ' warnings';
        msg += ')';

        console.log('[BunkIntegration] Generation complete:', msg);
        onComplete?.(msg, result);

    } catch (err) {
        window._preGenClearActive = false;
        window._generationInProgress = false;
        console.error('[BunkIntegration] Generation failed:', err);
        onError?.('Generation error: ' + err.message);
    }
}

// =============================================================================
// BUILD PER-BUNK DIVISION TIMES
// =============================================================================
// Converts bunkTimelines into the _isPerBunk divisionTimes structure.
// Each bunk gets its own slot array — slot indices are independent per bunk.

function buildPerBunkDivisionTimes(bunkTimelines, divisions) {
    var divisionTimes = {};

    // Group timelines by division
    var byDiv = {};
    Object.values(bunkTimelines).forEach(function(tl) {
        if (!byDiv[tl.divisionName]) byDiv[tl.divisionName] = [];
        byDiv[tl.divisionName].push(tl);
    });

    Object.keys(byDiv).forEach(function(divName) {
        var perBunkSlots = {};

        byDiv[divName].forEach(function(tl) {
            // Each slot in the bunk timeline becomes one entry in the slot array.
            // We include ALL slots (locked + unlocked) so indices are complete.
            perBunkSlots[tl.bunkName] = tl.slots.map(function(slot) {
                return {
                    startMin: slot.startMin,
                    endMin: slot.endMin,
                    label: fmtTime(slot.startMin) + ' - ' + fmtTime(slot.endMin),
                    _locked: slot.locked || false,
                    _activityType: slot.activityType,
                    _source: slot.source
                };
            });
        });

        divisionTimes[divName] = {
            _isPerBunk: true,
            _perBunkSlots: perBunkSlots,
            // Provide a fallback flat array for any code that reads divisionTimes[div] directly
            // Use the union of all unique time boundaries across all bunks
            length: Math.max.apply(null, Object.values(perBunkSlots).map(function(s) { return s.length; }))
        };

        console.log('[BunkIntegration] divisionTimes[' + divName + ']: _isPerBunk, ' +
            Object.keys(perBunkSlots).length + ' bunks');
    });

    return divisionTimes;
}

// =============================================================================
// FIND SLOT INDICES
// =============================================================================
// Given a bunk's slot array and a time range, returns which slot indices
// the range covers. Used when writing locked slots to scheduleAssignments.

function findSlotIndices(bunkSlots, startMin, endMin) {
    var indices = [];
    for (var i = 0; i < bunkSlots.length; i++) {
        var s = bunkSlots[i];
        // Slot overlaps with the time range
        if (s.startMin < endMin && s.endMin > startMin) {
            indices.push(i);
        }
    }
    return indices;
}

// =============================================================================
// BUILD ACTIVITY BLOCKS FOR SOLVER
// =============================================================================
// Converts unlocked bunk timeline slots into the exact format
// Solver.solveSchedule() expects.

function buildActivityBlocks(bunkTimelines, perBunkDivisionTimes) {
    var activityBlocks = [];

    Object.values(bunkTimelines).forEach(function(tl) {
        var bunkSlots = perBunkDivisionTimes[tl.divisionName]?._perBunkSlots?.[tl.bunkName] || [];

        tl.slots.forEach(function(slot) {
            // Skip locked slots — already written to scheduleAssignments
            if (slot.locked) return;
            // Skip types the solver can't fill
            var type = (slot.activityType || '').toLowerCase();
            if (type === 'free' || type === 'change') return;

            // Find slot indices for this time range
            var slotIndices = findSlotIndices(bunkSlots, slot.startMin, slot.endMin);
            if (slotIndices.length === 0) {
                console.warn('[BunkIntegration] No slot indices for', tl.bunkName,
                    fmtTime(slot.startMin), '-', fmtTime(slot.endMin));
                return;
            }

            activityBlocks.push({
                bunk: tl.bunkName,
                divName: tl.divisionName,
                slots: slotIndices,
                startTime: slot.startMin,   // minutes — solver uses this for field conflict checks
                endTime: slot.endMin,
                event: slot.activityType,   // 'sports', 'special', 'activity' — solver picks specific
                type: 'slot',
                _autoGenerated: true,
                _bunkMode: true
            });
        });
    });

    return activityBlocks;
}

// Simple time formatter (same as BunkScheduleEngine)
function fmtTime(min) {
    if (min == null) return '?';
    var h = Math.floor(min / 60), m = min % 60;
    var ap = h >= 12 ? 'pm' : 'am';
    h = h % 12 || 12;
    return h + ':' + (m < 10 ? '0' : '') + m + ap;
}
    // -------------------------------------------------------------------------
    // Build a synthetic scheduleAssignments structure from bunkTimelines
    // so existing code that reads scheduleAssignments doesn't crash.
    // Each bunk gets an array where each entry is indexed by a 5-minute slot
    // starting from the division's day start.
    // -------------------------------------------------------------------------
    function buildSyntheticAssignments(bunkTimelines) {
        var assignments = {};

        Object.values(bunkTimelines).forEach(function (tl) {
            var bunkName = tl.bunkName;
            assignments[bunkName] = [];

            tl.slots.forEach(function (slot) {
                // Convert to 5-minute slot indices
                var slotIdx = Math.floor((slot.startMin - tl.dayStart) / 5);
                var slotCount = Math.ceil((slot.endMin - slot.startMin) / 5);

                for (var i = 0; i < slotCount; i++) {
                    assignments[bunkName][slotIdx + i] = {
                        _activity: slot.activity || slot.activityType || 'Free',
                        field: slot.field,
                        _autoGenerated: true,
                        _bunkMode: true,
                        _startMin: slot.startMin,
                        _endMin: slot.endMin,
                        continuation: i > 0,
                        _locked: slot.locked || false,
                        _source: slot.source
                    };
                }
            });
        });

        return assignments;
    }

    // -------------------------------------------------------------------------
    // SETTINGS: get/set the generation mode for this camp
    // -------------------------------------------------------------------------
    function setGenerationMode(mode) {
        // mode: 'grade' | 'bunk'
        var g = window.loadGlobalSettings?.() || {};
        g.app1 = g.app1 || {};
        g.app1.generationMode = mode;
        window.saveGlobalSettings?.('app1', g.app1);
        console.log('[BunkIntegration] Generation mode set to:', mode);
    }

    // -------------------------------------------------------------------------
    // PUBLIC API
    // -------------------------------------------------------------------------
    window.BunkEngineIntegration = {
        isBunkMode: isBunkMode,
        getGenerationMode: getGenerationMode,
        setGenerationMode: setGenerationMode,
        runBunkGeneration: runBunkGeneration,
        buildSyntheticAssignments: buildSyntheticAssignments,

        // Called from daily_adjustments.js runOptimizer() — replaces
        // the AutoBuildEngine call when bunk mode is active
        handleAutoGenerate: async function (dateStr, daAutoLayers, showAlert) {
            if (!isBunkMode()) return false; // signal: use existing pipeline

            await runBunkGeneration(
                dateStr,
                daAutoLayers,
                function (msg) { showAlert?.(msg); },
                function (err) { showAlert?.('❌ ' + err); }
            );

            return true; // signal: handled by bunk engine, skip existing pipeline
        }
    };

    console.log('[BunkEngineIntegration] loaded. Mode:', getGenerationMode());

})();
