// =================================================================
// DayPlanEngine.js  (v1.1)
// =================================================================
// The orchestrator for the bunk-level skeleton engine. Replaces the
// internals of AutoBuildEngine.build() while keeping the identical
// public output contract so every existing call site continues to
// work without modification.
//
// CALL ORDER:
//   1. WeeklyAllocationSolver  — run once per week (lazy, cached)
//   2. ScarceActivityAllocator — per-day, commits scarce blocks first
//   3. BunkTimelineSolver      — per-bunk, posts-and-gaps placement
//
// OUTPUT CONTRACT (identical to AutoBuildEngine.build()):
//   { skeleton, bunkOverrides, bunkTimelines, warnings,
//     _autoGenerated, _buildDate, _buildVersion, _perBunkMode }
//
//   skeleton      — per-bunk blocks with _bunk field set.
//                   DivisionTimesSystem.buildFromSkeleton() detects
//                   _bunk fields and automatically enters per-bunk
//                   mode — no changes to any call site needed.
//
//   bunkTimelines — { bunkName: slot[] } for the Gantt renderer
//                   (same shape as _autoBuildTimelines today)
//
//   _perBunkMode  — true. Call sites can check this to skip the
//                   legacy grade-level Gantt path.
//
// CALL SITE COMPATIBILITY:
//   auto_schedule_planner.js  → genBtn → AutoBuildEngine.build()
//   daily_adjustments.js      → runOptimizer → AutoBuildEngine.build()
//   Both receive the same result shape and need no changes.
//
// HOW DayPlanEngine becomes AutoBuildEngine's implementation:
//   At the bottom of this file, window.AutoBuildEngine.build is
//   patched to call DayPlanEngine.run() when the new engine is
//   active (builderMode includes bunk-level layers). The old engine
//   is preserved as AutoBuildEngine._legacyBuild for fallback.
//
// ARCHITECTURE CONTRACT:
//   - Does NOT modify total_solver_engine.js
//   - Does NOT modify rotation_engine.js
//   - Does NOT modify scheduler_core_main.js
//   - Does NOT modify division_times_system.js
//   - Partial failures are handled gracefully with warnings
//
// v1.1 CHANGES — REFINEMENT LOOP:
//   After campistry-generation-complete fires, refine() runs a
//   two-tier convergence loop:
//
//   Tier 1 — PATCH (maxPatchRounds, default 3):
//     Detects Free slots whose _suggestedActivity was blocked by
//     capacity, and quantity/operator violations from layer rules.
//     Rebuilds only the failed bunks with those activities excluded,
//     snapshots all good bunk assignments, re-runs the solver, then
//     restores the good-bunk snapshot so the solver's full wipe
//     doesn't destroy work that already succeeded.
//     Updates the display after each round so the user sees progress.
//
//   Tier 2 — FULL WIPE (maxWipes, default 2):
//     If patch mode can't converge, wipes all daily state and reruns
//     DayPlanEngine.run() from scratch. Repeats up to maxWipes times.
// =================================================================

(function () {
    'use strict';

    var VERSION = '1.1';

    // =================================================================
    // LOGGING
    // =================================================================
    var _logs = [];
    function log(msg)  { _logs.push(msg);        console.log('[DayPlanEngine] '  + msg); }
    function warn(msg) { _logs.push('⚠ ' + msg); console.warn('[DayPlanEngine] ' + msg); }
    function getLogs()   { return _logs.slice(); }
    function clearLogs() { _logs = []; }

    // =================================================================
    // TIME UTILITIES
    // =================================================================

    function parseTimeToMinutes(str) {
        if (!str || typeof str !== 'string') return null;
        var s = str.trim().toLowerCase();
        var mer = null;
        if (s.endsWith('am') || s.endsWith('pm')) {
            mer = s.endsWith('am') ? 'am' : 'pm';
            s = s.replace(/am|pm/g, '').trim();
        }
        var m = s.match(/^(\d{1,2})\s*:\s*(\d{2})$/);
        if (!m) return null;
        var hh = parseInt(m[1], 10), mm = parseInt(m[2], 10);
        if (isNaN(hh) || isNaN(mm) || mm < 0 || mm > 59) return null;
        if (mer) {
            if (hh === 12) hh = mer === 'am' ? 0 : 12;
            else if (mer === 'pm') hh += 12;
        } else {
            if (hh < 0 || hh > 23) return null;
        }
        return hh * 60 + mm;
    }

    function minutesToTimeStr(min) {
        var h = Math.floor(min / 60);
        var m = min % 60;
        var ap = h >= 12 ? 'PM' : 'AM';
        var h12 = h % 12 || 12;
        return h12 + ':' + String(m).padStart(2, '0') + ' ' + ap;
    }

    // =================================================================
    // CAMP STRUCTURE HELPERS
    // =================================================================

    function getCampStructure() {
        var g = window.loadGlobalSettings ? window.loadGlobalSettings() : {};
        return g.campStructure || {};
    }

    /**
     * Reads from campStructure (grades-as-scheduling-units model).
     * Returns { divisionName: [bunkName, ...] }
     */
    function getDivBunkMap() {
        var structure = getCampStructure();
        var map = {};
        Object.keys(structure).forEach(function (divName) {
            var grades = structure[divName].grades || {};
            var divBunks = [];
            Object.keys(grades).forEach(function (gradeName) {
                var bunks = grades[gradeName].bunks || [];
                divBunks = divBunks.concat(bunks);
            });
            if (divBunks.length > 0) map[divName] = divBunks;
        });
        return map;
    }

    function getAllBunks() {
        var map = getDivBunkMap();
        var all = [];
        Object.keys(map).forEach(function (d) { all = all.concat(map[d]); });
        return all;
    }

    /**
     * Find the grade name for a given bunk. Used by detectFailedSuggestions.
     */
    function getGradeForBunk(bunkName) {
        var structure = getCampStructure();
        for (var divName in structure) {
            var grades = structure[divName].grades || {};
            for (var gradeName in grades) {
                if ((grades[gradeName].bunks || []).indexOf(bunkName) !== -1) return gradeName;
            }
        }
        return null;
    }

    // =================================================================
    // ENGINE READINESS
    // =================================================================

    function checkEngines() {
        var required = ['WeeklyAllocationSolver', 'ScarceActivityAllocator', 'BunkTimelineSolver'];
        return required.filter(function (name) { return !window[name]; });
    }

    // =================================================================
    // SLOT → SKELETON BLOCK CONVERTER
    // =================================================================

    function slotToSkeletonBlock(slot, divName) {
        return {
            id:                 slot.id || ('dpe_' + Math.random().toString(36).slice(2, 8)),
            type:               slot.type || 'slot',
            event:              slot.event || slot._activityType || 'GA',
            division:           divName,
            startTime:          minutesToTimeStr(slot.startMin),
            endTime:            minutesToTimeStr(slot.endMin),
            _bunk:              slot._bunk,
            _suggestedActivity: slot._suggestedActivity || null,
            _autoGenerated:     true,
            _durationStrict:    slot._durationStrict || false,
            _anchorClass:       slot._anchorClass || null,
            _perBunkMode:       true
        };
    }

    // =================================================================
    // CORE: run()
    // =================================================================

    /**
     * Run the full bunk-level skeleton engine for a single date.
     *
     * @param {object} params
     *   params.dateStr    {string}   'YYYY-MM-DD'  (required)
     *   params.layers     {object[]} Grade layer rules from the UI
     *   params.forceWeek  {boolean}  Force re-solve the weekly matrix
     *
     * @returns {object} result matching AutoBuildEngine.build() contract
     */
    function run(params) {
        clearLogs();

        var dateStr   = params.dateStr  || new Date().toISOString().split('T')[0];
        var layers    = params.layers   || [];
        var forceWeek = !!params.forceWeek;
        var warnings  = [];

        log('======================================================');
        log('DayPlanEngine v' + VERSION);
        log('Date: ' + dateStr + (forceWeek ? ' [force re-week]' : ''));
        log('======================================================');

        // ── Readiness ──────────────────────────────────────────────
        var missing = checkEngines();
        if (missing.length > 0) {
            var msg = 'Required engines not loaded: ' + missing.join(', ');
            warn(msg);
            return _legacyFallback(params, [msg]);
        }

        // ── Seed layer rules from UI layers if not yet persisted ───
        _seedLayerRulesFromUILayers(layers);

        // ── STEP 1: Weekly Allocation Solver ───────────────────────
        log('\n── STEP 1: WeeklyAllocationSolver ──');
        var weekResult;
        try {
            weekResult = window.WeeklyAllocationSolver.solve(dateStr, { force: forceWeek });
            if (weekResult.skipped) {
                log('Using cached weekly matrix for ' + weekResult.weekKey);
            } else {
                log('Solved weekly matrix: ' + weekResult.weekKey);
                if (weekResult.warnings.length > 0) {
                    weekResult.warnings.forEach(function (w) { warnings.push('Weekly: ' + w); });
                }
            }
        } catch (e) {
            var msg1 = 'WeeklyAllocationSolver failed: ' + e.message;
            warn(msg1);
            warnings.push(msg1);
            weekResult = { weekKey: null, matrix: {}, warnings: [] };
        }

        // ── STEP 2: Scarce Activity Allocator ──────────────────────
        log('\n── STEP 2: ScarceActivityAllocator ──');
        var allBunks = getAllBunks();
        var allocResult;
        try {
            allocResult = window.ScarceActivityAllocator.allocate({
                dateStr:  dateStr,
                allBunks: allBunks,
                warnings: warnings
            });
            log('Scarce allocator: ' + allocResult.allocations.length + ' activities, ' +
                Object.keys(allocResult.scarceBlocksMap).filter(function (b) {
                    return allocResult.scarceBlocksMap[b].length > 0;
                }).length + ' bunks with committed blocks');
        } catch (e) {
            var msg2 = 'ScarceActivityAllocator failed: ' + e.message;
            warn(msg2);
            warnings.push(msg2);
            allocResult = { scarceBlocksMap: {}, deferredBunks: {}, allocations: [], warnings: [] };
        }

        var scarceBlocksMap = allocResult.scarceBlocksMap;

        // ★ v1.1: Store for refinement loop use
        window._lastScarceBlocksMap  = scarceBlocksMap;
        window._lastLayerConstraints = (function () {
            try {
                var _g = window.loadGlobalSettings ? window.loadGlobalSettings() : {};
                return (_g.app1 || {}).gradeLayerRules || {};
            } catch (e) { return {}; }
        })();

        // ── STEP 3: BunkTimelineSolver ─────────────────────────────
        log('\n── STEP 3: BunkTimelineSolver ──');
        var divBunkMap       = getDivBunkMap();
        var allSkeletonBlocks = [];
        var bunkTimelines    = {};

        Object.keys(divBunkMap).forEach(function (divName) {
            var divBunks = divBunkMap[divName];

            var divResult;
            try {
                divResult = window.BunkTimelineSolver.buildForDivision({
                    divName:         divName,
                    bunks:           divBunks,
                    dateStr:         dateStr,
                    scarceBlocksMap: scarceBlocksMap,
                    warnings:        warnings
                });
            } catch (e) {
                var msg3 = divName + ': BunkTimelineSolver failed — ' + e.message;
                warn(msg3);
                warnings.push(msg3);
                return;
            }

            var perBunkSlots = divResult.perBunkSlots;

            window.BunkTimelineSolver.applyToDivisionTimes(divName, perBunkSlots);

            Object.keys(perBunkSlots).forEach(function (bunk) {
                var slots = perBunkSlots[bunk] || [];

                bunkTimelines[bunk] = slots.map(function (s) {
                    return {
                        startMin:           s.startMin,
                        endMin:             s.endMin,
                        event:              s.event,
                        type:               s.type,
                        _suggestedActivity: s._suggestedActivity || null,
                        _anchorClass:       s._anchorClass || null,
                        _autoGenerated:     true
                    };
                });

                slots.forEach(function (slot) {
                    allSkeletonBlocks.push(slotToSkeletonBlock(slot, divName));
                });
            });

            log('  ' + divName + ': ' + divBunks.length + ' bunks processed, ' +
                allSkeletonBlocks.filter(function (b) { return b.division === divName; }).length +
                ' skeleton blocks');
        });

        // ── Persist bunk timelines ─────────────────────────────────
        window._autoGeneratedSchedule = true;
        window._autoBuildTimelines    = bunkTimelines;
        window._perBunkMode           = true;

        if (window.saveCurrentDailyData) {
            try {
                window.saveCurrentDailyData('_autoGenerated',      true);
                window.saveCurrentDailyData('_autoBuildTimelines', bunkTimelines);
                window.saveCurrentDailyData('_perBunkMode',        true);
                if (window.DivisionTimesSystem && window.DivisionTimesSystem.serialize) {
                    window.saveCurrentDailyData(
                        'divisionTimes',
                        window.DivisionTimesSystem.serialize(window.divisionTimes)
                    );
                }
            } catch (e) {
                warn('Failed to persist to saveCurrentDailyData: ' + e.message);
            }
        }

        log('\n======================================================');
        log('DayPlanEngine COMPLETE');
        log('Skeleton blocks:  ' + allSkeletonBlocks.length);
        log('Bunk timelines:   ' + Object.keys(bunkTimelines).length + ' bunks');
        log('Scarce committed: ' + allocResult.allocations.length + ' activities');
        log('Warnings:         ' + warnings.length);
        log('======================================================');

        return {
            skeleton:       allSkeletonBlocks,
            bunkOverrides:  [],
            bunkTimelines:  bunkTimelines,
            warnings:       warnings,
            allocations:    allocResult.allocations,
            _autoGenerated: true,
            _buildDate:     dateStr,
            _buildVersion:  'DayPlanEngine-' + VERSION,
            _perBunkMode:   true
        };
    }

    // =================================================================
    // LAYER RULE SEEDING
    // =================================================================

    function _seedLayerRulesFromUILayers(layers) {
        if (!layers || layers.length === 0) return;

        var g = window.loadGlobalSettings ? window.loadGlobalSettings() : {};
        if (!g.app1) g.app1 = {};
        var existing = g.app1.gradeLayerRules || {};

        var byGrade = {};
        layers.forEach(function (l) {
            var grade = l.grade || l.division || null;
            if (!grade) return;
            if (!byGrade[grade]) byGrade[grade] = [];
            byGrade[grade].push(l);
        });

        var dirty = false;
        Object.keys(byGrade).forEach(function (grade) {
            if (existing[grade] && existing[grade].length > 0) return;
            existing[grade] = byGrade[grade].map(function (l) {
                return {
                    id:           l.id || ('seed_' + Math.random().toString(36).slice(2, 7)),
                    type:         l.type || 'activity',
                    duration:     l.periodMin || l.durationMin || l.duration || 30,
                    windowStart:  l.startMin || 0,
                    windowEnd:    l.endMin   || 0,
                    timesPerDay:  l.quantity || l.timesPerDay || 1,
                    timesPerWeek: l.timesPerWeek || null,
                    weeklyOp:     l.weeklyOp || l.op || '>=',
                    operator:     l.operator || l.op || '>='
                };
            });
            dirty = true;
            log('Seeded layer rules for grade "' + grade + '" from UI layers');
        });

        if (dirty) {
            g.app1.gradeLayerRules = existing;
            if (window.saveGlobalSettings) window.saveGlobalSettings('app1', g.app1);
        }
    }

    // =================================================================
    // LEGACY FALLBACK
    // =================================================================

    function _legacyFallback(params, prefixWarnings) {
        warn('Falling back to legacy AutoBuildEngine._legacyBuild');
        if (window.AutoBuildEngine && window.AutoBuildEngine._legacyBuild) {
            var result = window.AutoBuildEngine._legacyBuild(params);
            if (prefixWarnings && prefixWarnings.length > 0) {
                result.warnings = prefixWarnings.concat(result.warnings || []);
            }
            return result;
        }
        return {
            skeleton: [], bunkOverrides: [], bunkTimelines: {},
            warnings: (prefixWarnings || []).concat(['DayPlanEngine: no engine available']),
            _autoGenerated: false, _buildDate: params.dateStr, _buildVersion: 'none'
        };
    }

    // =================================================================
    // WEEK PLAN UTILITIES
    // =================================================================

    function planWeek(dateStr, layers, force) {
        if (!window.WeeklyAllocationSolver) {
            warn('WeeklyAllocationSolver not loaded');
            return { weekKey: null, matrix: {}, warnings: ['WeeklyAllocationSolver not loaded'], skipped: false };
        }
        _seedLayerRulesFromUILayers(layers || []);
        return window.WeeklyAllocationSolver.solve(dateStr, { force: !!force });
    }

    function getWeekPlanSummary(dateStr) {
        if (!window.WeeklyAllocationSolver) return { weekKey: null, weekDays: [], rows: [], warnings: [] };
        return window.WeeklyAllocationSolver.getMatrixSummary(dateStr);
    }

    function lockWeekCell(dateStr, bunkName, types) {
        if (!window.WeeklyAllocationSolver) return;
        window.WeeklyAllocationSolver.lockCell(dateStr, bunkName, types);
    }

    function unlockWeekCell(dateStr, bunkName) {
        if (!window.WeeklyAllocationSolver) return;
        window.WeeklyAllocationSolver.unlockCell(dateStr, bunkName);
    }

    // =================================================================
    // REFINEMENT LOOP  (v1.1)
    // =================================================================

    // ------------------------------------------------------------------
    // Helpers
    // ------------------------------------------------------------------

    /** Parse a block's startTime field (string or number) to minutes. */
    function parseBlockStartMin(startTime) {
        if (typeof startTime === 'number') return startTime;
        if (!startTime) return null;
        var s = String(startTime);
        var m = s.match(/(\d+):(\d+)\s*(AM|PM)/i);
        if (!m) return null;
        var h = parseInt(m[1]), mn = parseInt(m[2]);
        if (/pm/i.test(m[3]) && h !== 12) h += 12;
        if (/am/i.test(m[3]) && h === 12) h = 0;
        return h * 60 + mn;
    }

    /** Normalise operator unicode to ASCII. */
    function normOp(op) {
        if (!op) return '>=';
        return String(op).replace('\u2265', '>=').replace('\u2264', '<=');
    }

    /**
     * Trigger a visual table refresh so the user sees progress between
     * solver rounds without waiting for the final state.
     */
    function updateDisplay() {
        try {
            if (typeof window.updateTable === 'function') window.updateTable();
        } catch (e) { /* non-critical */ }
    }

    // ------------------------------------------------------------------
    // detectFailedSuggestions
    //
    // Cross-references window.skeleton + window.scheduleAssignments +
    // window._lastLayerConstraints to find three categories of violation:
    //
    //   'activity:<name>'            — specific suggestion went Free
    //   'qty:<type>:<op><n>(got <k>)'— operator/quantity contract broken
    //   'weekly:<type>:should-not-be-today' — layer was off today but placed
    //
    // Returns { bunkName: Set<reason> }
    // ------------------------------------------------------------------
    function detectFailedSuggestions() {
        var skeleton    = window.skeleton               || [];
        var assignments = window.scheduleAssignments    || {};
        var constraints = window._lastLayerConstraints  || {};

        var failed = {};

        function markFailed(bunk, reason) {
            if (!failed[bunk]) failed[bunk] = new Set();
            failed[bunk].add(reason);
        }

        // ── 1. Specific suggestion failures (suggestion slot went Free) ──
        skeleton.forEach(function (block) {
            var bunk      = block._bunk;
            var suggested = block._suggestedActivity;
            if (!bunk || !suggested) return;

            var divName       = block.division;
            var perBunkSlots  = window.divisionTimes?.[divName]?._perBunkSlots?.[bunk];
            if (!perBunkSlots) return;

            var startMin = parseBlockStartMin(block.startTime);
            if (startMin === null) return;

            var slotIdx = perBunkSlots.findIndex(function (s) { return s.startMin === startMin; });
            if (slotIdx === -1) return;

            var placed     = assignments[bunk]?.[slotIdx];
            var placedName = (placed?._activity || placed?.field || '').toLowerCase().trim();
            var isFree     = !placedName || placedName === 'free' || placedName === 'free (timeout)';

            if (isFree) markFailed(bunk, 'activity:' + suggested);
        });

        // ── 2. Daily quantity / operator violations ──────────────────────
        // Count filled slots of each _activityType per bunk; compare against rule.
        Object.keys(assignments).forEach(function (bunk) {
            var gradeName  = getGradeForBunk(bunk);
            if (!gradeName) return;
            var layerRules = constraints[gradeName] || [];
            if (layerRules.length === 0) return;

            var divName = window.SchedulerCoreUtils
                ? window.SchedulerCoreUtils.getDivisionForBunk(bunk)
                : null;
            if (!divName) return;

            var perBunkSlots = window.divisionTimes?.[divName]?._perBunkSlots?.[bunk] || [];
            var bunkAssigns  = assignments[bunk] || [];

            // Count filled slots by _activityType
            var typeCounts = {};
            perBunkSlots.forEach(function (slot, idx) {
                var assign = bunkAssigns[idx];
                if (!assign) return;
                var actName = (assign._activity || assign.field || '').toLowerCase().trim();
                if (!actName || actName === 'free' || actName === 'free (timeout)') return;
                var slotType = slot._activityType || '';
                if (!slotType) return;
                typeCounts[slotType] = (typeCounts[slotType] || 0) + 1;
            });

            layerRules.forEach(function (rule) {
                var type    = rule.type;
                var qty     = rule.timesPerDay || rule.quantity || 1;
                var op      = normOp(rule.operator || rule.weeklyOp);
                var actual  = typeCounts[type] || 0;

                var violated = false;
                if (op === '=')  violated = actual !== qty;
                if (op === '>=') violated = actual < qty;
                if (op === '<=') violated = actual > qty;

                if (violated) {
                    markFailed(bunk, 'qty:' + type + ':' + op + qty + ' (got ' + actual + ')');
                }
            });
        });

        // ── 3. Weekly constraint violations ─────────────────────────────
        // If a layer was off today (timesPerWeek) but slots of that type
        // were placed anyway, flag for removal.
        if (window.WeeklyAllocationSolver) {
            var dateStr = window.currentScheduleDate || new Date().toISOString().split('T')[0];

            Object.keys(assignments).forEach(function (bunk) {
                var matrixRow  = window.WeeklyAllocationSolver.getBunkDayRow(bunk, dateStr);
                var gradeName  = getGradeForBunk(bunk);
                if (!gradeName) return;
                var layerRules = constraints[gradeName] || [];

                layerRules.forEach(function (rule) {
                    if (rule.timesPerWeek == null) return;
                    var type = rule.type;
                    var isScheduledToday = matrixRow.indexOf(type) !== -1;
                    if (!isScheduledToday) {
                        var divName = window.SchedulerCoreUtils
                            ? window.SchedulerCoreUtils.getDivisionForBunk(bunk)
                            : null;
                        if (!divName) return;
                        var perBunkSlots = window.divisionTimes?.[divName]?._perBunkSlots?.[bunk] || [];
                        var hasType = perBunkSlots.some(function (s) {
                            return (s._activityType || '') === type;
                        });
                        if (hasType) markFailed(bunk, 'weekly:' + type + ':should-not-be-today');
                    }
                });
            });
        }

        return failed;
    }

    // ------------------------------------------------------------------
    // snapshotGoodBunks / restoreGoodBunks
    //
    // The solver's STEP 0 does window.scheduleAssignments = {} which
    // destroys the entire object. We cannot pin slots in place before
    // the solver runs. Instead we snapshot good bunk arrays before the
    // solver call and write them back immediately after, overwriting
    // whatever the solver placed for those bunks.
    // ------------------------------------------------------------------

    function snapshotGoodBunks(failedBunks) {
        var snapshot    = {};
        var assignments = window.scheduleAssignments || {};
        var failedSet   = new Set(failedBunks);

        Object.keys(assignments).forEach(function (bunk) {
            if (!failedSet.has(bunk)) {
                // Shallow-copy the slot array (entries are objects we don't mutate here)
                snapshot[bunk] = (assignments[bunk] || []).slice();
            }
        });
        return snapshot;
    }

    function restoreGoodBunks(snapshot) {
        if (!window.scheduleAssignments) window.scheduleAssignments = {};
        Object.keys(snapshot).forEach(function (bunk) {
            window.scheduleAssignments[bunk] = snapshot[bunk];
        });
    }

    // ------------------------------------------------------------------
    // patchFailedBunks
    //
    // Rebuilds timelines for only the failed bunks, excluding their
    // blocked activities, snapshots good bunks, re-runs the solver,
    // then restores good-bunk assignments.
    // ------------------------------------------------------------------

    function patchFailedBunks(failedMap, dateStr) {
        var warnings     = [];
        var failedBunks  = Object.keys(failedMap);
        var anyRebuilt   = false;

        failedBunks.forEach(function (bunk) {
            var blocked = failedMap[bunk]; // Set<activityName or reason string>

            // Extract raw activity names from the reason strings
            var blockedActivities = new Set();
            blocked.forEach(function (reason) {
                if (reason.startsWith('activity:')) {
                    blockedActivities.add(reason.slice('activity:'.length));
                }
            });

            var divName = window.SchedulerCoreUtils
                ? window.SchedulerCoreUtils.getDivisionForBunk(bunk)
                : null;
            if (!divName) return;

            var matrixRow    = window.WeeklyAllocationSolver
                ? window.WeeklyAllocationSolver.getBunkDayRow(bunk, dateStr)
                : [];
            var scarceBlocks = (window._lastScarceBlocksMap || {})[bunk] || [];

            try {
                // BunkTimelineSolver reads layerRules internally via getLayerRulesForBunk
                var slots = window.BunkTimelineSolver.buildForBunk({
                    bunkName:          bunk,
                    dateStr:           dateStr,
                    matrixRow:         matrixRow,
                    scarceBlocks:      scarceBlocks,
                    warnings:          warnings,
                    blockedActivities: blockedActivities
                });

                // Update perBunkSlots for this bunk only
                var partial = {};
                partial[bunk] = slots;
                window.BunkTimelineSolver.applyToDivisionTimes(divName, partial);

                // Patch the live skeleton: remove old blocks for this bunk, insert new ones
                window.skeleton = (window.skeleton || []).filter(function (b) {
                    return b._bunk !== bunk;
                });
                slots.forEach(function (slot) {
                    window.skeleton.push(slotToSkeletonBlock(slot, divName));
                });

                // Null out only this bunk's assignments so the solver re-fills them.
                // All other bunks are handled by snapshotGoodBunks/restoreGoodBunks below.
                if (window.scheduleAssignments && window.scheduleAssignments[bunk]) {
                    window.scheduleAssignments[bunk] = new Array(
                        window.scheduleAssignments[bunk].length
                    ).fill(null);
                }

                anyRebuilt = true;
                log('  [patch] Rebuilt ' + bunk +
                    ' — blocked: [' + Array.from(blockedActivities).join(', ') + ']');

            } catch (e) {
                warn('  [patch] Failed to rebuild ' + bunk + ': ' + e.message);
            }
        });

        return anyRebuilt;
    }

    // ------------------------------------------------------------------
    // fullWipe
    //
    // Clears all daily generated state and re-runs DayPlanEngine.run()
    // from scratch (Stage 1 → Scarce → Timeline → Skeleton).
    // ------------------------------------------------------------------

    function fullWipe(dateStr) {
        log('  [wipe] Clearing all assignments and rebuilding from scratch');

        // Clear live state
        window.scheduleAssignments  = {};
        window.skeleton             = [];
        window.divisionTimes        = {};
        window._autoBuildTimelines  = {};
        window._lastScarceBlocksMap = {};

        // Read layers — handle both flat array and { grade: [layers] } formats
        var layers = (function () {
            try {
                var g = window.loadGlobalSettings ? window.loadGlobalSettings() : {};
                var draft = g.app1 && g.app1.draftAutoLayers;
                if (!draft) return [];
                if (Array.isArray(draft)) return draft;
                return Object.values(draft).reduce(function (acc, arr) {
                    return acc.concat(Array.isArray(arr) ? arr : []);
                }, []);
            } catch (e) { return []; }
        })();

        var result = window.DayPlanEngine.run({
            dateStr:   dateStr,
            layers:    layers,
            forceWeek: false   // keep weekly matrix; only wipe daily timelines
        });

        if (!result.skeleton || result.skeleton.length === 0) {
            warn('  [wipe] DayPlanEngine.run() produced no skeleton');
            return false;
        }

        // Push the fresh skeleton into the live globals
        window.manualSkeleton = result.skeleton;
        window.skeleton       = result.skeleton;

        // Rebuild divisionTimes from the fresh skeleton
        if (window.DivisionTimesSystem && window.DivisionTimesSystem.buildFromSkeleton) {
            var divisions = window.divisions
                || (window.loadGlobalSettings ? window.loadGlobalSettings() : {}).app1?.divisions
                || {};
            window.divisionTimes = window.DivisionTimesSystem.buildFromSkeleton(result.skeleton, divisions);
        }

        return true;
    }

    // ------------------------------------------------------------------
    // refine  — the two-tier convergence loop
    //
    // Tier 1 — PATCH MODE (up to maxPatchRounds per wipe cycle):
    //   Detect violated bunks → rebuild with blocked activities →
    //   snapshot good bunks → re-run solver → restore good bunks →
    //   update display.  Repeat until converged or no progress.
    //
    // Tier 2 — FULL WIPE (up to maxWipes times):
    //   Wipe everything → re-run DayPlanEngine.run() + solver →
    //   update display.  Then try patch rounds again.
    // ------------------------------------------------------------------

    async function refine(dateStr, opts) {
        opts = opts || {};
        var maxPatchRounds = opts.maxPatchRounds || 3;
        var maxWipes       = opts.maxWipes       || 2;

        log('======================================================');
        log('DayPlanEngine REFINE');
        log('  maxPatchRounds=' + maxPatchRounds + '  maxWipes=' + maxWipes);
        log('======================================================');

        // wipe=0 means "initial generation already ran — skip the wipe step"
        for (var wipe = 0; wipe <= maxWipes; wipe++) {

            if (wipe > 0) {
                // ── Full wipe ───────────────────────────────────────
                log('\n── Full wipe ' + wipe + '/' + maxWipes + ' ──');
                var wiped = await Promise.resolve(fullWipe(dateStr));
                if (!wiped) {
                    warn('Full wipe failed — stopping refinement');
                    break;
                }

                // Solver run after wipe (no snapshot needed — fresh solve)
                window._refinementInProgress = true;
                try {
                    await window.runSkeletonOptimizer(window.skeleton);
                } finally {
                    window._refinementInProgress = false;
                }
                updateDisplay();
            }

            // ── Patch rounds ────────────────────────────────────────
            var converged = false;

            for (var round = 1; round <= maxPatchRounds; round++) {
                var failed    = detectFailedSuggestions();
                var failCount = Object.keys(failed).length;

                log('\n[wipe ' + wipe + ' / patch ' + round + '] ' +
                    failCount + ' bunk(s) with violations');

                if (failCount === 0) {
                    log('Converged ✓');
                    converged = true;
                    break;
                }

                // Patch the failed bunks (nulls their assignments, rebuilds timelines)
                var anyRebuilt = patchFailedBunks(failed, dateStr);
                if (!anyRebuilt) {
                    log('Nothing could be rebuilt — escalating');
                    break;
                }

                // Snapshot good bunks BEFORE the solver runs (STEP 0 wipes everything)
                var failedBunkNames = Object.keys(failed);
                var goodSnapshot    = snapshotGoodBunks(failedBunkNames);

                // Re-run solver
                window._refinementInProgress = true;
                try {
                    await window.runSkeletonOptimizer(window.skeleton);
                } finally {
                    window._refinementInProgress = false;
                }

                // Immediately restore good bunk assignments the solver wiped
                restoreGoodBunks(goodSnapshot);

                // Show progress to the user
                updateDisplay();

                // Measure progress
                var stillFailed = detectFailedSuggestions();
                var resolved    = failCount - Object.keys(stillFailed).length;
                log('  Patch round ' + round + ': resolved ' + resolved + '/' + failCount);

                if (resolved === 0) {
                    log('  No progress this round — escalating to wipe');
                    break;
                }
            }

            if (converged) break;

            if (wipe === maxWipes) {
                log('\nMax wipes reached — accepting best result');
            }
        }

        // Final display refresh
        updateDisplay();

        log('\n======================================================');
        log('DayPlanEngine REFINE complete');
        log('======================================================');
    }

    // ------------------------------------------------------------------
    // installRefinementHook
    //
    // Listens for campistry-generation-complete (fired by integration_hooks.js
    // and schedule_orchestrator.js after every solver run).
    // Guards prevent recursive firing during refinement.
    // ------------------------------------------------------------------

    function installRefinementHook() {
        window.addEventListener('campistry-generation-complete', function () {
            if (!window._perBunkMode)         return;  // legacy engine, skip
            if (window._refinementInProgress) return;  // already mid-refine

            var dateStr = window.currentScheduleDate ||
                          new Date().toISOString().split('T')[0];

            log('campistry-generation-complete → refine()');
            refine(dateStr, { maxPatchRounds: 3, maxWipes: 2 });
        });

        log('Refinement hook installed on campistry-generation-complete');
    }

    // =================================================================
    // PATCH AutoBuildEngine.build()
    // =================================================================

    function patchAutoBuildEngine() {
        if (!window.AutoBuildEngine) {
            setTimeout(patchAutoBuildEngine, 200);
            return;
        }

        if (!window.AutoBuildEngine._legacyBuild) {
            window.AutoBuildEngine._legacyBuild = window.AutoBuildEngine.build;
            log('Preserved AutoBuildEngine._legacyBuild');
        }

        window.AutoBuildEngine.build = function (params) {
            params = params || {};
            var dateStr = params.dateStr || new Date().toISOString().split('T')[0];
            var layers  = params.layers  || [];

            var useNew = _shouldUseNewEngine(layers);

            if (useNew) {
                log('AutoBuildEngine.build() → DayPlanEngine.run()');
                return window.DayPlanEngine.run({
                    dateStr:   dateStr,
                    layers:    layers,
                    forceWeek: params.forceWeek || false
                });
            } else {
                log('AutoBuildEngine.build() → legacy engine (no bunk-level config)');
                return window.AutoBuildEngine._legacyBuild(params);
            }
        };

        log('AutoBuildEngine.build() patched → DayPlanEngine');
    }

    function _shouldUseNewEngine(layers) {
        if (window._forceBunkEngine === true)  return true;
        if (window._forceBunkEngine === false) return false;

        try {
            var g = window.loadGlobalSettings ? window.loadGlobalSettings() : {};
            var rules = (g.app1 || {}).gradeLayerRules || {};
            if (Object.keys(rules).length > 0) return true;
        } catch (e) { /* continue */ }

        if (layers && layers.some(function (l) { return l.timesPerWeek != null; })) return true;

        return false;
    }

    // =================================================================
    // PUBLIC API
    // =================================================================

    window.DayPlanEngine = {
        VERSION: VERSION,

        // Core
        run: run,

        // Week planning (for UI)
        planWeek:           planWeek,
        getWeekPlanSummary: getWeekPlanSummary,
        lockWeekCell:       lockWeekCell,
        unlockWeekCell:     unlockWeekCell,

        // Refinement (exposed for testing / manual trigger)
        refine:                   refine,
        detectFailedSuggestions:  detectFailedSuggestions,
        snapshotGoodBunks:        snapshotGoodBunks,
        restoreGoodBunks:         restoreGoodBunks,
        patchFailedBunks:         patchFailedBunks,
        fullWipe:                 fullWipe,
        installRefinementHook:    installRefinementHook,

        // Internals (exposed for testing)
        _shouldUseNewEngine:          _shouldUseNewEngine,
        _seedLayerRulesFromUILayers:  _seedLayerRulesFromUILayers,
        _legacyFallback:              _legacyFallback,

        // Debug
        getLogs:   getLogs,
        clearLogs: clearLogs
    };

    // Install hooks (order matters: refinement hook before engine patch
    // so the hook is ready if the patch fires a generation event)
    installRefinementHook();
    patchAutoBuildEngine();

    log('DayPlanEngine v' + VERSION + ' loaded');

})();
