// =============================================================================
// playoff_mode.js — shared playoff data model for Leagues + Specialty Leagues
// =============================================================================
// v2 — USER-DEFINED ROUNDS.
// The old auto-generated bracket engine (seed list, fixed/reseed styles,
// play-in / eliminate / bye adjustments, advanceFixed / advanceReseed and the
// dead inline render UI) is GONE. The user now builds every round by hand in
// the Playoff Hub (playoff_hub.js): how many matchups a round has, which team
// plays which, which sport they play, and (optionally) which field. This
// module owns only the data model + pure helpers that the schedulers consume.
//
//   league.playoff = {
//     enabled: bool,
//     rounds: [
//       { number: 1,
//         matchups: [ { id, teamA, teamB, sport, field, winner } ],
//         byes: [teamName, ...],    // sit out this round, still in the playoffs
//         reservedActivities: [activityName, ...]  // PER-ROUND fields saved
//                                   // (pinned) for teams that are out during
//                                   // THIS round — later rounds typically
//                                   // reserve more as more teams get knocked
//                                   // out. New rounds seed from the previous
//                                   // round's list; fully editable per round.
//       }
//     ],
//     reservedActivities: [activityName, ...],  // legacy league-wide list —
//                                               // fallback when a round has
//                                               // no list of its own
//     currentRound: 1,              // display cache + legacy manual fallback
//     startGameCount: null|number   // AUTOMATIC ROUND TRACKING anchor: the
//                                   // league's total recorded game count
//                                   // (history.gamesPerDate tiles) at the
//                                   // moment playoffs started. Each league
//                                   // tile after that plays the next round:
//                                   //   round = gameNumber - startGameCount
//                                   // null = legacy manual currentRound mode.
//   }
//
// A matchup with an empty teamA/teamB is a placeholder the user hasn't filled
// in yet — the schedulers ignore it (getActiveMatchups requires both teams).
// Legacy brackets generated by v1 still load: their rounds/matchups have the
// same shape (plus BYE entries, which are filtered out), and the old
// style/seedOrder/bracketAdjust fields are simply ignored.
//
// Public API: window.PlayoffMode
//   getOrInit(league)             - normalize + return league.playoff
//   isLeagueInPlayoff(league)     - enabled && has rounds
//   getActiveRound(league)        - round whose number === currentRound
//   getActiveMatchups(league)     - fully-specified, undecided matchups of the
//                                   active round (what the scheduler places)
//   getRoundByNumber(league, n)   - user-defined round n, or null
//   isRoundComplete(round)        - every filled matchup has a winner
//   createMatchup()               - one empty matchup object
//   createRound(p, matchupCount)  - append a user-defined round with N empty matchups
//   removeRound(p, number)        - delete a round + renumber the rest
//   getEliminatedTeams(league, beforeRound?) - teams that lost and never reappear
//                                   later; beforeRound limits to "out going into
//                                   round N"
//   getFieldShortages(round, opts) - pure capacity check: which sports have more
//                                   games than fields that can host them (see the
//                                   function header for opts + return shape)
//   getReservedForRound(league, n) - round n's reserved fields (legacy fallback)
//   getChampion(league)           - winner of a decided single-matchup final, or null
//   render(league, mountEl, opts) - deprecated stub; the live UI is PlayoffHub
// =============================================================================
(function () {
    'use strict';

    var VERSION = '2.2.0';

    function uid() {
        return 'mu_' + Date.now().toString(36) + '_' + Math.random().toString(36).slice(2, 7);
    }

    // -------------------------------------------------------------------------
    // Data model
    // -------------------------------------------------------------------------

    function createMatchup() {
        return {
            id: uid(),
            teamA: '',
            teamB: '',
            sport: '',
            field: '',      // '' = auto (scheduler picks any compatible field)
            winner: null
        };
    }

    // Append a new round with `matchupCount` empty matchups. Returns the round.
    // Reserved fields carry FORWARD: the new round starts with the previous
    // round's reserved list (eliminations accumulate — round 3 usually needs
    // more fields than round 2), and the user edits it from there.
    function createRound(p, matchupCount) {
        var n = 0, prev = null;
        (p.rounds || []).forEach(function (r) {
            if (r && typeof r.number === 'number' && r.number > n) { n = r.number; prev = r; }
        });
        var count = Math.max(1, Math.min(64, parseInt(matchupCount, 10) || 1));
        var matchups = [];
        for (var i = 0; i < count; i++) matchups.push(createMatchup());
        var seedReserved = (prev && Array.isArray(prev.reservedActivities))
            ? prev.reservedActivities.slice()
            : (Array.isArray(p.reservedActivities) ? p.reservedActivities.slice() : []);
        var round = { number: n + 1, matchups: matchups, byes: [], reservedActivities: seedReserved };
        if (!Array.isArray(p.rounds)) p.rounds = [];
        p.rounds.push(round);
        return round;
    }

    // Delete round `number`, renumber the remaining rounds 1..N (preserving
    // order) and keep currentRound pointing at a valid round.
    function removeRound(p, number) {
        if (!Array.isArray(p.rounds)) return;
        p.rounds = p.rounds.filter(function (r) { return r && r.number !== number; });
        p.rounds.forEach(function (r, i) { r.number = i + 1; });
        if (p.rounds.length === 0) p.currentRound = 1;
        else if (p.currentRound > p.rounds.length) p.currentRound = p.rounds.length;
        else if (p.currentRound < 1) p.currentRound = 1;
    }

    function getOrInit(league) {
        if (!league.playoff || typeof league.playoff !== 'object') {
            league.playoff = {
                enabled: false,
                rounds: [],
                reservedActivities: [],
                currentRound: 1
            };
        }
        var p = league.playoff;
        if (typeof p.enabled !== 'boolean') p.enabled = false;
        if (!Array.isArray(p.rounds)) p.rounds = [];
        if (!Array.isArray(p.reservedActivities)) p.reservedActivities = [];
        if (typeof p.currentRound !== 'number' || p.currentRound < 1) p.currentRound = 1;
        if (typeof p.startGameCount !== 'number' || p.startGameCount < 0) p.startGameCount = null;
        // Normalize every round/matchup (also migrates v1 auto-generated
        // brackets — same shape; extra v1 fields like seedA/seedB/isBye and
        // the top-level style/seedOrder/bracketAdjust are left alone/ignored).
        p.rounds.forEach(function (r, i) {
            if (!r || typeof r !== 'object') return;
            if (typeof r.number !== 'number') r.number = i + 1;
            if (!Array.isArray(r.matchups)) r.matchups = [];
            if (!Array.isArray(r.byes)) r.byes = [];
            // Migration: rounds from before per-round reservations inherit the
            // legacy league-wide list (preserves the old locking behavior).
            if (!Array.isArray(r.reservedActivities)) r.reservedActivities = p.reservedActivities.slice();
            r.matchups.forEach(function (m) {
                if (!m || typeof m !== 'object') return;
                if (!m.id) m.id = uid();
                if (typeof m.teamA !== 'string') m.teamA = m.teamA || '';
                if (typeof m.teamB !== 'string') m.teamB = m.teamB || '';
                if (typeof m.sport !== 'string') m.sport = m.sport || '';
                if (typeof m.field !== 'string') m.field = m.field || '';
                if (m.winner === undefined) m.winner = null;
            });
        });
        return p;
    }

    // -------------------------------------------------------------------------
    // State accessors (scheduler-facing — keep semantics stable)
    // -------------------------------------------------------------------------

    function isLeagueInPlayoff(league) {
        return !!(league && league.playoff && league.playoff.enabled
            && Array.isArray(league.playoff.rounds) && league.playoff.rounds.length > 0);
    }

    function getRoundByNumber(league, number) {
        if (!league || !league.playoff || !Array.isArray(league.playoff.rounds)) return null;
        for (var i = 0; i < league.playoff.rounds.length; i++) {
            var r = league.playoff.rounds[i];
            if (r && r.number === number) return r;
        }
        return null;
    }

    function getActiveRound(league) {
        if (!isLeagueInPlayoff(league)) return null;
        var p = league.playoff;
        var byNumber = getRoundByNumber(league, p.currentRound);
        if (byNumber) return byNumber;
        // Fallback (legacy data with gaps, e.g. a v1 play-in round 0): clamp by index.
        var idx = Math.min(Math.max(p.currentRound - 1, 0), p.rounds.length - 1);
        return p.rounds[idx] || null;
    }

    // Matchups the scheduler should actually place: both teams chosen, no BYE
    // placeholders, winner not decided yet.
    function getActiveMatchups(league) {
        var r = getActiveRound(league);
        if (!r || !r.matchups) return [];
        return r.matchups.filter(function (m) {
            return m && m.teamA && m.teamB
                && m.teamA !== 'BYE' && m.teamB !== 'BYE'
                && !m.winner;
        });
    }

    // A round is complete when it has at least one fully-specified matchup,
    // no half-filled matchup (one team picked, the other blank), and every
    // fully-specified matchup has a winner. Untouched placeholder matchups
    // (both teams blank) don't block completion — but the Hub nags about them.
    function isRoundComplete(round) {
        if (!round || !Array.isArray(round.matchups) || round.matchups.length === 0) return false;
        var filled = [];
        for (var i = 0; i < round.matchups.length; i++) {
            var m = round.matchups[i];
            if (!m) continue;
            // Legacy v1 bye matchup — auto-advance, never blocks completion
            if (m.teamA === 'BYE' || m.teamB === 'BYE') continue;
            if (m.teamA && m.teamB) filled.push(m);
            else if (m.teamA || m.teamB) return false;   // half-filled — user isn't done
        }
        if (filled.length === 0) return false;
        return filled.every(function (m) { return !!m.winner; });
    }

    // -------------------------------------------------------------------------
    // Derived team status
    // -------------------------------------------------------------------------

    // A team is OUT when it lost a decided matchup and does not appear in any
    // later round (as a matchup team or a bye). Appearing later re-enters the
    // team — the user is free to shape the tournament however they like.
    // Optional `beforeRound`: only count losses in rounds BEFORE that number —
    // "who is out going into round N" (drives the per-round reserved-fields UI).
    function getEliminatedTeams(league, beforeRound) {
        if (!league || !league.playoff || !Array.isArray(league.playoff.rounds)) return [];
        var rounds = league.playoff.rounds;
        var lossRound = {};   // team -> highest round number it lost in
        rounds.forEach(function (r) {
            if (!r || !Array.isArray(r.matchups)) return;
            if (typeof beforeRound === 'number' && r.number >= beforeRound) return;
            r.matchups.forEach(function (m) {
                if (!m || !m.winner || !m.teamA || !m.teamB) return;
                if (m.teamA === 'BYE' || m.teamB === 'BYE') return;
                var loser = null;
                if (m.winner === m.teamA) loser = m.teamB;
                else if (m.winner === m.teamB) loser = m.teamA;
                if (!loser) return;
                if (!(loser in lossRound) || r.number > lossRound[loser]) lossRound[loser] = r.number;
            });
        });
        var out = [];
        Object.keys(lossRound).forEach(function (team) {
            var reappears = rounds.some(function (r) {
                if (!r || r.number <= lossRound[team]) return false;
                var inMatchup = (r.matchups || []).some(function (m) {
                    return m && (m.teamA === team || m.teamB === team);
                });
                return inMatchup || (r.byes || []).indexOf(team) >= 0;
            });
            if (!reappears) out.push(team);
        });
        return out.sort();
    }

    // -------------------------------------------------------------------------
    // Field-capacity analysis — "you scheduled 6 baseball games but only 5
    // baseball fields exist". Pure: all availability comes in via `opts`.
    //
    //   getFieldShortages(round, opts)
    //     opts.fieldsForSport(sport) -> [fieldName, ...]   (regular leagues:
    //                                    which fields can host that sport)
    //     opts.sharedFieldPool       -> [fieldName, ...]   (specialty leagues:
    //                                    every court hosts every matchup —
    //                                    used when fieldsForSport is absent)
    //     opts.gamesPerField         -> games one field hosts simultaneously
    //                                    (default 1; specialty gamesPerFieldSlot)
    //
    // Only matchups the scheduler would actually place are counted: both teams
    // picked, no BYE, no winner yet. The round's reservedActivities are saved
    // for the teams that are OUT, so they don't count toward game capacity —
    // EXCEPT a reserved field the user explicitly picked for a matchup (an
    // explicit pick wins in the scheduler too).
    //
    // Returns a list of shortage objects, worst problems first:
    //   { kind:'no_sport',   count }                        — matchups the
    //       scheduler will SKIP because no sport is picked (only when
    //       fieldsForSport mode is active; specialty courts are sport-agnostic)
    //   { kind:'sport',      sport, games, capacity, shortfall }
    //       — more games of one sport than fields that can host it
    //   { kind:'field_dup',  field, picks }                 — the same field
    //       explicitly picked for more picks than it can host at once
    //   { kind:'overall',    games, capacity, shortfall }   — cross-sport
    //       contention: every per-sport count fits, but the sports SHARE
    //       fields and there aren't enough distinct fields for all games
    // An empty array means every pending matchup can get a field.
    // -------------------------------------------------------------------------
    function getFieldShortages(round, opts) {
        var out = [];
        if (!round || !Array.isArray(round.matchups)) return out;
        opts = opts || {};
        var perField = Math.max(1, parseInt(opts.gamesPerField, 10) || 1);
        var sportMode = typeof opts.fieldsForSport === 'function';
        var pool = Array.isArray(opts.sharedFieldPool) ? opts.sharedFieldPool : [];
        var reserved = {};
        (Array.isArray(round.reservedActivities) ? round.reservedActivities : [])
            .forEach(function (f) { reserved[String(f)] = true; });

        // Matchups the scheduler will try to place.
        var pending = round.matchups.filter(function (m) {
            return m && m.teamA && m.teamB && m.teamA !== 'BYE' && m.teamB !== 'BYE' && !m.winner;
        });
        if (pending.length === 0) return out;

        // Sport-mode: matchups without a sport are silently skipped by the
        // scheduler — surface that first, and analyze only the rest.
        if (sportMode) {
            var noSport = pending.filter(function (m) { return !m.sport; }).length;
            if (noSport > 0) out.push({ kind: 'no_sport', count: noSport });
            pending = pending.filter(function (m) { return !!m.sport; });
            if (pending.length === 0) return out;
        }

        // Candidate fields per matchup: an explicit user pick always counts
        // (even if reserved); auto-pick uses compatible non-reserved fields.
        function candidatesFor(m) {
            var base = sportMode ? (opts.fieldsForSport(m.sport) || []) : pool;
            var set = {};
            base.forEach(function (f) {
                f = String(f);
                if (!reserved[f]) set[f] = true;
            });
            if (m.field && base.indexOf(m.field) >= 0) set[String(m.field)] = true;
            return Object.keys(set);
        }

        // ── Per-sport counts (the headline warning the user reads) ──
        if (sportMode) {
            var bySport = {};
            pending.forEach(function (m) {
                (bySport[m.sport] = bySport[m.sport] || []).push(m);
            });
            Object.keys(bySport).sort().forEach(function (sport) {
                var games = bySport[sport].length;
                var usable = {};
                bySport[sport].forEach(function (m) {
                    candidatesFor(m).forEach(function (f) { usable[f] = true; });
                });
                var capacity = Object.keys(usable).length * perField;
                if (games > capacity) {
                    out.push({ kind: 'sport', sport: sport, games: games, capacity: capacity, shortfall: games - capacity });
                }
            });
        }

        // ── Duplicate explicit picks: same field hand-picked too many times ──
        var explicitCounts = {};
        pending.forEach(function (m) {
            if (m.field) explicitCounts[String(m.field)] = (explicitCounts[String(m.field)] || 0) + 1;
        });
        Object.keys(explicitCounts).sort().forEach(function (f) {
            if (explicitCounts[f] > perField) {
                out.push({ kind: 'field_dup', field: f, picks: explicitCounts[f] });
            }
        });

        // ── Overall feasibility: maximum bipartite matching of matchups onto
        //    field slots (each field expands to `perField` slots). Catches
        //    cross-sport contention on shared fields that per-sport counts
        //    can't see (e.g. 2 baseball + 2 kickball games on 3 dual-use
        //    fields). Sizes here are tiny (≤64 matchups), so the classic
        //    augmenting-path algorithm is plenty.
        var slotIds = {};   // field slot key -> index
        var slotList = [];
        var adj = pending.map(function (m) {
            return candidatesFor(m).reduce(function (acc, f) {
                for (var c = 0; c < perField; c++) {
                    var key = f + ' ' + c;
                    if (!(key in slotIds)) { slotIds[key] = slotList.length; slotList.push(key); }
                    acc.push(slotIds[key]);
                }
                return acc;
            }, []);
        });
        var slotOwner = new Array(slotList.length).fill(-1);
        function tryPlace(i, seen) {
            var edges = adj[i];
            for (var k = 0; k < edges.length; k++) {
                var s = edges[k];
                if (seen[s]) continue;
                seen[s] = true;
                if (slotOwner[s] === -1 || tryPlace(slotOwner[s], seen)) {
                    slotOwner[s] = i;
                    return true;
                }
            }
            return false;
        }
        var placed = 0;
        for (var i = 0; i < pending.length; i++) {
            if (tryPlace(i, new Array(slotList.length).fill(false))) placed++;
        }
        if (placed < pending.length) {
            // Only add the overall entry when it says something the per-sport
            // entries didn't already: more drops than the per-sport shortfalls
            // account for, or no per-sport shortfall at all.
            var sportShortfall = out.reduce(function (a, w) { return a + (w.kind === 'sport' ? w.shortfall : 0); }, 0);
            var totalShort = pending.length - placed;
            if (totalShort > sportShortfall) {
                out.push({ kind: 'overall', games: pending.length, capacity: placed, shortfall: totalShort });
            }
        }
        return out;
    }

    // Reserved fields to lock for a given round: the round's own list, with
    // the legacy league-wide list as fallback (rounds not built yet / old data).
    function getReservedForRound(league, roundNumber) {
        var r = getRoundByNumber(league, roundNumber);
        if (r && Array.isArray(r.reservedActivities)) return r.reservedActivities;
        return (league && league.playoff && Array.isArray(league.playoff.reservedActivities))
            ? league.playoff.reservedActivities : [];
    }

    // Champion: the last round has exactly one fully-specified matchup and it
    // has a winner.
    function getChampion(league) {
        if (!isLeagueInPlayoff(league)) return null;
        var rounds = league.playoff.rounds;
        var last = rounds[rounds.length - 1];
        if (!last || !Array.isArray(last.matchups)) return null;
        var filled = last.matchups.filter(function (m) {
            return m && m.teamA && m.teamB && m.teamA !== 'BYE' && m.teamB !== 'BYE';
        });
        if (filled.length !== 1) return null;
        return filled[0].winner || null;
    }

    // -------------------------------------------------------------------------
    // Deprecated inline UI stub — the live editor is PlayoffHub (playoff_hub.js).
    // Kept so legacy mount helpers don't crash if ever reached.
    // -------------------------------------------------------------------------
    function render(league, mountEl, opts) {
        if (!mountEl) return;
        mountEl.innerHTML = '';
        var note = document.createElement('div');
        note.style.cssText = 'padding:12px;color:#6B7280;font-size:0.85rem;';
        note.textContent = 'Playoff setup has moved to the Playoff Hub — use the "Playoff Mode" button on the league card.';
        mountEl.appendChild(note);
        if (window.PlayoffHub && typeof window.PlayoffHub.open === 'function' && league) {
            var btn = document.createElement('button');
            btn.type = 'button';
            btn.textContent = 'Open Playoff Hub';
            btn.style.cssText = 'margin:0 12px 12px;padding:8px 14px;border:1px solid #147D91;color:#147D91;background:#fff;border-radius:8px;cursor:pointer;font-family:inherit;';
            btn.onclick = function () { window.PlayoffHub.open(league, (opts && opts.kind) || 'regular'); };
            mountEl.appendChild(btn);
        }
    }

    // -------------------------------------------------------------------------
    // Public API
    // -------------------------------------------------------------------------
    var api = {
        VERSION: VERSION,
        getOrInit: getOrInit,
        isLeagueInPlayoff: isLeagueInPlayoff,
        getActiveRound: getActiveRound,
        getActiveMatchups: getActiveMatchups,
        getRoundByNumber: getRoundByNumber,
        isRoundComplete: isRoundComplete,
        createMatchup: createMatchup,
        createRound: createRound,
        removeRound: removeRound,
        getEliminatedTeams: getEliminatedTeams,
        getFieldShortages: getFieldShortages,
        getReservedForRound: getReservedForRound,
        getChampion: getChampion,
        render: render
    };

    if (typeof window !== 'undefined') window.PlayoffMode = api;
    if (typeof module !== 'undefined' && module.exports) module.exports = api;

    if (typeof console !== 'undefined') console.log('[PlayoffMode] v' + VERSION + ' loaded (user-defined rounds)');
})();
