// =============================================================================
// playoff_mode.js — shared playoff data model for Leagues + Specialty Leagues
// =============================================================================
// v2 — USER-DEFINED ROUNDS.
// The old auto-generated bracket engine (seed list, fixed/reseed styles,
// play-in / eliminate / bye adjustments, advanceFixed / advanceReseed and the
// dead inline render UI) is GONE. The user now builds every round by hand in
// the Playoff Hub (playoff_hub.js): how many matchups a round has, which team
// plays which, which sport they play, and (optionally) which field. This
// module owns only the data model + pure helpers that the schedulers consume.
//
//   league.playoff = {
//     enabled: bool,
//     rounds: [
//       { number: 1,
//         matchups: [ { id, teamA, teamB, sport, field, winner } ],
//         byes: [teamName, ...],    // sit out this round, still in the playoffs
//         reservedActivities: [activityName, ...]  // PER-ROUND fields saved
//                                   // (pinned) for teams that are out during
//                                   // THIS round — later rounds typically
//                                   // reserve more as more teams get knocked
//                                   // out. New rounds seed from the previous
//                                   // round's list; fully editable per round.
//       }
//     ],
//     reservedActivities: [activityName, ...],  // legacy league-wide list —
//                                               // fallback when a round has
//                                               // no list of its own
//     currentRound: 1,              // display cache + legacy manual fallback
//     startGameCount: null|number   // AUTOMATIC ROUND TRACKING anchor: the
//                                   // league's total recorded game count
//                                   // (history.gamesPerDate tiles) at the
//                                   // moment playoffs started. Each league
//                                   // tile after that plays the next round:
//                                   //   round = gameNumber - startGameCount
//                                   // null = legacy manual currentRound mode.
//   }
//
// A matchup with an empty teamA/teamB is a placeholder the user hasn't filled
// in yet — the schedulers ignore it (getActiveMatchups requires both teams).
// Legacy brackets generated by v1 still load: their rounds/matchups have the
// same shape (plus BYE entries, which are filtered out), and the old
// style/seedOrder/bracketAdjust fields are simply ignored.
//
// Public API: window.PlayoffMode
//   getOrInit(league)             - normalize + return league.playoff
//   isLeagueInPlayoff(league)     - enabled && has rounds
//   getActiveRound(league)        - round whose number === currentRound
//   getActiveMatchups(league)     - fully-specified, undecided matchups of the
//                                   active round (what the scheduler places)
//   getRoundByNumber(league, n)   - user-defined round n, or null
//   isRoundComplete(round)        - every filled matchup has a winner
//   createMatchup()               - one empty matchup object
//   createRound(p, matchupCount)  - append a user-defined round with N empty matchups
//   removeRound(p, number)        - delete a round + renumber the rest
//   getEliminatedTeams(league, beforeRound?) - teams that lost and never reappear
//                                   later; beforeRound limits to "out going into
//                                   round N"
//   getReservedForRound(league, n) - round n's reserved fields (legacy fallback)
//   getChampion(league)           - winner of a decided single-matchup final, or null
//   render(league, mountEl, opts) - deprecated stub; the live UI is PlayoffHub
// =============================================================================
(function () {
    'use strict';

    var VERSION = '2.1.0';

    function uid() {
        return 'mu_' + Date.now().toString(36) + '_' + Math.random().toString(36).slice(2, 7);
    }

    // -------------------------------------------------------------------------
    // Data model
    // -------------------------------------------------------------------------

    function createMatchup() {
        return {
            id: uid(),
            teamA: '',
            teamB: '',
            sport: '',
            field: '',      // '' = auto (scheduler picks any compatible field)
            winner: null
        };
    }

    // Append a new round with `matchupCount` empty matchups. Returns the round.
    // Reserved fields carry FORWARD: the new round starts with the previous
    // round's reserved list (eliminations accumulate — round 3 usually needs
    // more fields than round 2), and the user edits it from there.
    function createRound(p, matchupCount) {
        var n = 0, prev = null;
        (p.rounds || []).forEach(function (r) {
            if (r && typeof r.number === 'number' && r.number > n) { n = r.number; prev = r; }
        });
        var count = Math.max(1, Math.min(64, parseInt(matchupCount, 10) || 1));
        var matchups = [];
        for (var i = 0; i < count; i++) matchups.push(createMatchup());
        var seedReserved = (prev && Array.isArray(prev.reservedActivities))
            ? prev.reservedActivities.slice()
            : (Array.isArray(p.reservedActivities) ? p.reservedActivities.slice() : []);
        var round = { number: n + 1, matchups: matchups, byes: [], reservedActivities: seedReserved };
        if (!Array.isArray(p.rounds)) p.rounds = [];
        p.rounds.push(round);
        return round;
    }

    // Delete round `number`, renumber the remaining rounds 1..N (preserving
    // order) and keep currentRound pointing at a valid round.
    function removeRound(p, number) {
        if (!Array.isArray(p.rounds)) return;
        p.rounds = p.rounds.filter(function (r) { return r && r.number !== number; });
        p.rounds.forEach(function (r, i) { r.number = i + 1; });
        if (p.rounds.length === 0) p.currentRound = 1;
        else if (p.currentRound > p.rounds.length) p.currentRound = p.rounds.length;
        else if (p.currentRound < 1) p.currentRound = 1;
    }

    function getOrInit(league) {
        if (!league.playoff || typeof league.playoff !== 'object') {
            league.playoff = {
                enabled: false,
                rounds: [],
                reservedActivities: [],
                currentRound: 1
            };
        }
        var p = league.playoff;
        if (typeof p.enabled !== 'boolean') p.enabled = false;
        if (!Array.isArray(p.rounds)) p.rounds = [];
        if (!Array.isArray(p.reservedActivities)) p.reservedActivities = [];
        if (typeof p.currentRound !== 'number' || p.currentRound < 1) p.currentRound = 1;
        if (typeof p.startGameCount !== 'number' || p.startGameCount < 0) p.startGameCount = null;
        // Normalize every round/matchup (also migrates v1 auto-generated
        // brackets — same shape; extra v1 fields like seedA/seedB/isBye and
        // the top-level style/seedOrder/bracketAdjust are left alone/ignored).
        p.rounds.forEach(function (r, i) {
            if (!r || typeof r !== 'object') return;
            if (typeof r.number !== 'number') r.number = i + 1;
            if (!Array.isArray(r.matchups)) r.matchups = [];
            if (!Array.isArray(r.byes)) r.byes = [];
            // Migration: rounds from before per-round reservations inherit the
            // legacy league-wide list (preserves the old locking behavior).
            if (!Array.isArray(r.reservedActivities)) r.reservedActivities = p.reservedActivities.slice();
            r.matchups.forEach(function (m) {
                if (!m || typeof m !== 'object') return;
                if (!m.id) m.id = uid();
                if (typeof m.teamA !== 'string') m.teamA = m.teamA || '';
                if (typeof m.teamB !== 'string') m.teamB = m.teamB || '';
                if (typeof m.sport !== 'string') m.sport = m.sport || '';
                if (typeof m.field !== 'string') m.field = m.field || '';
                if (m.winner === undefined) m.winner = null;
            });
        });
        return p;
    }

    // -------------------------------------------------------------------------
    // State accessors (scheduler-facing — keep semantics stable)
    // -------------------------------------------------------------------------

    function isLeagueInPlayoff(league) {
        return !!(league && league.playoff && league.playoff.enabled
            && Array.isArray(league.playoff.rounds) && league.playoff.rounds.length > 0);
    }

    function getRoundByNumber(league, number) {
        if (!league || !league.playoff || !Array.isArray(league.playoff.rounds)) return null;
        for (var i = 0; i < league.playoff.rounds.length; i++) {
            var r = league.playoff.rounds[i];
            if (r && r.number === number) return r;
        }
        return null;
    }

    function getActiveRound(league) {
        if (!isLeagueInPlayoff(league)) return null;
        var p = league.playoff;
        var byNumber = getRoundByNumber(league, p.currentRound);
        if (byNumber) return byNumber;
        // Fallback (legacy data with gaps, e.g. a v1 play-in round 0): clamp by index.
        var idx = Math.min(Math.max(p.currentRound - 1, 0), p.rounds.length - 1);
        return p.rounds[idx] || null;
    }

    // Matchups the scheduler should actually place: both teams chosen, no BYE
    // placeholders, winner not decided yet.
    function getActiveMatchups(league) {
        var r = getActiveRound(league);
        if (!r || !r.matchups) return [];
        return r.matchups.filter(function (m) {
            return m && m.teamA && m.teamB
                && m.teamA !== 'BYE' && m.teamB !== 'BYE'
                && !m.winner;
        });
    }

    // A round is complete when it has at least one fully-specified matchup,
    // no half-filled matchup (one team picked, the other blank), and every
    // fully-specified matchup has a winner. Untouched placeholder matchups
    // (both teams blank) don't block completion — but the Hub nags about them.
    function isRoundComplete(round) {
        if (!round || !Array.isArray(round.matchups) || round.matchups.length === 0) return false;
        var filled = [];
        for (var i = 0; i < round.matchups.length; i++) {
            var m = round.matchups[i];
            if (!m) continue;
            // Legacy v1 bye matchup — auto-advance, never blocks completion
            if (m.teamA === 'BYE' || m.teamB === 'BYE') continue;
            if (m.teamA && m.teamB) filled.push(m);
            else if (m.teamA || m.teamB) return false;   // half-filled — user isn't done
        }
        if (filled.length === 0) return false;
        return filled.every(function (m) { return !!m.winner; });
    }

    // -------------------------------------------------------------------------
    // Derived team status
    // -------------------------------------------------------------------------

    // A team is OUT when it lost a decided matchup and does not appear in any
    // later round (as a matchup team or a bye). Appearing later re-enters the
    // team — the user is free to shape the tournament however they like.
    // Optional `beforeRound`: only count losses in rounds BEFORE that number —
    // "who is out going into round N" (drives the per-round reserved-fields UI).
    function getEliminatedTeams(league, beforeRound) {
        if (!league || !league.playoff || !Array.isArray(league.playoff.rounds)) return [];
        var rounds = league.playoff.rounds;
        var lossRound = {};   // team -> highest round number it lost in
        rounds.forEach(function (r) {
            if (!r || !Array.isArray(r.matchups)) return;
            if (typeof beforeRound === 'number' && r.number >= beforeRound) return;
            r.matchups.forEach(function (m) {
                if (!m || !m.winner || !m.teamA || !m.teamB) return;
                if (m.teamA === 'BYE' || m.teamB === 'BYE') return;
                var loser = null;
                if (m.winner === m.teamA) loser = m.teamB;
                else if (m.winner === m.teamB) loser = m.teamA;
                if (!loser) return;
                if (!(loser in lossRound) || r.number > lossRound[loser]) lossRound[loser] = r.number;
            });
        });
        var out = [];
        Object.keys(lossRound).forEach(function (team) {
            var reappears = rounds.some(function (r) {
                if (!r || r.number <= lossRound[team]) return false;
                var inMatchup = (r.matchups || []).some(function (m) {
                    return m && (m.teamA === team || m.teamB === team);
                });
                return inMatchup || (r.byes || []).indexOf(team) >= 0;
            });
            if (!reappears) out.push(team);
        });
        return out.sort();
    }

    // Reserved fields to lock for a given round: the round's own list, with
    // the legacy league-wide list as fallback (rounds not built yet / old data).
    function getReservedForRound(league, roundNumber) {
        var r = getRoundByNumber(league, roundNumber);
        if (r && Array.isArray(r.reservedActivities)) return r.reservedActivities;
        return (league && league.playoff && Array.isArray(league.playoff.reservedActivities))
            ? league.playoff.reservedActivities : [];
    }

    // Champion: the last round has exactly one fully-specified matchup and it
    // has a winner.
    function getChampion(league) {
        if (!isLeagueInPlayoff(league)) return null;
        var rounds = league.playoff.rounds;
        var last = rounds[rounds.length - 1];
        if (!last || !Array.isArray(last.matchups)) return null;
        var filled = last.matchups.filter(function (m) {
            return m && m.teamA && m.teamB && m.teamA !== 'BYE' && m.teamB !== 'BYE';
        });
        if (filled.length !== 1) return null;
        return filled[0].winner || null;
    }

    // -------------------------------------------------------------------------
    // Deprecated inline UI stub — the live editor is PlayoffHub (playoff_hub.js).
    // Kept so legacy mount helpers don't crash if ever reached.
    // -------------------------------------------------------------------------
    function render(league, mountEl, opts) {
        if (!mountEl) return;
        mountEl.innerHTML = '';
        var note = document.createElement('div');
        note.style.cssText = 'padding:12px;color:#6B7280;font-size:0.85rem;';
        note.textContent = 'Playoff setup has moved to the Playoff Hub — use the "Playoff Mode" button on the league card.';
        mountEl.appendChild(note);
        if (window.PlayoffHub && typeof window.PlayoffHub.open === 'function' && league) {
            var btn = document.createElement('button');
            btn.type = 'button';
            btn.textContent = 'Open Playoff Hub';
            btn.style.cssText = 'margin:0 12px 12px;padding:8px 14px;border:1px solid #147D91;color:#147D91;background:#fff;border-radius:8px;cursor:pointer;font-family:inherit;';
            btn.onclick = function () { window.PlayoffHub.open(league, (opts && opts.kind) || 'regular'); };
            mountEl.appendChild(btn);
        }
    }

    // -------------------------------------------------------------------------
    // Public API
    // -------------------------------------------------------------------------
    var api = {
        VERSION: VERSION,
        getOrInit: getOrInit,
        isLeagueInPlayoff: isLeagueInPlayoff,
        getActiveRound: getActiveRound,
        getActiveMatchups: getActiveMatchups,
        getRoundByNumber: getRoundByNumber,
        isRoundComplete: isRoundComplete,
        createMatchup: createMatchup,
        createRound: createRound,
        removeRound: removeRound,
        getEliminatedTeams: getEliminatedTeams,
        getReservedForRound: getReservedForRound,
        getChampion: getChampion,
        render: render
    };

    if (typeof window !== 'undefined') window.PlayoffMode = api;
    if (typeof module !== 'undefined' && module.exports) module.exports = api;

    if (typeof console !== 'undefined') console.log('[PlayoffMode] v' + VERSION + ' loaded (user-defined rounds)');
})();
