/**
 * Regression test for the date-change day rebuild.
 *
 * BUG: navigating to an older date rebuilt the day only PARTIALLY. The cloud
 *      merge (ScheduleDB.mergeSchedules) returns the complete day —
 *      scheduleAssignments, scheduleSegments, leagueAssignments, unifiedTimes,
 *      deserialized divisionTimes, _perBunkSlotsData, _autoGenerated and
 *      manualSkeleton — but the date-change handler applied assignments /
 *      leagues / unifiedTimes / divisionTimes / rain and dropped the rest. So:
 *
 *        • window.scheduleSegments kept the PREVIOUS date's cells
 *        • divisionTimes was assigned RAW (not deserialized), losing the
 *          _perBunkSlots custom array property → auto days rendered with gaps
 *        • _autoGenerated / manualSkeleton were lost
 *        • window._autoSkeleton (what the SAVE side reads back) still held the
 *          previous day's skeleton, so the next save of the new date attached
 *          the old date's skeleton to its cloud row
 *        • a transient load failure had no branch at all, leaving the previous
 *          date's schedule on screen under the new date's label
 *        • the empty-date branch cleared only assignments + leagues, so an empty
 *          date still drew the prior day's grid geometry
 *
 * FIX: applyLoadedDay applies every field and then delegates the geometry
 *      restore to loadScheduleForDate (the one function that reattaches
 *      _perBunkSlots with mode isolation and realigns assignments to slot
 *      windows); clearDayInMemory clears EVERY per-day global; and the failure
 *      path falls back to the local copy or clears, never leaving another day's
 *      data on screen.
 *
 * Copies the REAL applyLoadedDay + clearDayInMemory (integration_hooks.js)
 * verbatim, plus the orchestrator's no-data clear.
 *
 * Run with: node --test tests/date_change_rebuild.test.js
 */

const { describe, it, beforeEach } = require('node:test');
const assert = require('node:assert/strict');

global.window = global;
global.console = { log() {}, warn() {}, error() {} };

let _restoreCalls = [];
let _rebuildSegmentsCalls = 0;

// ── VERBATIM: applyLoadedDay (integration_hooks.js) ──
function applyLoadedDay(dateKey, data, source) {
    window.scheduleAssignments = data.scheduleAssignments || {};
    window.leagueAssignments = data.leagueAssignments || {};
    window._scheduleAssignmentsDate = dateKey;

    if (data.scheduleSegments && Object.keys(data.scheduleSegments).length > 0) {
        window.scheduleSegments = data.scheduleSegments;
    } else {
        window.scheduleSegments = {};
        try { window.AutoSegmentModel?.rebuildFromAssignments?.(); } catch (_e) {}
    }

    if (data.unifiedTimes?.length > 0) {
        window.unifiedTimes = data.unifiedTimes;
    }
    if (data.divisionTimes && Object.keys(data.divisionTimes).length > 0) {
        window.divisionTimes = window.DivisionTimesSystem?.deserialize?.(data.divisionTimes) || data.divisionTimes;
        window._divisionTimesFromCloud = true;
    }

    if (data._autoGenerated === true) window._autoGenerated = true;
    else if (data._autoGenerated === false) window._autoGenerated = false;

    if (Array.isArray(data.manualSkeleton) && data.manualSkeleton.length > 0) {
        window.manualSkeleton = data.manualSkeleton;
        window._autoSkeleton = data.manualSkeleton;
    } else {
        window._autoSkeleton = null;
    }

    if (data.isRainyDay === true || data.rainyDayMode === true) {
        window.isRainyDay = true;
    } else if (data.isRainyDay === false) {
        window.isRainyDay = false;
    }
    window.rainyDayStartTime = (data.rainyDayStartTime !== null && data.rainyDayStartTime !== undefined)
        ? data.rainyDayStartTime : null;

    try {
        if (typeof window.loadScheduleForDate === 'function') {
            window.loadScheduleForDate(dateKey);
        }
    } catch (eRestore) {
        console.warn('Full day restore failed:', eRestore?.message || eRestore);
    }

    if (window.updateTable) { try { window.updateTable(); } catch (_e) {} }
}

// ── VERBATIM: clearDayInMemory (integration_hooks.js) ──
function clearDayInMemory(dateKey) {
    window.scheduleAssignments = {};
    window.leagueAssignments = {};
    window.scheduleSegments = {};
    window._scheduleAssignmentsDate = dateKey;
    window._autoSkeleton = null;
    try {
        const dt = window.divisionTimes || {};
        Object.keys(dt).forEach(g => {
            if (dt[g]) { delete dt[g]._perBunkSlots; delete dt[g]._isPerBunk; }
        });
    } catch (_e) {}
    if (window.updateTable) { try { window.updateTable(); } catch (_e) {} }
}

// ── VERBATIM: hydrateWindowGlobals' no-data clear (schedule_orchestrator.js) ──
function orchestratorClearGlobals() {
    window.scheduleAssignments = {};
    window.leagueAssignments = {};
    window.scheduleSegments = {};
    window._autoSkeleton = null;
    try {
        const _dt = window.divisionTimes || {};
        Object.keys(_dt).forEach(g => {
            if (_dt[g]) { delete _dt[g]._perBunkSlots; delete _dt[g]._isPerBunk; }
        });
    } catch (_e) {}
}

// ── The date-change branch selection (integration_hooks.js) ──
function handleLoadResult(dateKey, result) {
    const hasBunks = (d) => d && Object.keys(d.scheduleAssignments || {}).length > 0;
    if (result?.success && result.data) {
        applyLoadedDay(dateKey, result.data, result.source);
        return 'applied';
    } else if (result && !result.success) {
        if (hasBunks(result.data)) {
            applyLoadedDay(dateKey, result.data, 'local-fallback');
            return 'local-fallback';
        }
        clearDayInMemory(dateKey);
        return 'cleared-after-failure';
    } else if (result && result.success) {
        clearDayInMemory(dateKey);
        return 'cleared-empty';
    }
    return 'noop';
}

// ── Fixtures ──

// Simulates the state left over from viewing a PREVIOUS date.
function seedPreviousDate() {
    window.scheduleAssignments = { 'Bunk A': [{ _activity: 'Soccer' }] };
    window.leagueAssignments = { 'Seniors': { 540: { matchups: ['X vs Y'] } } };
    window.scheduleSegments = { 'Bunk A': [[{ activity: 'Soccer' }]] };
    window.unifiedTimes = [{ startMin: 540 }];
    window.divisionTimes = { Seniors: Object.assign([{ startMin: 540 }], { _isPerBunk: true, _perBunkSlots: { 'Bunk A': [{ startMin: 540 }] } }) };
    window.manualSkeleton = [{ tile: 'PREV' }];
    window._autoSkeleton = [{ tile: 'PREV' }];
    window._autoGenerated = true;
    window._scheduleAssignmentsDate = '2026-07-01';
    window.isRainyDay = true;
    window.rainyDayStartTime = 780;
}

beforeEach(() => {
    _restoreCalls = [];
    _rebuildSegmentsCalls = 0;
    window.loadScheduleForDate = (dk) => { _restoreCalls.push(dk); };
    window.AutoSegmentModel = { rebuildFromAssignments: () => { _rebuildSegmentsCalls++; } };
    window.DivisionTimesSystem = {
        // Mimics the real deserialize: reattaches _perBunkSlots from the sidecar.
        deserialize: (dt) => {
            const out = {};
            Object.keys(dt || {}).forEach(g => {
                const arr = Array.isArray(dt[g]) ? dt[g].slice() : dt[g];
                out[g] = arr;
                out[g]._deserialized = true;
            });
            return out;
        }
    };
    window.updateTable = () => {};
    seedPreviousDate();
});

describe('date change → rebuild the day from cloud', () => {

    it('hydrates scheduleSegments from the loaded day (not the previous date)', () => {
        applyLoadedDay('2026-07-15', {
            scheduleAssignments: { 'Bunk B': [{ _activity: 'Swim' }] },
            scheduleSegments: { 'Bunk B': [[{ activity: 'Swim' }]] }
        });
        assert.deepEqual(Object.keys(window.scheduleSegments), ['Bunk B'],
            'segments must come from the loaded day, not linger from the previous one');
    });

    it('rebuilds segments when the saved day predates the segment store', () => {
        applyLoadedDay('2026-07-15', {
            scheduleAssignments: { 'Bunk B': [{ _activity: 'Swim' }] }
            // no scheduleSegments — an older cloud row
        });
        assert.deepEqual(window.scheduleSegments, {},
            "previous date's segments must be cleared first");
        assert.equal(_rebuildSegmentsCalls, 1,
            'segments must be rebuilt from the loaded assignments');
    });

    it('deserializes divisionTimes rather than assigning the raw JSON', () => {
        applyLoadedDay('2026-07-15', {
            scheduleAssignments: { 'Bunk B': [] },
            divisionTimes: { Juniors: [{ startMin: 600 }] }
        });
        assert.equal(window.divisionTimes.Juniors._deserialized, true,
            '_perBunkSlots is a custom array property — a raw assign loses it');
    });

    it('delegates the geometry restore to loadScheduleForDate for THIS date', () => {
        applyLoadedDay('2026-07-15', { scheduleAssignments: { 'Bunk B': [] } });
        assert.deepEqual(_restoreCalls, ['2026-07-15'],
            'per-bunk reattach + slot realignment must run for the newly loaded date');
    });

    it('refreshes BOTH skeleton globals so a save cannot inherit the old day', () => {
        applyLoadedDay('2026-07-15', {
            scheduleAssignments: { 'Bunk B': [] },
            manualSkeleton: [{ tile: 'NEW' }]
        });
        assert.deepEqual(window.manualSkeleton, [{ tile: 'NEW' }]);
        assert.deepEqual(window._autoSkeleton, [{ tile: 'NEW' }],
            'the save side reads _autoSkeleton — it must track the loaded day');
    });

    it('clears _autoSkeleton when the loaded day has no skeleton', () => {
        applyLoadedDay('2026-07-15', { scheduleAssignments: { 'Bunk B': [] } });
        assert.equal(window._autoSkeleton, null,
            "a day with no skeleton must not inherit the previous day's");
    });

    it('stamps the owner date so downstream save guards see a coherent pair', () => {
        applyLoadedDay('2026-07-15', { scheduleAssignments: { 'Bunk B': [] } });
        assert.equal(window._scheduleAssignmentsDate, '2026-07-15');
    });

    it('resets rainy-day state instead of carrying the previous day forward', () => {
        applyLoadedDay('2026-07-15', {
            scheduleAssignments: { 'Bunk B': [] },
            isRainyDay: false
        });
        assert.equal(window.isRainyDay, false);
        assert.equal(window.rainyDayStartTime, null);
    });
});

describe('date change → empty and failed loads', () => {

    it('an empty date clears EVERY per-day global, not just assignments', () => {
        const verdict = handleLoadResult('2026-07-15', { success: true, data: null });
        assert.equal(verdict, 'cleared-empty');
        assert.deepEqual(window.scheduleAssignments, {});
        assert.deepEqual(window.leagueAssignments, {});
        assert.deepEqual(window.scheduleSegments, {}, 'stale segments would redraw the prior day');
        assert.equal(window._autoSkeleton, null);
        assert.equal(window.divisionTimes.Seniors._perBunkSlots, undefined,
            'stale per-bunk geometry would redraw the prior day’s grid');
        assert.equal(window.divisionTimes.Seniors._isPerBunk, undefined);
        assert.equal(window._scheduleAssignmentsDate, '2026-07-15');
    });

    it('a failed load falls back to the local copy of THAT date', () => {
        const verdict = handleLoadResult('2026-07-15', {
            success: false,
            error: 'query-failed',
            source: 'local-fallback',
            data: { scheduleAssignments: { 'Bunk C': [{ _activity: 'Art' }] } }
        });
        assert.equal(verdict, 'local-fallback');
        assert.deepEqual(Object.keys(window.scheduleAssignments), ['Bunk C']);
        assert.equal(window._scheduleAssignmentsDate, '2026-07-15');
    });

    it('a failed load with no local copy clears rather than showing another day', () => {
        const verdict = handleLoadResult('2026-07-15', {
            success: false,
            error: 'query-failed',
            data: { scheduleAssignments: {} }
        });
        assert.equal(verdict, 'cleared-after-failure');
        assert.deepEqual(window.scheduleAssignments, {},
            "the previous date's schedule must never be displayed under the new date");
        assert.equal(window._scheduleAssignmentsDate, '2026-07-15');
    });
});

describe('orchestrator path clears the same set of globals', () => {

    it('clears segments, skeleton and per-bunk geometry when there is no data', () => {
        orchestratorClearGlobals();
        assert.deepEqual(window.scheduleSegments, {});
        assert.equal(window._autoSkeleton, null);
        assert.equal(window.divisionTimes.Seniors._perBunkSlots, undefined);
        assert.equal(window.divisionTimes.Seniors._isPerBunk, undefined);
    });
});
