/**
 * Regression test for reconcileOrphanActivities (integration_hooks.js).
 *
 * BUG: On every cloud load / date switch, the orphan reconcile nulled any slot
 *      whose activity name wasn't in its `validNames` set. That set was built
 *      from a narrow list that OMITTED sportMetaData sports, the live special
 *      list, and wall/custom-layer names (Cleanup / Change / Main Activity…), so
 *      generated activities were treated as orphans and wiped — the schedule lost
 *      its afternoon tail on reload, showing "+ Add" gaps.
 *
 * FIX: build validNames from the canonical getValidActivityNames() (which
 *      includes sportMetaData) + the live special list + wall/system names, AND
 *      never null generator-placed or pinned slots (they're valid by
 *      construction). The reconcile still clears a genuinely-orphaned MANUAL slot.
 *
 * Copies the REAL reconcileOrphanActivities + getValidActivityNames verbatim.
 *
 * Run with: node --test tests/orphan_reconcile.test.js
 */

const { describe, it, beforeEach } = require('node:test');
const assert = require('node:assert/strict');

global.window = global;
global.console = { log() {}, warn() {}, error() {} };
global.logError = () => {};

// ── VERBATIM: Utils.getValidActivityNames (scheduler_core_utils.js:2819) ──
function getValidActivityNames() {
    const g = window.loadGlobalSettings?.() || {};
    const fields = g.app1?.fields || [];
    const specials = g.app1?.specialActivities || [];
    const valid = new Set();
    fields.forEach(f => (f.activities || []).forEach(a => valid.add(a)));
    specials.forEach(s => { if (s.name) valid.add(s.name); });
    (g.app1?.allSports || []).forEach(s => { if (s) valid.add(s); });
    Object.keys(g.app1?.sportMetaData || {}).forEach(s => { if (s) valid.add(s); });
    return valid;
}

// ── VERBATIM: reconcileOrphanActivities (integration_hooks.js:1131) ──
function reconcileOrphanActivities() {
    try {
        if (!window.scheduleAssignments) return 0;
        const validNames = new Set();
        try {
            const canon = window.SchedulerCoreUtils?.getValidActivityNames?.();
            if (canon && typeof canon.forEach === 'function') canon.forEach(n => n && validNames.add(n));
        } catch (_) {}
        try {
            const settings = window.loadGlobalSettings?.() || {};
            const app1 = settings.app1 || {};
            (app1.fields || []).forEach(f => (f.activities || []).forEach(a => a && validNames.add(a)));
            (app1.specialActivities || []).forEach(s => s?.name && validNames.add(s.name));
            (settings.specialActivities || []).forEach(s => s?.name && validNames.add(s.name));
            Object.keys(app1.sportMetaData || {}).forEach(n => n && validNames.add(n));
            (app1.allSports || []).forEach(s => { const n = typeof s === 'string' ? s : s?.name; if (n) validNames.add(n); });
            (settings.facilities || []).forEach(fac => {
                (fac.activities || []).forEach(a => a && validNames.add(a));
                (fac.specialActivityNames || []).forEach(n => n && validNames.add(n));
                (fac.generalActivities || []).forEach(ga => {
                    const n = (ga && ga.name) || ga;
                    if (n) validNames.add(n);
                });
            });
            (settings.allSports || []).forEach(s => {
                const n = typeof s === 'string' ? s : s?.name;
                if (n) validNames.add(n);
            });
        } catch (_) {}
        try {
            const live = (typeof window.getAllSpecialActivities === 'function') ? window.getAllSpecialActivities() : null;
            if (Array.isArray(live)) live.forEach(s => s?.name && validNames.add(s.name));
        } catch (_) {}
        ['Free', 'Free Play', 'No Field', 'Lunch', 'Snack', 'Snacks', 'Dismissal',
         'Swim', 'Pool', 'League Game',
         'Transition/Buffer', 'Transition', 'Buffer',
         'Lineup', 'Regroup', 'Bus',
         'Change', 'Cleanup', 'Main Activity', 'Davening', 'Mincha', 'Canteen', 'Custom'].forEach(n => validNames.add(n));

        if (validNames.size === 0) return 0;
        const validLower = new Set([...validNames].map(n => String(n).toLowerCase()));

        let nulled = 0;
        Object.keys(window.scheduleAssignments).forEach(bunk => {
            const slots = window.scheduleAssignments[bunk];
            if (!Array.isArray(slots)) return;
            slots.forEach((slot, i) => {
                if (!slot || typeof slot !== 'object') return;
                if (slot._isTransition || slot._league || slot.continuation) return;
                if (slot._autoMode || slot._autoSpecial || slot._autoGenerated || slot._generic ||
                    slot._fixed || slot._pinned || slot._isPrep || slot._bunkOverride) return;
                const name = slot._activity || slot.activity || slot.event;
                if (typeof name === 'string' && name.startsWith('League:')) return;
                if (name && !validLower.has(String(name).toLowerCase())) {
                    slots[i] = null;
                    nulled++;
                }
            });
        });
        return nulled;
    } catch (e) {
        return 0;
    }
}

// ── fixtures: a config where sports live in sportMetaData (NOT fields.activities) ──
beforeEach(() => {
    window.SchedulerCoreUtils = { getValidActivityNames };
    window.loadGlobalSettings = () => ({
        app1: {
            fields: [{ name: 'Court 1', activities: ['gaga'] }],   // only gaga is on a field
            specialActivities: [{ name: 'Gymnastics' }, { name: 'Golf Carting' }],
            sportMetaData: { 'Big Shot': {}, 'Jumbo/ Limbo': {}, 'gaga': {} }  // sports live here
        }
    });
    delete window.getAllSpecialActivities;
});

describe('reconcileOrphanActivities — generated content survives', () => {
    it('keeps a sportMetaData sport placed by the solver (was nulled before)', () => {
        window.scheduleAssignments = {
            'Minors א': [{ _activity: 'Big Shot', sport: 'Big Shot', _autoMode: true, _fixed: true }]
        };
        const nulled = reconcileOrphanActivities();
        assert.equal(nulled, 0);
        assert.ok(window.scheduleAssignments['Minors א'][0], 'Big Shot slot preserved');
    });

    it('keeps a wall/custom-layer slot (Cleanup)', () => {
        window.scheduleAssignments = { 'Minors א': [{ _activity: 'Cleanup' }] };
        reconcileOrphanActivities();
        assert.ok(window.scheduleAssignments['Minors א'][0], 'Cleanup preserved (wall name)');
    });

    it('keeps an auto special even if it is missing from every config copy', () => {
        window.scheduleAssignments = {
            'Minors א': [{ _activity: 'Mystery Special', _autoSpecial: true, _autoMode: true }]
        };
        reconcileOrphanActivities();
        assert.ok(window.scheduleAssignments['Minors א'][0], 'auto-placed slot never nulled');
    });

    it('keeps a special that only exists in the live list', () => {
        window.getAllSpecialActivities = () => [{ name: 'Live Only Special' }];
        window.scheduleAssignments = { 'Minors א': [{ _activity: 'Live Only Special' }] };
        reconcileOrphanActivities();
        assert.ok(window.scheduleAssignments['Minors א'][0], 'live-list special preserved');
    });

    it('a whole generated row survives a reconcile pass', () => {
        window.scheduleAssignments = {
            'Minors ב': [
                { _activity: 'Swim', _fixed: true },
                { _activity: 'Golf Carting', _autoSpecial: true, _autoMode: true },
                { _activity: 'Big Shot', sport: 'Big Shot', _autoMode: true, _fixed: true },
                { _activity: 'Cleanup' },
                { _activity: 'Main Activity', _fixed: true }
            ]
        };
        const nulled = reconcileOrphanActivities();
        assert.equal(nulled, 0, 'no slot nulled');
        assert.equal(window.scheduleAssignments['Minors ב'].filter(Boolean).length, 5);
    });
});

describe('reconcileOrphanActivities — still clears a genuine manual orphan', () => {
    it('nulls an unmarked manual slot whose activity is unknown', () => {
        window.scheduleAssignments = {
            'Minors א': [{ _activity: 'DeletedSport' }]   // not in config, no marker
        };
        const nulled = reconcileOrphanActivities();
        assert.equal(nulled, 1);
        assert.equal(window.scheduleAssignments['Minors א'][0], null);
    });

    it('does NOT touch a known config activity', () => {
        window.scheduleAssignments = { 'Minors א': [{ _activity: 'Gymnastics' }] };
        const nulled = reconcileOrphanActivities();
        assert.equal(nulled, 0);
    });

    it('bails (clears nothing) when the registry is empty', () => {
        window.SchedulerCoreUtils = { getValidActivityNames: () => new Set() };
        window.loadGlobalSettings = () => ({});
        // The wall-name seed keeps validNames non-empty, so an unknown manual slot
        // would still be cleared; verify a wall slot is safe even then.
        window.scheduleAssignments = { 'Minors א': [{ _activity: 'Lunch' }] };
        reconcileOrphanActivities();
        assert.ok(window.scheduleAssignments['Minors א'][0], 'Lunch (system) preserved');
    });
});
