-- ============================================================================
-- Migration: link_parent_invites — parent portal access via secure tokens
--
-- Why: when a camp accepts a camper application in Campistry Me, the parent
--      needs a way to access the Campistry Link parent portal without a
--      full Supabase Auth account. A secure random token (256-bit entropy)
--      serves as the parent's credential. The token is generated by the admin
--      on acceptance, stored here, and shared with the parent as a URL.
--
-- Token security model:
--   - 64-char hex token = 256 bits entropy — enumeration is infeasible
--   - Tokens expire after 365 days by default (configurable per invite)
--   - Admins can revoke any token (status = 'revoked')
--   - get_parent_invite_data() RPC is SECURITY DEFINER so it can read the
--     table without requiring the parent to have an authenticated session
--
-- Parent data in camper_data JSONB:
--   Snapshot of the camper's public-facing info at acceptance time.
--   Includes name, age, division, grade, bunk, session, counselor, and
--   the parent's own submission data (allergies, medical, contacts).
--   Stored here so the parent portal works without needing camp_state_kv
--   access (which is restricted to authenticated camp staff).
-- ============================================================================

-- ─── 1. Table ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS link_parent_invites (
    id            uuid          NOT NULL DEFAULT gen_random_uuid(),
    camp_id       uuid          NOT NULL,
    token         text          NOT NULL,
    parent_name   text          NOT NULL,
    parent_email  text          NOT NULL,
    family_id     text,
    camper_names  jsonb,        -- ['Eli Miller', 'Mia Miller']
    camper_data   jsonb,        -- { 'Eli Miller': { division, grade, bunk, ... } }
    status        text          NOT NULL DEFAULT 'active',  -- active | revoked
    expires_at    timestamptz,
    created_at    timestamptz   NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT link_parent_invites_token_unique UNIQUE (token)
);

CREATE INDEX IF NOT EXISTS idx_link_parent_invites_camp
    ON link_parent_invites (camp_id);

CREATE INDEX IF NOT EXISTS idx_link_parent_invites_token
    ON link_parent_invites (token);

CREATE INDEX IF NOT EXISTS idx_link_parent_invites_email
    ON link_parent_invites (camp_id, parent_email);

-- ─── 2. RLS ───────────────────────────────────────────────────────────────────
-- Admin-side access: authenticated camp staff can manage invites.
-- Parent-side access: handled entirely by the get_parent_invite_data() RPC
-- (SECURITY DEFINER), so no anon SELECT policy is needed here.
ALTER TABLE link_parent_invites ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS link_parent_invites_select ON link_parent_invites;
CREATE POLICY link_parent_invites_select ON link_parent_invites
    FOR SELECT
    USING (
        camp_id = get_user_camp_id()
        AND get_user_role() = ANY (ARRAY['owner'::text, 'admin'::text, 'scheduler'::text])
    );

DROP POLICY IF EXISTS link_parent_invites_insert ON link_parent_invites;
CREATE POLICY link_parent_invites_insert ON link_parent_invites
    FOR INSERT
    WITH CHECK (
        camp_id = get_user_camp_id()
        AND get_user_role() = ANY (ARRAY['owner'::text, 'admin'::text])
    );

DROP POLICY IF EXISTS link_parent_invites_update ON link_parent_invites;
CREATE POLICY link_parent_invites_update ON link_parent_invites
    FOR UPDATE
    USING (
        camp_id = get_user_camp_id()
        AND get_user_role() = ANY (ARRAY['owner'::text, 'admin'::text])
    );

DROP POLICY IF EXISTS link_parent_invites_delete ON link_parent_invites;
CREATE POLICY link_parent_invites_delete ON link_parent_invites
    FOR DELETE
    USING (
        camp_id = get_user_camp_id()
        AND get_user_role() = ANY (ARRAY['owner'::text, 'admin'::text])
    );

-- ─── 3. RPC: get_parent_invite_data ──────────────────────────────────────────
-- Called by the parent portal with the token from the invite URL.
-- SECURITY DEFINER so it bypasses RLS — the token IS the credential.
-- Returns the parent's data if the token is valid and active.
-- Idempotent: repeated calls with the same token always return the same data.
CREATE OR REPLACE FUNCTION public.get_parent_invite_data(p_token text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path = public, pg_catalog
AS $$
DECLARE
    inv link_parent_invites;
BEGIN
    SELECT * INTO inv
    FROM link_parent_invites
    WHERE token = p_token
      AND status = 'active'
      AND (expires_at IS NULL OR expires_at > now())
    LIMIT 1;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('success', false, 'error', 'invalid_or_expired');
    END IF;

    RETURN jsonb_build_object(
        'success',      true,
        'camp_id',      inv.camp_id,
        'parent_name',  inv.parent_name,
        'parent_email', inv.parent_email,
        'family_id',    inv.family_id,
        'camper_names', inv.camper_names,
        'camper_data',  inv.camper_data
    );
END;
$$;

REVOKE ALL ON FUNCTION public.get_parent_invite_data(text) FROM public;
GRANT EXECUTE ON FUNCTION public.get_parent_invite_data(text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_parent_invite_data(text) TO authenticated;

-- ─── 4. Sanity check ──────────────────────────────────────────────────────────
-- Verify the table and function exist:
--
--   SELECT tablename, rowsecurity FROM pg_tables
--   WHERE tablename = 'link_parent_invites' AND schemaname = 'public';
--
--   SELECT proname, prosecdef FROM pg_proc
--   WHERE proname = 'get_parent_invite_data';
--   -- prosecdef should be true (SECURITY DEFINER)
