-- ============================================================================
-- Migration: link_parent_invites — access_code column + claim_invite_by_code
--
-- Access codes give parents a short, typeable credential (format: XXXX-XXXX)
-- for creating their account when the original invite URL is unavailable.
-- Generated by the admin side in campistry_me.js alongside the invite URL.
--
-- Parents can use EITHER:
--   • The invite URL (?invite=TOKEN)  — claim_parent_invite(p_token)
--   • The access code (XXXX-XXXX)    — claim_invite_by_code(p_code)
-- Both are idempotent for the same user.
-- ============================================================================

-- ─── 1. Add access_code column ───────────────────────────────────────────────
ALTER TABLE link_parent_invites
    ADD COLUMN IF NOT EXISTS access_code text;

-- Backfill any existing rows that don't have a code yet
UPDATE link_parent_invites
SET access_code = upper(
    substring(encode(gen_random_bytes(2), 'hex') from 1 for 4) || '-' ||
    substring(encode(gen_random_bytes(2), 'hex') from 1 for 4)
)
WHERE access_code IS NULL;

-- Unique index — case-insensitive, only for non-null values
CREATE UNIQUE INDEX IF NOT EXISTS idx_link_parent_invites_code
    ON link_parent_invites (upper(access_code))
    WHERE access_code IS NOT NULL;

-- ─── 2. RPC: claim_invite_by_code ────────────────────────────────────────────
-- Called by parent portal after signUp or signIn when parent enters their
-- access code (no invite URL needed). Idempotent for the same user.
CREATE OR REPLACE FUNCTION public.claim_invite_by_code(p_code text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
    inv    link_parent_invites;
    caller uuid := auth.uid();
BEGIN
    IF caller IS NULL THEN
        RETURN jsonb_build_object('success', false, 'error', 'not_authenticated');
    END IF;

    SELECT * INTO inv
    FROM link_parent_invites
    WHERE upper(access_code) = upper(p_code)
      AND status = 'active'
      AND (expires_at IS NULL OR expires_at > now())
    LIMIT 1;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('success', false, 'error', 'invalid_code');
    END IF;

    -- Guard: if already claimed by a DIFFERENT user, reject
    IF inv.user_id IS NOT NULL AND inv.user_id <> caller THEN
        RETURN jsonb_build_object('success', false, 'error', 'already_claimed');
    END IF;

    -- Link (idempotent — safe to call again from same user)
    UPDATE link_parent_invites
    SET user_id = caller
    WHERE id = inv.id;

    RETURN jsonb_build_object(
        'success',      true,
        'camp_id',      inv.camp_id,
        'parent_name',  inv.parent_name,
        'parent_email', inv.parent_email,
        'family_id',    inv.family_id,
        'camper_names', inv.camper_names,
        'camper_data',  inv.camper_data
    );
END;
$$;

REVOKE ALL ON FUNCTION public.claim_invite_by_code(text) FROM public;
GRANT EXECUTE ON FUNCTION public.claim_invite_by_code(text) TO authenticated;

-- ─── 3. Sanity check ──────────────────────────────────────────────────────────
-- SELECT column_name FROM information_schema.columns
-- WHERE table_name = 'link_parent_invites' AND column_name = 'access_code';
--
-- SELECT proname FROM pg_proc WHERE proname = 'claim_invite_by_code';
