-- ============================================================================
-- Migration 159: the capability registry and preset expansions, in SQL.
--
-- GENERATED FILE — do not edit by hand.
-- Rebuild with:  node scripts/build-access-registry-sql.js
--
-- Phase 3 of ENTITLEMENTS_DESIGN.md enforces a STAFF MEMBER's section access in
-- RLS. Until now that layer was browser-only: a manager with payroll:none could
-- read campistryMePayroll straight out of the table with curl. To close that,
-- the database needs the two things that only existed as JavaScript — the
-- capability registry, and what each preset expands to once '*' and 'app.*' are
-- resolved.
--
-- These tables are DERIVED DATA, not configuration. Nobody edits them; they are
-- regenerated from campistry_capabilities.js, which stays the single source of
-- truth. tests/access_registry_sql.test.js fails if this file drifts from it.
--
-- Read-only to clients: RLS denies everything and the resolver reads them as
-- SECURITY DEFINER. They are not camp data — they are the same for every camp.
--
-- Idempotent: the tables are recreated and refilled from scratch each run.
-- ============================================================================

CREATE TABLE IF NOT EXISTS access_capabilities (
    cap_key    text PRIMARY KEY,
    app        text NOT NULL,
    section    text NOT NULL,
    view_only  boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS access_preset_grants (
    preset     text NOT NULL,
    cap_key    text NOT NULL,
    level      text NOT NULL,
    -- Did the preset literally NAME this key, as opposed to inheriting the
    -- level from 'app.*' or '*'? Needed for the finance -> analytics legacy
    -- fallback in user_section_level(); see the header of the generator.
    explicit   boolean NOT NULL DEFAULT false,
    PRIMARY KEY (preset, cap_key)
);

-- Neither table is camp-scoped and neither is client-readable. The resolver is
-- SECURITY DEFINER, so it sees them regardless.
ALTER TABLE access_capabilities  ENABLE ROW LEVEL SECURITY;
ALTER TABLE access_preset_grants ENABLE ROW LEVEL SECURITY;

-- Refill from scratch, so a removed capability or preset actually disappears
-- rather than lingering and granting access to a section that no longer exists.
TRUNCATE access_preset_grants;
TRUNCATE access_capabilities;

INSERT INTO access_capabilities (cap_key, app, section, view_only) VALUES
    ('flow.camper-locator', 'flow', 'camper-locator', false),
    ('flow.daily-adjustments', 'flow', 'daily-adjustments', false),
    ('flow.facilities', 'flow', 'facilities', false),
    ('flow.leagues', 'flow', 'leagues', false),
    ('flow.master-scheduler', 'flow', 'master-scheduler', false),
    ('flow.print', 'flow', 'print', false),
    ('flow.report', 'flow', 'report', true),
    ('flow.rules', 'flow', 'rules', false),
    ('flow.schedule', 'flow', 'schedule', false),
    ('flow.setup', 'flow', 'setup', false),
    ('flow.specialty-leagues', 'flow', 'specialty-leagues', false),
    ('flow.zones', 'flow', 'zones', false),
    ('go.addresses', 'go', 'addresses', false),
    ('go.fleet', 'go', 'fleet', false),
    ('go.luggage', 'go', 'luggage', false),
    ('go.routes', 'go', 'routes', false),
    ('go.setup', 'go', 'setup', false),
    ('go.staff', 'go', 'staff', false),
    ('guard.guard', 'guard', 'guard', false),
    ('health.allergies', 'health', 'allergies', false),
    ('health.campers', 'health', 'campers', false),
    ('health.dashboard', 'health', 'dashboard', false),
    ('health.doctor', 'health', 'doctor', false),
    ('health.intake', 'health', 'intake', false),
    ('health.medications', 'health', 'medications', false),
    ('health.nighttime', 'health', 'nighttime', false),
    ('health.reports', 'health', 'reports', true),
    ('health.sick-visits', 'health', 'sick-visits', false),
    ('link.dashboard', 'link', 'dashboard', false),
    ('link.forms', 'link', 'forms', false),
    ('link.lists', 'link', 'lists', false),
    ('link.messages', 'link', 'messages', false),
    ('link.parents', 'link', 'parents', false),
    ('link.photos', 'link', 'photos', false),
    ('link.tips', 'link', 'tips', false),
    ('live.absences', 'live', 'absences', false),
    ('live.camper-locator', 'live', 'camper-locator', true),
    ('live.camper-mail', 'live', 'camper-mail', false),
    ('live.changes', 'live', 'changes', false),
    ('live.early-pickup', 'live', 'early-pickup', false),
    ('live.messages', 'live', 'messages', false),
    ('live.reports', 'live', 'reports', true),
    ('live.roll-call', 'live', 'roll-call', false),
    ('me.analytics', 'me', 'analytics', true),
    ('me.billing', 'me', 'billing', false),
    ('me.bunkbuilder', 'me', 'bunkbuilder', false),
    ('me.campers', 'me', 'campers', false),
    ('me.enrollment', 'me', 'enrollment', false),
    ('me.finance', 'me', 'finance', true),
    ('me.payroll', 'me', 'payroll', false),
    ('me.printsheets', 'me', 'printsheets', false),
    ('me.reports', 'me', 'reports', true),
    ('me.settings', 'me', 'settings', false),
    ('me.structure', 'me', 'structure', false),
    ('notes.notes', 'notes', 'notes', false),
    ('snacks.accounts', 'snacks', 'accounts', false),
    ('snacks.dashboard', 'snacks', 'dashboard', false),
    ('snacks.menu', 'snacks', 'menu', false),
    ('snacks.pos', 'snacks', 'pos', false),
    ('snacks.settings', 'snacks', 'settings', false),
    ('snacks.shop', 'snacks', 'shop', false),
    ('snacks.transactions', 'snacks', 'transactions', false);

INSERT INTO access_preset_grants (preset, cap_key, level, explicit) VALUES
    ('bookkeeper', 'flow.camper-locator', 'none', false),
    ('bookkeeper', 'flow.daily-adjustments', 'none', false),
    ('bookkeeper', 'flow.facilities', 'none', false),
    ('bookkeeper', 'flow.leagues', 'none', false),
    ('bookkeeper', 'flow.master-scheduler', 'none', false),
    ('bookkeeper', 'flow.print', 'none', false),
    ('bookkeeper', 'flow.report', 'none', false),
    ('bookkeeper', 'flow.rules', 'none', false),
    ('bookkeeper', 'flow.schedule', 'none', false),
    ('bookkeeper', 'flow.setup', 'none', false),
    ('bookkeeper', 'flow.specialty-leagues', 'none', false),
    ('bookkeeper', 'flow.zones', 'none', false),
    ('bookkeeper', 'go.addresses', 'none', false),
    ('bookkeeper', 'go.fleet', 'none', false),
    ('bookkeeper', 'go.luggage', 'none', false),
    ('bookkeeper', 'go.routes', 'none', false),
    ('bookkeeper', 'go.setup', 'none', false),
    ('bookkeeper', 'go.staff', 'none', false),
    ('bookkeeper', 'guard.guard', 'none', false),
    ('bookkeeper', 'health.allergies', 'none', false),
    ('bookkeeper', 'health.campers', 'none', false),
    ('bookkeeper', 'health.dashboard', 'none', false),
    ('bookkeeper', 'health.doctor', 'none', false),
    ('bookkeeper', 'health.intake', 'none', false),
    ('bookkeeper', 'health.medications', 'none', false),
    ('bookkeeper', 'health.nighttime', 'none', false),
    ('bookkeeper', 'health.reports', 'none', false),
    ('bookkeeper', 'health.sick-visits', 'none', false),
    ('bookkeeper', 'link.dashboard', 'none', false),
    ('bookkeeper', 'link.forms', 'none', false),
    ('bookkeeper', 'link.lists', 'none', false),
    ('bookkeeper', 'link.messages', 'none', false),
    ('bookkeeper', 'link.parents', 'none', false),
    ('bookkeeper', 'link.photos', 'none', false),
    ('bookkeeper', 'link.tips', 'none', false),
    ('bookkeeper', 'live.absences', 'none', false),
    ('bookkeeper', 'live.camper-locator', 'none', false),
    ('bookkeeper', 'live.camper-mail', 'none', false),
    ('bookkeeper', 'live.changes', 'none', false),
    ('bookkeeper', 'live.early-pickup', 'none', false),
    ('bookkeeper', 'live.messages', 'none', false),
    ('bookkeeper', 'live.reports', 'none', false),
    ('bookkeeper', 'live.roll-call', 'none', false),
    ('bookkeeper', 'me.analytics', 'view', true),
    ('bookkeeper', 'me.billing', 'edit', true),
    ('bookkeeper', 'me.bunkbuilder', 'none', false),
    ('bookkeeper', 'me.campers', 'view', true),
    ('bookkeeper', 'me.enrollment', 'none', false),
    ('bookkeeper', 'me.finance', 'view', true),
    ('bookkeeper', 'me.payroll', 'edit', true),
    ('bookkeeper', 'me.printsheets', 'none', false),
    ('bookkeeper', 'me.reports', 'view', true),
    ('bookkeeper', 'me.settings', 'none', false),
    ('bookkeeper', 'me.structure', 'none', false),
    ('bookkeeper', 'notes.notes', 'none', false),
    ('bookkeeper', 'snacks.accounts', 'view', true),
    ('bookkeeper', 'snacks.dashboard', 'none', false),
    ('bookkeeper', 'snacks.menu', 'none', false),
    ('bookkeeper', 'snacks.pos', 'none', true),
    ('bookkeeper', 'snacks.settings', 'none', false),
    ('bookkeeper', 'snacks.shop', 'none', false),
    ('bookkeeper', 'snacks.transactions', 'view', true),
    ('bunk-counselor', 'flow.camper-locator', 'view', true),
    ('bunk-counselor', 'flow.daily-adjustments', 'none', false),
    ('bunk-counselor', 'flow.facilities', 'none', false),
    ('bunk-counselor', 'flow.leagues', 'none', false),
    ('bunk-counselor', 'flow.master-scheduler', 'none', false),
    ('bunk-counselor', 'flow.print', 'none', false),
    ('bunk-counselor', 'flow.report', 'none', false),
    ('bunk-counselor', 'flow.rules', 'none', false),
    ('bunk-counselor', 'flow.schedule', 'view', true),
    ('bunk-counselor', 'flow.setup', 'none', false),
    ('bunk-counselor', 'flow.specialty-leagues', 'none', false),
    ('bunk-counselor', 'flow.zones', 'none', false),
    ('bunk-counselor', 'go.addresses', 'none', false),
    ('bunk-counselor', 'go.fleet', 'none', false),
    ('bunk-counselor', 'go.luggage', 'none', false),
    ('bunk-counselor', 'go.routes', 'none', false),
    ('bunk-counselor', 'go.setup', 'none', false),
    ('bunk-counselor', 'go.staff', 'none', false),
    ('bunk-counselor', 'guard.guard', 'none', false),
    ('bunk-counselor', 'health.allergies', 'none', false),
    ('bunk-counselor', 'health.campers', 'none', false),
    ('bunk-counselor', 'health.dashboard', 'none', false),
    ('bunk-counselor', 'health.doctor', 'none', false),
    ('bunk-counselor', 'health.intake', 'none', false),
    ('bunk-counselor', 'health.medications', 'none', false),
    ('bunk-counselor', 'health.nighttime', 'none', false),
    ('bunk-counselor', 'health.reports', 'none', false),
    ('bunk-counselor', 'health.sick-visits', 'none', false),
    ('bunk-counselor', 'link.dashboard', 'none', false),
    ('bunk-counselor', 'link.forms', 'none', false),
    ('bunk-counselor', 'link.lists', 'none', false),
    ('bunk-counselor', 'link.messages', 'none', false),
    ('bunk-counselor', 'link.parents', 'none', false),
    ('bunk-counselor', 'link.photos', 'none', false),
    ('bunk-counselor', 'link.tips', 'none', false),
    ('bunk-counselor', 'live.absences', 'edit', false),
    ('bunk-counselor', 'live.camper-locator', 'view', false),
    ('bunk-counselor', 'live.camper-mail', 'edit', false),
    ('bunk-counselor', 'live.changes', 'edit', false),
    ('bunk-counselor', 'live.early-pickup', 'edit', false),
    ('bunk-counselor', 'live.messages', 'edit', false),
    ('bunk-counselor', 'live.reports', 'view', false),
    ('bunk-counselor', 'live.roll-call', 'edit', false),
    ('bunk-counselor', 'me.analytics', 'none', false),
    ('bunk-counselor', 'me.billing', 'none', false),
    ('bunk-counselor', 'me.bunkbuilder', 'none', false),
    ('bunk-counselor', 'me.campers', 'view', true),
    ('bunk-counselor', 'me.enrollment', 'none', false),
    ('bunk-counselor', 'me.finance', 'none', false),
    ('bunk-counselor', 'me.payroll', 'none', false),
    ('bunk-counselor', 'me.printsheets', 'none', false),
    ('bunk-counselor', 'me.reports', 'none', false),
    ('bunk-counselor', 'me.settings', 'none', false),
    ('bunk-counselor', 'me.structure', 'none', false),
    ('bunk-counselor', 'notes.notes', 'edit', true),
    ('bunk-counselor', 'snacks.accounts', 'none', false),
    ('bunk-counselor', 'snacks.dashboard', 'none', false),
    ('bunk-counselor', 'snacks.menu', 'none', false),
    ('bunk-counselor', 'snacks.pos', 'none', false),
    ('bunk-counselor', 'snacks.settings', 'none', false),
    ('bunk-counselor', 'snacks.shop', 'none', false),
    ('bunk-counselor', 'snacks.transactions', 'none', false),
    ('bus-coordinator', 'flow.camper-locator', 'none', false),
    ('bus-coordinator', 'flow.daily-adjustments', 'none', false),
    ('bus-coordinator', 'flow.facilities', 'none', false),
    ('bus-coordinator', 'flow.leagues', 'none', false),
    ('bus-coordinator', 'flow.master-scheduler', 'none', false),
    ('bus-coordinator', 'flow.print', 'none', false),
    ('bus-coordinator', 'flow.report', 'none', false),
    ('bus-coordinator', 'flow.rules', 'none', false),
    ('bus-coordinator', 'flow.schedule', 'none', false),
    ('bus-coordinator', 'flow.setup', 'none', false),
    ('bus-coordinator', 'flow.specialty-leagues', 'none', false),
    ('bus-coordinator', 'flow.zones', 'none', false),
    ('bus-coordinator', 'go.addresses', 'edit', false),
    ('bus-coordinator', 'go.fleet', 'edit', false),
    ('bus-coordinator', 'go.luggage', 'edit', false),
    ('bus-coordinator', 'go.routes', 'edit', false),
    ('bus-coordinator', 'go.setup', 'edit', false),
    ('bus-coordinator', 'go.staff', 'edit', false),
    ('bus-coordinator', 'guard.guard', 'none', false),
    ('bus-coordinator', 'health.allergies', 'none', false),
    ('bus-coordinator', 'health.campers', 'none', false),
    ('bus-coordinator', 'health.dashboard', 'none', false),
    ('bus-coordinator', 'health.doctor', 'none', false),
    ('bus-coordinator', 'health.intake', 'none', false),
    ('bus-coordinator', 'health.medications', 'none', false),
    ('bus-coordinator', 'health.nighttime', 'none', false),
    ('bus-coordinator', 'health.reports', 'none', false),
    ('bus-coordinator', 'health.sick-visits', 'none', false),
    ('bus-coordinator', 'link.dashboard', 'none', false),
    ('bus-coordinator', 'link.forms', 'none', false),
    ('bus-coordinator', 'link.lists', 'none', false),
    ('bus-coordinator', 'link.messages', 'none', false),
    ('bus-coordinator', 'link.parents', 'none', false),
    ('bus-coordinator', 'link.photos', 'none', false),
    ('bus-coordinator', 'link.tips', 'none', false),
    ('bus-coordinator', 'live.absences', 'none', false),
    ('bus-coordinator', 'live.camper-locator', 'none', false),
    ('bus-coordinator', 'live.camper-mail', 'none', false),
    ('bus-coordinator', 'live.changes', 'none', false),
    ('bus-coordinator', 'live.early-pickup', 'none', false),
    ('bus-coordinator', 'live.messages', 'none', false),
    ('bus-coordinator', 'live.reports', 'none', false),
    ('bus-coordinator', 'live.roll-call', 'none', false),
    ('bus-coordinator', 'me.analytics', 'none', false),
    ('bus-coordinator', 'me.billing', 'none', false),
    ('bus-coordinator', 'me.bunkbuilder', 'none', false),
    ('bus-coordinator', 'me.campers', 'view', true),
    ('bus-coordinator', 'me.enrollment', 'none', false),
    ('bus-coordinator', 'me.finance', 'none', false),
    ('bus-coordinator', 'me.payroll', 'none', false),
    ('bus-coordinator', 'me.printsheets', 'none', false),
    ('bus-coordinator', 'me.reports', 'none', false),
    ('bus-coordinator', 'me.settings', 'none', false),
    ('bus-coordinator', 'me.structure', 'none', false),
    ('bus-coordinator', 'notes.notes', 'edit', true),
    ('bus-coordinator', 'snacks.accounts', 'none', false),
    ('bus-coordinator', 'snacks.dashboard', 'none', false),
    ('bus-coordinator', 'snacks.menu', 'none', false),
    ('bus-coordinator', 'snacks.pos', 'none', false),
    ('bus-coordinator', 'snacks.settings', 'none', false),
    ('bus-coordinator', 'snacks.shop', 'none', false),
    ('bus-coordinator', 'snacks.transactions', 'none', false),
    ('canteen', 'flow.camper-locator', 'none', false),
    ('canteen', 'flow.daily-adjustments', 'none', false),
    ('canteen', 'flow.facilities', 'none', false),
    ('canteen', 'flow.leagues', 'none', false),
    ('canteen', 'flow.master-scheduler', 'none', false),
    ('canteen', 'flow.print', 'none', false),
    ('canteen', 'flow.report', 'none', false),
    ('canteen', 'flow.rules', 'none', false),
    ('canteen', 'flow.schedule', 'none', false),
    ('canteen', 'flow.setup', 'none', false),
    ('canteen', 'flow.specialty-leagues', 'none', false),
    ('canteen', 'flow.zones', 'none', false),
    ('canteen', 'go.addresses', 'none', false),
    ('canteen', 'go.fleet', 'none', false),
    ('canteen', 'go.luggage', 'none', false),
    ('canteen', 'go.routes', 'none', false),
    ('canteen', 'go.setup', 'none', false),
    ('canteen', 'go.staff', 'none', false),
    ('canteen', 'guard.guard', 'none', false),
    ('canteen', 'health.allergies', 'none', false),
    ('canteen', 'health.campers', 'none', false),
    ('canteen', 'health.dashboard', 'none', false),
    ('canteen', 'health.doctor', 'none', false),
    ('canteen', 'health.intake', 'none', false),
    ('canteen', 'health.medications', 'none', false),
    ('canteen', 'health.nighttime', 'none', false),
    ('canteen', 'health.reports', 'none', false),
    ('canteen', 'health.sick-visits', 'none', false),
    ('canteen', 'link.dashboard', 'none', false),
    ('canteen', 'link.forms', 'none', false),
    ('canteen', 'link.lists', 'none', false),
    ('canteen', 'link.messages', 'none', false),
    ('canteen', 'link.parents', 'none', false),
    ('canteen', 'link.photos', 'none', false),
    ('canteen', 'link.tips', 'none', false),
    ('canteen', 'live.absences', 'none', false),
    ('canteen', 'live.camper-locator', 'none', false),
    ('canteen', 'live.camper-mail', 'none', false),
    ('canteen', 'live.changes', 'none', false),
    ('canteen', 'live.early-pickup', 'none', false),
    ('canteen', 'live.messages', 'none', false),
    ('canteen', 'live.reports', 'none', false),
    ('canteen', 'live.roll-call', 'none', false),
    ('canteen', 'me.analytics', 'none', false),
    ('canteen', 'me.billing', 'none', false),
    ('canteen', 'me.bunkbuilder', 'none', false),
    ('canteen', 'me.campers', 'view', true),
    ('canteen', 'me.enrollment', 'none', false),
    ('canteen', 'me.finance', 'none', false),
    ('canteen', 'me.payroll', 'none', false),
    ('canteen', 'me.printsheets', 'none', false),
    ('canteen', 'me.reports', 'none', false),
    ('canteen', 'me.settings', 'none', false),
    ('canteen', 'me.structure', 'none', false),
    ('canteen', 'notes.notes', 'none', false),
    ('canteen', 'snacks.accounts', 'edit', false),
    ('canteen', 'snacks.dashboard', 'edit', false),
    ('canteen', 'snacks.menu', 'edit', false),
    ('canteen', 'snacks.pos', 'edit', false),
    ('canteen', 'snacks.settings', 'edit', false),
    ('canteen', 'snacks.shop', 'edit', false),
    ('canteen', 'snacks.transactions', 'edit', false),
    ('division-head', 'flow.camper-locator', 'view', true),
    ('division-head', 'flow.daily-adjustments', 'edit', true),
    ('division-head', 'flow.facilities', 'none', false),
    ('division-head', 'flow.leagues', 'none', false),
    ('division-head', 'flow.master-scheduler', 'none', false),
    ('division-head', 'flow.print', 'edit', true),
    ('division-head', 'flow.report', 'view', true),
    ('division-head', 'flow.rules', 'none', false),
    ('division-head', 'flow.schedule', 'view', true),
    ('division-head', 'flow.setup', 'none', false),
    ('division-head', 'flow.specialty-leagues', 'none', false),
    ('division-head', 'flow.zones', 'none', false),
    ('division-head', 'go.addresses', 'none', false),
    ('division-head', 'go.fleet', 'none', false),
    ('division-head', 'go.luggage', 'none', false),
    ('division-head', 'go.routes', 'none', false),
    ('division-head', 'go.setup', 'none', false),
    ('division-head', 'go.staff', 'none', false),
    ('division-head', 'guard.guard', 'none', false),
    ('division-head', 'health.allergies', 'none', false),
    ('division-head', 'health.campers', 'none', false),
    ('division-head', 'health.dashboard', 'none', false),
    ('division-head', 'health.doctor', 'none', false),
    ('division-head', 'health.intake', 'none', false),
    ('division-head', 'health.medications', 'none', false),
    ('division-head', 'health.nighttime', 'none', false),
    ('division-head', 'health.reports', 'none', false),
    ('division-head', 'health.sick-visits', 'none', false),
    ('division-head', 'link.dashboard', 'none', false),
    ('division-head', 'link.forms', 'none', false),
    ('division-head', 'link.lists', 'none', false),
    ('division-head', 'link.messages', 'none', false),
    ('division-head', 'link.parents', 'none', false),
    ('division-head', 'link.photos', 'none', false),
    ('division-head', 'link.tips', 'none', false),
    ('division-head', 'live.absences', 'edit', false),
    ('division-head', 'live.camper-locator', 'view', false),
    ('division-head', 'live.camper-mail', 'edit', false),
    ('division-head', 'live.changes', 'edit', false),
    ('division-head', 'live.early-pickup', 'edit', false),
    ('division-head', 'live.messages', 'edit', false),
    ('division-head', 'live.reports', 'view', false),
    ('division-head', 'live.roll-call', 'edit', false),
    ('division-head', 'me.analytics', 'none', false),
    ('division-head', 'me.billing', 'none', false),
    ('division-head', 'me.bunkbuilder', 'edit', true),
    ('division-head', 'me.campers', 'view', true),
    ('division-head', 'me.enrollment', 'none', false),
    ('division-head', 'me.finance', 'none', false),
    ('division-head', 'me.payroll', 'none', false),
    ('division-head', 'me.printsheets', 'edit', true),
    ('division-head', 'me.reports', 'view', true),
    ('division-head', 'me.settings', 'none', false),
    ('division-head', 'me.structure', 'view', true),
    ('division-head', 'notes.notes', 'edit', true),
    ('division-head', 'snacks.accounts', 'none', false),
    ('division-head', 'snacks.dashboard', 'none', false),
    ('division-head', 'snacks.menu', 'none', false),
    ('division-head', 'snacks.pos', 'none', false),
    ('division-head', 'snacks.settings', 'none', false),
    ('division-head', 'snacks.shop', 'none', false),
    ('division-head', 'snacks.transactions', 'none', false),
    ('full', 'flow.camper-locator', 'edit', false),
    ('full', 'flow.daily-adjustments', 'edit', false),
    ('full', 'flow.facilities', 'edit', false),
    ('full', 'flow.leagues', 'edit', false),
    ('full', 'flow.master-scheduler', 'edit', false),
    ('full', 'flow.print', 'edit', false),
    ('full', 'flow.report', 'view', false),
    ('full', 'flow.rules', 'edit', false),
    ('full', 'flow.schedule', 'edit', false),
    ('full', 'flow.setup', 'edit', false),
    ('full', 'flow.specialty-leagues', 'edit', false),
    ('full', 'flow.zones', 'edit', false),
    ('full', 'go.addresses', 'edit', false),
    ('full', 'go.fleet', 'edit', false),
    ('full', 'go.luggage', 'edit', false),
    ('full', 'go.routes', 'edit', false),
    ('full', 'go.setup', 'edit', false),
    ('full', 'go.staff', 'edit', false),
    ('full', 'guard.guard', 'edit', false),
    ('full', 'health.allergies', 'edit', false),
    ('full', 'health.campers', 'edit', false),
    ('full', 'health.dashboard', 'edit', false),
    ('full', 'health.doctor', 'edit', false),
    ('full', 'health.intake', 'edit', false),
    ('full', 'health.medications', 'edit', false),
    ('full', 'health.nighttime', 'edit', false),
    ('full', 'health.reports', 'view', false),
    ('full', 'health.sick-visits', 'edit', false),
    ('full', 'link.dashboard', 'edit', false),
    ('full', 'link.forms', 'edit', false),
    ('full', 'link.lists', 'edit', false),
    ('full', 'link.messages', 'edit', false),
    ('full', 'link.parents', 'edit', false),
    ('full', 'link.photos', 'edit', false),
    ('full', 'link.tips', 'edit', false),
    ('full', 'live.absences', 'edit', false),
    ('full', 'live.camper-locator', 'view', false),
    ('full', 'live.camper-mail', 'edit', false),
    ('full', 'live.changes', 'edit', false),
    ('full', 'live.early-pickup', 'edit', false),
    ('full', 'live.messages', 'edit', false),
    ('full', 'live.reports', 'view', false),
    ('full', 'live.roll-call', 'edit', false),
    ('full', 'me.analytics', 'view', false),
    ('full', 'me.billing', 'edit', false),
    ('full', 'me.bunkbuilder', 'edit', false),
    ('full', 'me.campers', 'edit', false),
    ('full', 'me.enrollment', 'edit', false),
    ('full', 'me.finance', 'view', false),
    ('full', 'me.payroll', 'edit', false),
    ('full', 'me.printsheets', 'edit', false),
    ('full', 'me.reports', 'view', false),
    ('full', 'me.settings', 'edit', false),
    ('full', 'me.structure', 'edit', false),
    ('full', 'notes.notes', 'edit', false),
    ('full', 'snacks.accounts', 'edit', false),
    ('full', 'snacks.dashboard', 'edit', false),
    ('full', 'snacks.menu', 'edit', false),
    ('full', 'snacks.pos', 'edit', false),
    ('full', 'snacks.settings', 'edit', false),
    ('full', 'snacks.shop', 'edit', false),
    ('full', 'snacks.transactions', 'edit', false),
    ('gatehouse', 'flow.camper-locator', 'none', false),
    ('gatehouse', 'flow.daily-adjustments', 'none', false),
    ('gatehouse', 'flow.facilities', 'none', false),
    ('gatehouse', 'flow.leagues', 'none', false),
    ('gatehouse', 'flow.master-scheduler', 'none', false),
    ('gatehouse', 'flow.print', 'none', false),
    ('gatehouse', 'flow.report', 'none', false),
    ('gatehouse', 'flow.rules', 'none', false),
    ('gatehouse', 'flow.schedule', 'none', false),
    ('gatehouse', 'flow.setup', 'none', false),
    ('gatehouse', 'flow.specialty-leagues', 'none', false),
    ('gatehouse', 'flow.zones', 'none', false),
    ('gatehouse', 'go.addresses', 'none', false),
    ('gatehouse', 'go.fleet', 'none', false),
    ('gatehouse', 'go.luggage', 'none', false),
    ('gatehouse', 'go.routes', 'none', false),
    ('gatehouse', 'go.setup', 'none', false),
    ('gatehouse', 'go.staff', 'none', false),
    ('gatehouse', 'guard.guard', 'edit', false),
    ('gatehouse', 'health.allergies', 'none', false),
    ('gatehouse', 'health.campers', 'none', false),
    ('gatehouse', 'health.dashboard', 'none', false),
    ('gatehouse', 'health.doctor', 'none', false),
    ('gatehouse', 'health.intake', 'none', false),
    ('gatehouse', 'health.medications', 'none', false),
    ('gatehouse', 'health.nighttime', 'none', false),
    ('gatehouse', 'health.reports', 'none', false),
    ('gatehouse', 'health.sick-visits', 'none', false),
    ('gatehouse', 'link.dashboard', 'none', false),
    ('gatehouse', 'link.forms', 'none', false),
    ('gatehouse', 'link.lists', 'none', false),
    ('gatehouse', 'link.messages', 'none', false),
    ('gatehouse', 'link.parents', 'none', false),
    ('gatehouse', 'link.photos', 'none', false),
    ('gatehouse', 'link.tips', 'none', false),
    ('gatehouse', 'live.absences', 'none', false),
    ('gatehouse', 'live.camper-locator', 'view', true),
    ('gatehouse', 'live.camper-mail', 'none', false),
    ('gatehouse', 'live.changes', 'none', false),
    ('gatehouse', 'live.early-pickup', 'edit', true),
    ('gatehouse', 'live.messages', 'none', false),
    ('gatehouse', 'live.reports', 'none', false),
    ('gatehouse', 'live.roll-call', 'none', false),
    ('gatehouse', 'me.analytics', 'none', false),
    ('gatehouse', 'me.billing', 'none', false),
    ('gatehouse', 'me.bunkbuilder', 'none', false),
    ('gatehouse', 'me.campers', 'view', true),
    ('gatehouse', 'me.enrollment', 'none', false),
    ('gatehouse', 'me.finance', 'none', false),
    ('gatehouse', 'me.payroll', 'none', false),
    ('gatehouse', 'me.printsheets', 'none', false),
    ('gatehouse', 'me.reports', 'none', false),
    ('gatehouse', 'me.settings', 'none', false),
    ('gatehouse', 'me.structure', 'none', false),
    ('gatehouse', 'notes.notes', 'none', false),
    ('gatehouse', 'snacks.accounts', 'none', false),
    ('gatehouse', 'snacks.dashboard', 'none', false),
    ('gatehouse', 'snacks.menu', 'none', false),
    ('gatehouse', 'snacks.pos', 'none', false),
    ('gatehouse', 'snacks.settings', 'none', false),
    ('gatehouse', 'snacks.shop', 'none', false),
    ('gatehouse', 'snacks.transactions', 'none', false),
    ('head-counselor', 'flow.camper-locator', 'edit', false),
    ('head-counselor', 'flow.daily-adjustments', 'edit', false),
    ('head-counselor', 'flow.facilities', 'edit', false),
    ('head-counselor', 'flow.leagues', 'edit', false),
    ('head-counselor', 'flow.master-scheduler', 'edit', false),
    ('head-counselor', 'flow.print', 'edit', false),
    ('head-counselor', 'flow.report', 'view', false),
    ('head-counselor', 'flow.rules', 'edit', false),
    ('head-counselor', 'flow.schedule', 'edit', false),
    ('head-counselor', 'flow.setup', 'edit', false),
    ('head-counselor', 'flow.specialty-leagues', 'edit', false),
    ('head-counselor', 'flow.zones', 'edit', false),
    ('head-counselor', 'go.addresses', 'none', false),
    ('head-counselor', 'go.fleet', 'none', false),
    ('head-counselor', 'go.luggage', 'none', false),
    ('head-counselor', 'go.routes', 'none', false),
    ('head-counselor', 'go.setup', 'none', false),
    ('head-counselor', 'go.staff', 'none', false),
    ('head-counselor', 'guard.guard', 'none', false),
    ('head-counselor', 'health.allergies', 'none', false),
    ('head-counselor', 'health.campers', 'none', false),
    ('head-counselor', 'health.dashboard', 'none', false),
    ('head-counselor', 'health.doctor', 'none', false),
    ('head-counselor', 'health.intake', 'none', false),
    ('head-counselor', 'health.medications', 'none', false),
    ('head-counselor', 'health.nighttime', 'none', false),
    ('head-counselor', 'health.reports', 'none', false),
    ('head-counselor', 'health.sick-visits', 'none', false),
    ('head-counselor', 'link.dashboard', 'none', false),
    ('head-counselor', 'link.forms', 'none', false),
    ('head-counselor', 'link.lists', 'none', false),
    ('head-counselor', 'link.messages', 'none', false),
    ('head-counselor', 'link.parents', 'none', false),
    ('head-counselor', 'link.photos', 'none', false),
    ('head-counselor', 'link.tips', 'none', false),
    ('head-counselor', 'live.absences', 'edit', false),
    ('head-counselor', 'live.camper-locator', 'view', false),
    ('head-counselor', 'live.camper-mail', 'edit', false),
    ('head-counselor', 'live.changes', 'edit', false),
    ('head-counselor', 'live.early-pickup', 'edit', false),
    ('head-counselor', 'live.messages', 'edit', false),
    ('head-counselor', 'live.reports', 'view', false),
    ('head-counselor', 'live.roll-call', 'edit', false),
    ('head-counselor', 'me.analytics', 'none', false),
    ('head-counselor', 'me.billing', 'none', false),
    ('head-counselor', 'me.bunkbuilder', 'edit', true),
    ('head-counselor', 'me.campers', 'view', true),
    ('head-counselor', 'me.enrollment', 'none', false),
    ('head-counselor', 'me.finance', 'none', false),
    ('head-counselor', 'me.payroll', 'none', false),
    ('head-counselor', 'me.printsheets', 'edit', true),
    ('head-counselor', 'me.reports', 'view', true),
    ('head-counselor', 'me.settings', 'none', false),
    ('head-counselor', 'me.structure', 'view', true),
    ('head-counselor', 'notes.notes', 'edit', true),
    ('head-counselor', 'snacks.accounts', 'none', false),
    ('head-counselor', 'snacks.dashboard', 'none', false),
    ('head-counselor', 'snacks.menu', 'none', false),
    ('head-counselor', 'snacks.pos', 'none', false),
    ('head-counselor', 'snacks.settings', 'none', false),
    ('head-counselor', 'snacks.shop', 'none', false),
    ('head-counselor', 'snacks.transactions', 'none', false),
    ('nurse', 'flow.camper-locator', 'none', false),
    ('nurse', 'flow.daily-adjustments', 'none', false),
    ('nurse', 'flow.facilities', 'none', false),
    ('nurse', 'flow.leagues', 'none', false),
    ('nurse', 'flow.master-scheduler', 'none', false),
    ('nurse', 'flow.print', 'none', false),
    ('nurse', 'flow.report', 'none', false),
    ('nurse', 'flow.rules', 'none', false),
    ('nurse', 'flow.schedule', 'none', false),
    ('nurse', 'flow.setup', 'none', false),
    ('nurse', 'flow.specialty-leagues', 'none', false),
    ('nurse', 'flow.zones', 'none', false),
    ('nurse', 'go.addresses', 'none', false),
    ('nurse', 'go.fleet', 'none', false),
    ('nurse', 'go.luggage', 'none', false),
    ('nurse', 'go.routes', 'none', false),
    ('nurse', 'go.setup', 'none', false),
    ('nurse', 'go.staff', 'none', false),
    ('nurse', 'guard.guard', 'none', false),
    ('nurse', 'health.allergies', 'edit', false),
    ('nurse', 'health.campers', 'edit', false),
    ('nurse', 'health.dashboard', 'edit', false),
    ('nurse', 'health.doctor', 'edit', false),
    ('nurse', 'health.intake', 'edit', false),
    ('nurse', 'health.medications', 'edit', false),
    ('nurse', 'health.nighttime', 'edit', false),
    ('nurse', 'health.reports', 'view', false),
    ('nurse', 'health.sick-visits', 'edit', false),
    ('nurse', 'link.dashboard', 'none', false),
    ('nurse', 'link.forms', 'none', false),
    ('nurse', 'link.lists', 'none', false),
    ('nurse', 'link.messages', 'none', false),
    ('nurse', 'link.parents', 'none', false),
    ('nurse', 'link.photos', 'none', false),
    ('nurse', 'link.tips', 'none', false),
    ('nurse', 'live.absences', 'none', false),
    ('nurse', 'live.camper-locator', 'none', false),
    ('nurse', 'live.camper-mail', 'none', false),
    ('nurse', 'live.changes', 'none', false),
    ('nurse', 'live.early-pickup', 'none', false),
    ('nurse', 'live.messages', 'none', false),
    ('nurse', 'live.reports', 'none', false),
    ('nurse', 'live.roll-call', 'none', false),
    ('nurse', 'me.analytics', 'none', false),
    ('nurse', 'me.billing', 'none', false),
    ('nurse', 'me.bunkbuilder', 'none', false),
    ('nurse', 'me.campers', 'view', true),
    ('nurse', 'me.enrollment', 'none', false),
    ('nurse', 'me.finance', 'none', false),
    ('nurse', 'me.payroll', 'none', false),
    ('nurse', 'me.printsheets', 'none', false),
    ('nurse', 'me.reports', 'none', false),
    ('nurse', 'me.settings', 'none', false),
    ('nurse', 'me.structure', 'none', false),
    ('nurse', 'notes.notes', 'edit', true),
    ('nurse', 'snacks.accounts', 'none', false),
    ('nurse', 'snacks.dashboard', 'none', false),
    ('nurse', 'snacks.menu', 'none', false),
    ('nurse', 'snacks.pos', 'none', false),
    ('nurse', 'snacks.settings', 'none', false),
    ('nurse', 'snacks.shop', 'none', false),
    ('nurse', 'snacks.transactions', 'none', false),
    ('office', 'flow.camper-locator', 'none', false),
    ('office', 'flow.daily-adjustments', 'none', false),
    ('office', 'flow.facilities', 'none', false),
    ('office', 'flow.leagues', 'none', false),
    ('office', 'flow.master-scheduler', 'none', false),
    ('office', 'flow.print', 'none', false),
    ('office', 'flow.report', 'none', false),
    ('office', 'flow.rules', 'none', false),
    ('office', 'flow.schedule', 'none', false),
    ('office', 'flow.setup', 'none', false),
    ('office', 'flow.specialty-leagues', 'none', false),
    ('office', 'flow.zones', 'none', false),
    ('office', 'go.addresses', 'none', false),
    ('office', 'go.fleet', 'none', false),
    ('office', 'go.luggage', 'none', false),
    ('office', 'go.routes', 'none', false),
    ('office', 'go.setup', 'none', false),
    ('office', 'go.staff', 'none', false),
    ('office', 'guard.guard', 'none', false),
    ('office', 'health.allergies', 'none', false),
    ('office', 'health.campers', 'none', false),
    ('office', 'health.dashboard', 'none', false),
    ('office', 'health.doctor', 'none', false),
    ('office', 'health.intake', 'none', false),
    ('office', 'health.medications', 'none', false),
    ('office', 'health.nighttime', 'none', false),
    ('office', 'health.reports', 'none', false),
    ('office', 'health.sick-visits', 'none', false),
    ('office', 'link.dashboard', 'edit', false),
    ('office', 'link.forms', 'edit', false),
    ('office', 'link.lists', 'edit', false),
    ('office', 'link.messages', 'edit', false),
    ('office', 'link.parents', 'edit', false),
    ('office', 'link.photos', 'edit', false),
    ('office', 'link.tips', 'edit', false),
    ('office', 'live.absences', 'none', false),
    ('office', 'live.camper-locator', 'none', false),
    ('office', 'live.camper-mail', 'none', false),
    ('office', 'live.changes', 'none', false),
    ('office', 'live.early-pickup', 'none', false),
    ('office', 'live.messages', 'none', false),
    ('office', 'live.reports', 'none', false),
    ('office', 'live.roll-call', 'none', false),
    ('office', 'me.analytics', 'none', false),
    ('office', 'me.billing', 'edit', true),
    ('office', 'me.bunkbuilder', 'none', false),
    ('office', 'me.campers', 'edit', true),
    ('office', 'me.enrollment', 'edit', true),
    ('office', 'me.finance', 'none', false),
    ('office', 'me.payroll', 'none', false),
    ('office', 'me.printsheets', 'edit', true),
    ('office', 'me.reports', 'view', true),
    ('office', 'me.settings', 'none', false),
    ('office', 'me.structure', 'view', true),
    ('office', 'notes.notes', 'edit', true),
    ('office', 'snacks.accounts', 'none', false),
    ('office', 'snacks.dashboard', 'none', false),
    ('office', 'snacks.menu', 'none', false),
    ('office', 'snacks.pos', 'none', false),
    ('office', 'snacks.settings', 'none', false),
    ('office', 'snacks.shop', 'none', false),
    ('office', 'snacks.transactions', 'none', false),
    ('read-only', 'flow.camper-locator', 'view', false),
    ('read-only', 'flow.daily-adjustments', 'view', false),
    ('read-only', 'flow.facilities', 'view', false),
    ('read-only', 'flow.leagues', 'view', false),
    ('read-only', 'flow.master-scheduler', 'view', false),
    ('read-only', 'flow.print', 'view', false),
    ('read-only', 'flow.report', 'view', false),
    ('read-only', 'flow.rules', 'view', false),
    ('read-only', 'flow.schedule', 'view', false),
    ('read-only', 'flow.setup', 'view', false),
    ('read-only', 'flow.specialty-leagues', 'view', false),
    ('read-only', 'flow.zones', 'view', false),
    ('read-only', 'go.addresses', 'view', false),
    ('read-only', 'go.fleet', 'view', false),
    ('read-only', 'go.luggage', 'view', false),
    ('read-only', 'go.routes', 'view', false),
    ('read-only', 'go.setup', 'view', false),
    ('read-only', 'go.staff', 'view', false),
    ('read-only', 'guard.guard', 'view', false),
    ('read-only', 'health.allergies', 'view', false),
    ('read-only', 'health.campers', 'view', false),
    ('read-only', 'health.dashboard', 'view', false),
    ('read-only', 'health.doctor', 'view', false),
    ('read-only', 'health.intake', 'view', false),
    ('read-only', 'health.medications', 'view', false),
    ('read-only', 'health.nighttime', 'view', false),
    ('read-only', 'health.reports', 'view', false),
    ('read-only', 'health.sick-visits', 'view', false),
    ('read-only', 'link.dashboard', 'view', false),
    ('read-only', 'link.forms', 'view', false),
    ('read-only', 'link.lists', 'view', false),
    ('read-only', 'link.messages', 'view', false),
    ('read-only', 'link.parents', 'view', false),
    ('read-only', 'link.photos', 'view', false),
    ('read-only', 'link.tips', 'view', false),
    ('read-only', 'live.absences', 'view', false),
    ('read-only', 'live.camper-locator', 'view', false),
    ('read-only', 'live.camper-mail', 'view', false),
    ('read-only', 'live.changes', 'view', false),
    ('read-only', 'live.early-pickup', 'view', false),
    ('read-only', 'live.messages', 'view', false),
    ('read-only', 'live.reports', 'view', false),
    ('read-only', 'live.roll-call', 'view', false),
    ('read-only', 'me.analytics', 'view', false),
    ('read-only', 'me.billing', 'view', false),
    ('read-only', 'me.bunkbuilder', 'view', false),
    ('read-only', 'me.campers', 'view', false),
    ('read-only', 'me.enrollment', 'view', false),
    ('read-only', 'me.finance', 'view', false),
    ('read-only', 'me.payroll', 'view', false),
    ('read-only', 'me.printsheets', 'view', false),
    ('read-only', 'me.reports', 'view', false),
    ('read-only', 'me.settings', 'view', false),
    ('read-only', 'me.structure', 'view', false),
    ('read-only', 'notes.notes', 'view', false),
    ('read-only', 'snacks.accounts', 'view', false),
    ('read-only', 'snacks.dashboard', 'view', false),
    ('read-only', 'snacks.menu', 'view', false),
    ('read-only', 'snacks.pos', 'view', false),
    ('read-only', 'snacks.settings', 'view', false),
    ('read-only', 'snacks.shop', 'view', false),
    ('read-only', 'snacks.transactions', 'view', false);

-- ─── Verification ──────────────────────────────────────────────────────────
--   select count(*) from access_capabilities;    -- expect 62
--   select count(*) from access_preset_grants;   -- expect 682
--
-- Resolved levels for the two capabilities phase 3 gates, straight from the
-- JavaScript resolver. After applying 160, user_section_level() must agree with
-- every line of this:
--   me.payroll  role=owner    (no preset)        -> edit
--   me.payroll  role=admin    (no preset)        -> edit
--   me.payroll  role=manager  preset=bookkeeper       -> edit
--   me.payroll  role=manager  preset=bunk-counselor   -> none
--   me.payroll  role=manager  preset=bus-coordinator  -> none
--   me.payroll  role=manager  preset=canteen          -> none
--   me.payroll  role=manager  preset=division-head    -> none
--   me.payroll  role=manager  preset=full             -> edit
--   me.payroll  role=manager  preset=gatehouse        -> none
--   me.payroll  role=manager  preset=head-counselor   -> none
--   me.payroll  role=manager  preset=nurse            -> none
--   me.payroll  role=manager  preset=office           -> none
--   me.payroll  role=manager  preset=read-only        -> view
--   me.finance  role=owner    (no preset)        -> view
--   me.finance  role=admin    (no preset)        -> view
--   me.finance  role=manager  preset=bookkeeper       -> view
--   me.finance  role=manager  preset=bunk-counselor   -> none
--   me.finance  role=manager  preset=bus-coordinator  -> none
--   me.finance  role=manager  preset=canteen          -> none
--   me.finance  role=manager  preset=division-head    -> none
--   me.finance  role=manager  preset=full             -> view
--   me.finance  role=manager  preset=gatehouse        -> none
--   me.finance  role=manager  preset=head-counselor   -> none
--   me.finance  role=manager  preset=nurse            -> none
--   me.finance  role=manager  preset=office           -> none
--   me.finance  role=manager  preset=read-only        -> view
--
-- NOTE 'me.finance' never exceeds 'view' for ANYONE, the owner included — it is
-- flagged view-only in the registry. That is why migration 160 gates writes on
-- "not none" rather than "edit": gating on edit would make Finance permanently
-- unsaveable for every user in every camp.
-- ============================================================================
