-- ============================================================================
-- Migration 181: a payment plan created today is a LEDGER plan, so everything
-- built for ledger plans actually runs.
--
-- Standalone — not in APPLY_BUNDLE.sql. Paste this file on its own. Idempotent.
--
-- ── THE PROBLEM ────────────────────────────────────────────────────────────
-- 172 replaced the frozen-instalment model with a derived one: a plan stores
-- WHEN and HOW MANY, and the amount is worked out at charge time from what is
-- actually still owed. 179 added dunning on top — an attempt count, a backoff,
-- an escalation after three failures.
--
-- Both live on the same branch of charge-due-installments:
--
--     const ledgerPlans = (...).filter((p) => p && Array.isArray(p.dueDates));
--
-- And nothing created a plan with dueDates. set_my_payment_plan — the only
-- thing in the app that creates a plan — wrote `installments`, the legacy
-- frozen shape. BillingCore.newPlan(), which does produce dueDates, is called
-- by nothing outside its own tests. convert_family_ledgers only converts plans
-- that ALREADY EXIST; it does not change what new ones look like.
--
-- So every plan anyone made went down the legacy branch, where:
--   * the amount stays frozen at what was owed the day the plan was built —
--     the exact thing the derived model exists to stop;
--   * a declined instalment is written status:'failed', and the legacy loop
--     does `if (inst.status !== "pending") continue`. It is never retried,
--     never flagged, and raises no notification. One decline and that
--     instalment is gone;
--   * none of 179's dunning runs at all.
--
-- ── THE CHANGE, AND ITS LIMITS ─────────────────────────────────────────────
-- 117's function with ONE edit: the shape written at the end. Every guard is
-- untouched — the invite check, self-serve-enabled, the balance target, the
-- one-plan-per-family rule, the 1..60 count, and the total_mismatch check that
-- stops a plan being built which quietly collects less than is owed.
--
-- The per-instalment amounts are still required and still validated against the
-- balance. They are then DISCARDED rather than stored. `total` is kept as a
-- snapshot for display — "you set up a $3,000 plan" — and is never what gets
-- charged; plan_due decides that from the balance.
--
-- This file was generated by patching 117's own source rather than retyping it,
-- because reproducing a working function from memory is how a vault secret name
-- and three column names got silently changed earlier in this project.
--
-- ── WHAT IS DELIBERATELY NOT DONE ──────────────────────────────────────────
-- Existing legacy plans are LEFT ALONE. Rewriting a live plan's shape underneath
-- a family mid-season is a bigger risk than the one being fixed, and
-- convert_family_ledgers already exists for camps that want to move. The legacy
-- branch of the runner stays where it is and keeps working.
--
-- So: a camp with old plans still has old plans, with no dunning, until it
-- converts. That is worth saying plainly rather than implying this fixed them.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.set_my_payment_plan(
    p_camp_id        uuid,
    p_enrollment_ids jsonb,   -- accepted for signature compatibility, IGNORED
    p_installments   jsonb    -- [{amount numeric, dueDate text}, ...]
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
    caller     uuid := auth.uid();
    inv        link_parent_invites;
    v_names    jsonb;
    me         jsonb;
    enr        jsonb;
    fams       jsonb;
    sess_list  jsonb;
    pays       jsonb;
    rec        record;
    famRec     record;
    e          jsonb;
    fam        jsonb;
    ch         jsonb;
    cr         jsonb;
    p          jsonb;
    v_tuition  numeric;
    v_liveT    numeric;
    v_disc     numeric;
    v_amt      numeric;
    v_status   text;
    v_family   text;
    v_enrIds   jsonb := '[]'::jsonb;
    v_billed   numeric := 0;
    v_paid     numeric := 0;
    v_credits  numeric := 0;
    v_target   numeric := 0;
    v_belongs  boolean;
    v_famKey   text := NULL;
    v_fam      jsonb := NULL;
    v_count    integer := 0;
    v_sum      numeric := 0;
    inst       jsonb;
    v_dates    jsonb := '[]'::jsonb;
    v_n        integer := 0;
    v_total    numeric := 0;
    v_famName  text;
    v_existingPlans jsonb;
    v_newPlan  jsonb;
BEGIN
    IF caller IS NULL THEN
        RETURN jsonb_build_object('success', false, 'error', 'not_authenticated');
    END IF;
    IF p_camp_id IS NULL OR p_installments IS NULL OR jsonb_typeof(p_installments) <> 'array' THEN
        RETURN jsonb_build_object('success', false, 'error', 'invalid_payload');
    END IF;

    SELECT * INTO inv
    FROM link_parent_invites
    WHERE user_id = caller
      AND (status = 'active' OR billing_access = true)
      AND (expires_at IS NULL OR expires_at > now())
      AND camp_id = p_camp_id
    ORDER BY created_at DESC
    LIMIT 1;
    IF NOT FOUND THEN
        RETURN jsonb_build_object('success', false, 'error', 'no_active_invite');
    END IF;
    v_names := COALESCE(inv.camper_names, '[]'::jsonb);

    SELECT value INTO me FROM camp_state_kv
    WHERE camp_id = p_camp_id AND key = 'campistryMe' FOR UPDATE;
    IF me IS NULL THEN
        RETURN jsonb_build_object('success', false, 'error', 'camp_not_found');
    END IF;

    IF NOT COALESCE((me #>> '{enrollSettings,allowParentPaymentPlans}')::boolean, false) THEN
        RETURN jsonb_build_object('success', false, 'error', 'self_serve_not_enabled');
    END IF;

    enr       := COALESCE(me->'enrollments', '{}'::jsonb);
    fams      := COALESCE(me->'families', '{}'::jsonb);
    sess_list := COALESCE(me->'sessions', '[]'::jsonb);
    pays      := COALESCE(me->'finance'->'payments', '[]'::jsonb);

    -- Target = this family's real outstanding balance, computed exactly
    -- like get_my_balance does (billed - paid - credits) — never a sum of
    -- specific enrollments' tuition, which would ignore prior payments,
    -- family-level charges, and credits already on the ledger.
    FOR rec IN SELECT key, value FROM jsonb_each(enr) LOOP
        e := rec.value;
        IF (v_names ? (e->>'camperName')) AND (e->>'status') IN ('enrolled', 'accepted') THEN
            v_liveT := (SELECT (s->>'tuition')::numeric FROM jsonb_array_elements(sess_list) s WHERE s->>'name' = e->>'session' LIMIT 1);
            v_tuition := CASE WHEN v_liveT IS NOT NULL AND v_liveT > 0 THEN v_liveT
                              ELSE COALESCE((e->>'sessionTuition')::numeric, 0) END;
            v_disc := 0;
            IF e->'discount' IS NOT NULL AND e->'discount' <> 'null'::jsonb THEN
                v_disc := COALESCE((e->'discount'->>'amt')::numeric, 0)
                        + ROUND(v_tuition * COALESCE((e->'discount'->>'pct')::numeric, 0) / 100);
            END IF;
            v_billed := v_billed + (v_tuition - v_disc);
            v_enrIds := v_enrIds || to_jsonb(rec.key);
        END IF;
    END LOOP;

    FOR famRec IN SELECT key, value FROM jsonb_each(fams) LOOP
        fam := famRec.value;
        v_belongs := EXISTS (
            SELECT 1 FROM jsonb_array_elements_text(COALESCE(fam->'camperIds', '[]'::jsonb)) ci
            WHERE v_names ? ci
        );
        IF NOT v_belongs THEN CONTINUE; END IF;
        IF v_famKey IS NULL THEN v_famKey := famRec.key; v_fam := fam; END IF;

        FOR ch IN SELECT * FROM jsonb_array_elements(COALESCE(fam->'charges', '[]'::jsonb)) LOOP
            v_billed := v_billed + COALESCE((ch->>'amount')::numeric, 0);
        END LOOP;
        FOR cr IN SELECT * FROM jsonb_array_elements(COALESCE(fam->'credits', '[]'::jsonb)) LOOP
            v_credits := v_credits + COALESCE((cr->>'amount')::numeric, 0);
        END LOOP;
    END LOOP;

    IF v_famKey IS NULL THEN
        RETURN jsonb_build_object('success', false, 'error', 'no_family_on_file');
    END IF;

    FOR p IN SELECT * FROM jsonb_array_elements(pays) LOOP
        v_family := COALESCE(p->>'family', '');
        IF (v_names ? v_family) OR (v_enrIds ? COALESCE(p->>'enrollmentId', '')) THEN
            v_amt := COALESCE((p->>'amount')::numeric, 0);
            v_status := COALESCE(p->>'status', '');
            IF v_status NOT IN ('pending', 'failed') THEN v_paid := v_paid + v_amt; END IF;
        END IF;
    END LOOP;

    v_target := v_billed - v_paid - v_credits;
    IF v_target <= 0 THEN
        RETURN jsonb_build_object('success', false, 'error', 'nothing_owed');
    END IF;

    -- Only one plan per family, full stop — reject if any plan already
    -- exists (per-camper or legacy whole-family), same as before.
    IF v_fam ? 'plans' AND jsonb_typeof(v_fam->'plans') = 'array' THEN
        v_existingPlans := v_fam->'plans';
    ELSIF v_fam ? 'plan' AND v_fam->'plan' <> 'null'::jsonb THEN
        v_existingPlans := jsonb_build_array(v_fam->'plan');
    ELSE
        v_existingPlans := '[]'::jsonb;
    END IF;
    IF jsonb_array_length(v_existingPlans) > 0 THEN
        RETURN jsonb_build_object('success', false, 'error', 'plan_already_exists');
    END IF;

    FOR inst IN SELECT * FROM jsonb_array_elements(p_installments) LOOP
        v_amt := COALESCE((inst->>'amount')::numeric, 0);
        IF v_amt <= 0 OR (inst->>'dueDate') IS NULL OR (inst->>'dueDate') = '' THEN CONTINUE; END IF;
        v_count := v_count + 1;
        v_sum := v_sum + v_amt;
    END LOOP;
    IF v_count < 1 OR v_count > 60 THEN
        RETURN jsonb_build_object('success', false, 'error', 'invalid_installment_count');
    END IF;
    IF abs(v_sum - v_target) > 0.05 THEN
        RETURN jsonb_build_object('success', false, 'error', 'total_mismatch', 'expected', v_target, 'submitted', v_sum);
    END IF;

    FOR inst IN SELECT * FROM jsonb_array_elements(p_installments) ORDER BY (value->>'dueDate') LOOP
        v_amt := COALESCE((inst->>'amount')::numeric, 0);
        IF v_amt <= 0 OR (inst->>'dueDate') IS NULL OR (inst->>'dueDate') = '' THEN CONTINUE; END IF;
        v_n := v_n + 1;
        v_total := v_total + v_amt;
        -- The amount was required, and was just checked against the balance
        -- above. It is deliberately NOT stored: a frozen amount is a number
        -- that disagrees with reality later, which is the defect the derived
        -- model exists to remove. Only the date survives.
        v_dates := v_dates || jsonb_build_array(inst->>'dueDate');
    END LOOP;

    v_famName := coalesce(v_fam->>'name', v_names->>0, inv.parent_name, 'Family');
    -- The LEDGER shape (migration 172): when and how many, never how much.
    -- Field for field what BillingCore.newPlan() produces, because both are
    -- read by plan_due — which is what decides the amount, from the balance,
    -- at the moment of the charge.
    v_newPlan := jsonb_build_object(
        'id', 'plan_' || replace(gen_random_uuid()::text, '-', ''),
        'enrollmentIds', NULL,
        'dueDates', v_dates,
        'count', v_n,
        'nextIndex', 0,
        'history', '[]'::jsonb,
        'autopay', false,
        'paused', false,
        -- A snapshot of what was owed the day it was built, for display only.
        -- Never what gets charged.
        'total', round(v_total, 2),
        'createdAt', now()::text, 'source', 'parent'
    );
    fams := jsonb_set(fams, ARRAY[v_famKey, 'plans'], jsonb_build_array(v_newPlan));
    fams := fams #- ARRAY[v_famKey, 'plan'];
    me := jsonb_set(me, ARRAY['families'], fams);

    UPDATE camp_state_kv SET value = me, updated_at = now()
    WHERE camp_id = p_camp_id AND key = 'campistryMe';

    INSERT INTO notifications (camp_id, source, source_id, title, body, link_target)
    VALUES (p_camp_id, 'parent_payment_plan_created', v_newPlan->>'id',
            'Family set up their own payment plan',
            v_famName || ' built a ' || v_n || '-payment plan (' || to_char(round(v_total,2), 'FM$999,999,990.00') || ' total) in Link.',
            'campistry_me.html')
    ON CONFLICT (camp_id, source, source_id) DO NOTHING;

    RETURN jsonb_build_object('success', true, 'plan', v_newPlan);
END;
$$;
REVOKE ALL ON FUNCTION public.set_my_payment_plan(uuid, jsonb, jsonb) FROM public;
GRANT EXECUTE ON FUNCTION public.set_my_payment_plan(uuid, jsonb, jsonb) TO authenticated;


-- ─── Checking it ───────────────────────────────────────────────────────────
-- As a parent's session, on a family with a real balance and no plan yet:
--   select set_my_payment_plan('<camp>'::uuid, null,
--     '[{"amount": 100, "dueDate": "2026-10-01"}]'::jsonb);
--   -- still total_mismatch unless 100 IS the balance: the target is unchanged.
--
-- With a schedule that does add up, the stored plan must carry dueDates and
-- NOT installments — that is the whole point:
--   select value #> '{families,<famKey>,plans,0}'
--     from camp_state_kv where camp_id='<camp>'::uuid and key='campistryMe';
--   -- {"id":"plan_…","dueDates":["2026-10-01",…],"count":3,"nextIndex":0,
--   --  "history":[],"autopay":false,"total":3000.00,…}   ← no "installments"
--
-- And the runner must now treat it as a ledger plan, deriving the amount:
--   select plan_due_for('<camp>'::uuid, '<famKey>', '<planId>', current_date::text);
-- ============================================================================
