#!/usr/bin/env python3
"""
Join a run of numbered migrations into ONE file to paste into the Supabase SQL
Editor once, instead of pasting each file by hand.

    python3 scripts/build-range-bundle.py 255 290
    -> migrations/APPLY_255_290.sql

Every migration in the range is taken in number order, whole, each under a
header naming its file. The SQL Editor runs a pasted script as one piece: if
any part fails, nothing in it is kept, and the red message names the part.
Every file is safe to run twice, so the bundle is too.

GENERATED — never edit the output by hand. After changing any migration in the
range, run this again (tests/range_bundle.test.js fails while it is stale).
"""
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MIG = os.path.join(REPO, "migrations")


def files_in(lo, hi):
    out = []
    for name in sorted(os.listdir(MIG)):
        m = re.match(r"^(\d{3})_.*\.sql$", name)
        if m and lo <= int(m.group(1)) <= hi:
            out.append(name)
    return out


def build(lo, hi):
    names = files_in(lo, hi)
    if not names:
        sys.exit(f"no migrations numbered {lo}-{hi}")
    head = f"""-- ============================================================================
-- APPLY_{lo}_{hi}.sql — migrations {lo} to {hi} in one paste.
--
-- GENERATED by `python3 scripts/build-range-bundle.py {lo} {hi}` — do not edit.
--
-- HOW TO USE: Supabase Dashboard → SQL Editor → New query → paste this whole
-- file → Run. It runs as one piece: if any part fails, nothing in it is kept,
-- and the red message says which part. Safe to run again.
-- Then paste scripts/verify_identity_chain.sql → Run: every row should say ok.
--
-- Contains ({len(names)} files, in this order):
""" + "".join(f"--   {n}\n" for n in names) + "-- ============================================================================\n"
    parts = [head]
    for n in names:
        with open(os.path.join(MIG, n), encoding="utf-8") as fh:
            body = fh.read().rstrip() + "\n"
        parts.append(f"\n\n-- ▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼\n"
                     f"-- {n}\n"
                     f"-- ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲\n\n" + body)
    return "".join(parts), names


if __name__ == "__main__":
    args = [a for a in sys.argv[1:] if a != "--check"]
    lo, hi = (int(args[0]), int(args[1])) if len(args) == 2 else (255, 290)
    text, names = build(lo, hi)
    out = os.path.join(MIG, f"APPLY_{lo}_{hi}.sql")
    if "--check" in sys.argv:
        current = open(out, encoding="utf-8").read() if os.path.exists(out) else ""
        if current != text:
            sys.exit(f"{os.path.relpath(out, REPO)} is out of date — run: python3 scripts/build-range-bundle.py {lo} {hi}")
        print(f"{os.path.relpath(out, REPO)} is up to date")
        sys.exit(0)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"Wrote {os.path.relpath(out, REPO)} ({len(text)} bytes, {len(names)} migrations)")
